// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: RefactorPrincipal

#ifndef _REFACTORPRINCIPAL_UI_H
#define _REFACTORPRINCIPAL_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////

#include "ui_PrincipalScreen.h"
#include "ui_ConfiguracionesScreen.h"
#include "ui_ResultadoScreen.h"
#include "ui_SplashScreen.h"
#include "ui_EsperandoScreen.h"
#include "ui_EnCursoScreen.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_fiuner3201_png);    // assets/fiuner320.png

// Iconos de estado de los headers de Principal y Resultado. Vienen de a
// pares activo/fallo: el controlador muestra uno y oculta el otro, no hay
// un tercer estado "desconocido".
LV_IMG_DECLARE(ui_img_link_activo_png);    // assets/link_activo.png
LV_IMG_DECLARE(ui_img_link_fallo_png);    // assets/link_fallo.png
LV_IMG_DECLARE(ui_img_sd_activo_png);    // assets/sd_activo.png
LV_IMG_DECLARE(ui_img_sd_fallo_png);    // assets/sd_fallo.png
LV_IMG_DECLARE(ui_img_wifi_activo_png);    // assets/wifi_activo.png
LV_IMG_DECLARE(ui_img_wifi_fallo_png);    // assets/wifi_fallo.png
LV_IMG_DECLARE(ui_img_telemetry_activo_png);    // assets/telemetry_activo.png
LV_IMG_DECLARE(ui_img_telemetry_fallo_png);    // assets/telemetry_fallo.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
