// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Principal2

#ifndef _PRINCIPAL2_UI_H
#define _PRINCIPAL2_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////

#include "ui_Splash.h"
#include "ui_Principal.h"
#include "ui_Configuracion.h"
#include "ui_Running.h"
#include "ui_Resultado.h"
#include "ui_Busy.h"
///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_campo_png);    // assets/campo.png
LV_IMG_DECLARE(ui_img_frecuencia_png);    // assets/frecuencia.png
LV_IMG_DECLARE(ui_img_2_png);    // assets/2.png
LV_IMG_DECLARE(ui_img_tolcampo_png);    // assets/tolcampo.png
LV_IMG_DECLARE(ui_img_temp_normal_png);    // assets/temp_normal.png
LV_IMG_DECLARE(ui_img_temp_critica_png);    // assets/temp_critica.png
LV_IMG_DECLARE(ui_img_configuracion_png);    // assets/configuracion.png
LV_IMG_DECLARE(ui_img_iniciar_png);    // assets/iniciar.png
LV_IMG_DECLARE(ui_img_monitor_png);    // assets/monitor.png
LV_IMG_DECLARE(ui_img_estadook_png);    // assets/estadook.png
LV_IMG_DECLARE(ui_img_estadowarning_png);    // assets/estadowarning.png
LV_IMG_DECLARE(ui_img_estadocritical_png);    // assets/estadocritical.png
LV_IMG_DECLARE(ui_img_bobina_png);    // assets/bobina.png
LV_IMG_DECLARE(ui_img_alertacritica_png);    // assets/alertacritica.png
LV_IMG_DECLARE(ui_img_splash_png);    // assets/splash.png
LV_IMG_DECLARE(ui_img_7_png);    // assets/7.png
LV_IMG_DECLARE(ui_img_volver_png);    // assets/volver.png
LV_IMG_DECLARE(ui_img_guardar_png);    // assets/guardar.png


// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
