// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Busy

#include "ui.h"

lv_obj_t * ui_Busy = NULL;
lv_obj_t * ui_BusyMain = NULL;
lv_obj_t * ui_BusySpinner = NULL;
lv_obj_t * ui_BusyMensaje = NULL;
// event funtions

// build funtions

void ui_Busy_screen_init(void)
{
    ui_Busy = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Busy, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BusyMain = lv_obj_create(ui_Busy);
    lv_obj_remove_style_all(ui_BusyMain);
    lv_obj_set_width(ui_BusyMain, lv_pct(100));
    lv_obj_set_height(ui_BusyMain, lv_pct(100));
    lv_obj_set_align(ui_BusyMain, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_BusyMain, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_BusyMain, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_BusyMain, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_set_style_pad_left(ui_BusyMain, 5, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_BusyMain, 5, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_BusyMain, 5, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_BusyMain, 5, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_BusyMain, 5, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_BusyMain, 5, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_BusySpinner = lv_spinner_create(ui_BusyMain);
    //lv_spinner_set_anim_params(ui_BusySpinner, 1000, 90);
    lv_obj_set_width(ui_BusySpinner, 80);
    lv_obj_set_height(ui_BusySpinner, 80);
    lv_obj_set_align(ui_BusySpinner, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_BusySpinner, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_BusySpinner, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_BusySpinner, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_BusyMensaje = lv_label_create(ui_BusyMain);
    lv_obj_set_width(ui_BusyMensaje, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BusyMensaje, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BusyMensaje, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_BusyMensaje, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_BusyMensaje, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_BusyMensaje, "Procesando...");
    lv_obj_set_style_pad_left(ui_BusyMensaje, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_BusyMensaje, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_BusyMensaje, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_BusyMensaje, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Busy_screen_destroy(void)
{
    if(ui_Busy) lv_obj_del(ui_Busy);

    // NULL screen variables
    ui_Busy = NULL;
    ui_BusyMain = NULL;
    ui_BusySpinner = NULL;
    ui_BusyMensaje = NULL;

}
