// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Busy

#ifndef UI_BUSY_H
#define UI_BUSY_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Busy
extern void ui_Busy_screen_init(void);
extern void ui_Busy_screen_destroy(void);
extern lv_obj_t * ui_Busy;
extern lv_obj_t * ui_BusyMain;
extern lv_obj_t * ui_BusySpinner;
extern lv_obj_t * ui_BusyMensaje;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

