// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Configuracion

#include "ui.h"

lv_obj_t * ui_Configuracion = NULL;
lv_obj_t * ui_ContiguracionHead = NULL;
lv_obj_t * ui_ConfiguracionHeadImg = NULL;
lv_obj_t * ui_ContiguracionHeadTitulo = NULL;
lv_obj_t * ui_ConfiguracionButtons = NULL;
lv_obj_t * ui_ConfiguracionGuardarBtn = NULL;
lv_obj_t * ui_ConfiguracionGuardarBtnImg = NULL;
lv_obj_t * ui_ConfiguracionVolverBtn = NULL;
lv_obj_t * ui_ConfiguracionVolverBtnImg = NULL;
lv_obj_t * ui_ConfiguracionMain = NULL;
lv_obj_t * ui_DuracionImg = NULL;
lv_obj_t * ui_DuracionOpciones = NULL;
lv_obj_t * ui_CampoImg = NULL;
lv_obj_t * ui_CampoOpciones = NULL;
lv_obj_t * ui_FrecuenciaImg = NULL;
lv_obj_t * ui_FrecuenciaOpciones = NULL;
lv_obj_t * ui_ToleranciaCampoImg = NULL;
lv_obj_t * ui_ToleranciaCampoOpciones = NULL;
lv_obj_t * ui_RangoTempNormalImg = NULL;
lv_obj_t * ui_RangoTempNormalOpciones = NULL;
lv_obj_t * ui_RangoTempCritImg = NULL;
lv_obj_t * ui_RangoTempCritOpciones = NULL;
// Bring-up temporal INT-001 (2026-08-31): agregado a mano, NO viene del
// .sll de SquareLine Studio -- quitar (junto con la declaracion en
// ui_Configuracion.h) una vez terminadas las 6 pruebas de laboratorio.
// event funtions

// build funtions

void ui_Configuracion_screen_init(void)
{
    ui_Configuracion = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Configuracion, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ContiguracionHead = lv_obj_create(ui_Configuracion);
    lv_obj_remove_style_all(ui_ContiguracionHead);
    lv_obj_set_height(ui_ContiguracionHead, 42);
    lv_obj_set_width(ui_ContiguracionHead, lv_pct(100));
    lv_obj_set_x(ui_ContiguracionHead, 0);
    lv_obj_set_y(ui_ContiguracionHead, -98);
    lv_obj_set_align(ui_ContiguracionHead, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ContiguracionHead, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ContiguracionHead, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ContiguracionHead, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ContiguracionHead, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ContiguracionHead, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_ContiguracionHead, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ContiguracionHead, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConfiguracionHeadImg = lv_image_create(ui_ContiguracionHead);
    lv_image_set_src(ui_ConfiguracionHeadImg, &ui_img_configuracion_png);
    lv_obj_set_width(ui_ConfiguracionHeadImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ConfiguracionHeadImg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ConfiguracionHeadImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ConfiguracionHeadImg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_ConfiguracionHeadImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ContiguracionHeadTitulo = lv_label_create(ui_ContiguracionHead);
    lv_obj_set_width(ui_ContiguracionHeadTitulo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ContiguracionHeadTitulo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ContiguracionHeadTitulo, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ContiguracionHeadTitulo, "Configuracion del experimento");

    ui_ConfiguracionButtons = lv_obj_create(ui_Configuracion);
    lv_obj_remove_style_all(ui_ConfiguracionButtons);
    lv_obj_set_width(ui_ConfiguracionButtons, 55);
    lv_obj_set_height(ui_ConfiguracionButtons, 200);
    lv_obj_set_x(ui_ConfiguracionButtons, 130);
    lv_obj_set_y(ui_ConfiguracionButtons, 18);
    lv_obj_set_align(ui_ConfiguracionButtons, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ConfiguracionButtons, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_ConfiguracionButtons, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_ConfiguracionButtons, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_ConfiguracionButtons, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ConfiguracionButtons, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ConfiguracionButtons, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ConfiguracionButtons, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_ConfiguracionButtons, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ConfiguracionButtons, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConfiguracionGuardarBtn = lv_button_create(ui_ConfiguracionButtons);
    lv_obj_set_height(ui_ConfiguracionGuardarBtn, 50);
    lv_obj_set_width(ui_ConfiguracionGuardarBtn, lv_pct(100));
    lv_obj_set_align(ui_ConfiguracionGuardarBtn, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ConfiguracionGuardarBtn, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ConfiguracionGuardarBtn, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_ConfiguracionGuardarBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ConfiguracionGuardarBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ConfiguracionGuardarBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ConfiguracionGuardarBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConfiguracionGuardarBtnImg = lv_image_create(ui_ConfiguracionGuardarBtn);
    lv_image_set_src(ui_ConfiguracionGuardarBtnImg, &ui_img_guardar_png);
    lv_obj_set_width(ui_ConfiguracionGuardarBtnImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ConfiguracionGuardarBtnImg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ConfiguracionGuardarBtnImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ConfiguracionGuardarBtnImg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_ConfiguracionGuardarBtnImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ConfiguracionVolverBtn = lv_button_create(ui_ConfiguracionButtons);
    lv_obj_set_height(ui_ConfiguracionVolverBtn, 50);
    lv_obj_set_width(ui_ConfiguracionVolverBtn, lv_pct(100));
    lv_obj_set_align(ui_ConfiguracionVolverBtn, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ConfiguracionVolverBtn, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ConfiguracionVolverBtn, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_ConfiguracionVolverBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ConfiguracionVolverBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ConfiguracionVolverBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ConfiguracionVolverBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConfiguracionVolverBtnImg = lv_image_create(ui_ConfiguracionVolverBtn);
    lv_image_set_src(ui_ConfiguracionVolverBtnImg, &ui_img_volver_png);
    lv_obj_set_width(ui_ConfiguracionVolverBtnImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ConfiguracionVolverBtnImg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ConfiguracionVolverBtnImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ConfiguracionVolverBtnImg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_ConfiguracionVolverBtnImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ConfiguracionMain = lv_obj_create(ui_Configuracion);
    lv_obj_set_width(ui_ConfiguracionMain, 255);
    lv_obj_set_height(ui_ConfiguracionMain, 190);
    lv_obj_set_x(ui_ConfiguracionMain, -30);
    lv_obj_set_y(ui_ConfiguracionMain, 23);
    lv_obj_set_align(ui_ConfiguracionMain, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ConfiguracionMain, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_ConfiguracionMain, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_set_scroll_dir(ui_ConfiguracionMain, LV_DIR_VER);

    ui_DuracionImg = lv_image_create(ui_ConfiguracionMain);
    lv_image_set_src(ui_DuracionImg, &ui_img_2_png);
    lv_obj_set_width(ui_DuracionImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DuracionImg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_DuracionImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DuracionImg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_DuracionImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_DuracionOpciones = lv_dropdown_create(ui_ConfiguracionMain);
    lv_obj_set_width(ui_DuracionOpciones, 150);
    lv_obj_set_height(ui_DuracionOpciones, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_DuracionOpciones, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DuracionOpciones, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_CampoImg = lv_image_create(ui_ConfiguracionMain);
    lv_image_set_src(ui_CampoImg, &ui_img_campo_png);
    lv_obj_set_width(ui_CampoImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CampoImg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_CampoImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CampoImg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_CampoImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_CampoOpciones = lv_dropdown_create(ui_ConfiguracionMain);
    lv_obj_set_width(ui_CampoOpciones, 150);
    lv_obj_set_height(ui_CampoOpciones, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_CampoOpciones, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CampoOpciones, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_FrecuenciaImg = lv_image_create(ui_ConfiguracionMain);
    lv_image_set_src(ui_FrecuenciaImg, &ui_img_frecuencia_png);
    lv_obj_set_width(ui_FrecuenciaImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FrecuenciaImg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_FrecuenciaImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_FrecuenciaImg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_FrecuenciaImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_FrecuenciaOpciones = lv_dropdown_create(ui_ConfiguracionMain);
    lv_obj_set_width(ui_FrecuenciaOpciones, 150);
    lv_obj_set_height(ui_FrecuenciaOpciones, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_FrecuenciaOpciones, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_FrecuenciaOpciones, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_ToleranciaCampoImg = lv_image_create(ui_ConfiguracionMain);
    lv_image_set_src(ui_ToleranciaCampoImg, &ui_img_tolcampo_png);
    lv_obj_set_width(ui_ToleranciaCampoImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ToleranciaCampoImg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ToleranciaCampoImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ToleranciaCampoImg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_ToleranciaCampoImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ToleranciaCampoOpciones = lv_dropdown_create(ui_ConfiguracionMain);
    lv_obj_set_width(ui_ToleranciaCampoOpciones, 150);
    lv_obj_set_height(ui_ToleranciaCampoOpciones, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ToleranciaCampoOpciones, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ToleranciaCampoOpciones, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_RangoTempNormalImg = lv_image_create(ui_ConfiguracionMain);
    lv_image_set_src(ui_RangoTempNormalImg, &ui_img_temp_normal_png);
    lv_obj_set_width(ui_RangoTempNormalImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RangoTempNormalImg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_RangoTempNormalImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_RangoTempNormalImg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_RangoTempNormalImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_RangoTempNormalOpciones = lv_dropdown_create(ui_ConfiguracionMain);
    lv_obj_set_width(ui_RangoTempNormalOpciones, 150);
    lv_obj_set_height(ui_RangoTempNormalOpciones, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_RangoTempNormalOpciones, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_RangoTempNormalOpciones, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_RangoTempCritImg = lv_image_create(ui_ConfiguracionMain);
    lv_image_set_src(ui_RangoTempCritImg, &ui_img_temp_critica_png);
    lv_obj_set_width(ui_RangoTempCritImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RangoTempCritImg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_RangoTempCritImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_RangoTempCritImg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_RangoTempCritImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_RangoTempCritOpciones = lv_dropdown_create(ui_ConfiguracionMain);
    lv_obj_set_width(ui_RangoTempCritOpciones, 150);
    lv_obj_set_height(ui_RangoTempCritOpciones, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_RangoTempCritOpciones, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_RangoTempCritOpciones, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

}

void ui_Configuracion_screen_destroy(void)
{
    if(ui_Configuracion) lv_obj_del(ui_Configuracion);

    // NULL screen variables
    ui_Configuracion = NULL;
    ui_ContiguracionHead = NULL;
    ui_ConfiguracionHeadImg = NULL;
    ui_ContiguracionHeadTitulo = NULL;
    ui_ConfiguracionButtons = NULL;
    ui_ConfiguracionGuardarBtn = NULL;
    ui_ConfiguracionGuardarBtnImg = NULL;
    ui_ConfiguracionVolverBtn = NULL;
    ui_ConfiguracionVolverBtnImg = NULL;
    ui_ConfiguracionMain = NULL;
    ui_DuracionImg = NULL;
    ui_DuracionOpciones = NULL;
    ui_CampoImg = NULL;
    ui_CampoOpciones = NULL;
    ui_FrecuenciaImg = NULL;
    ui_FrecuenciaOpciones = NULL;
    ui_ToleranciaCampoImg = NULL;
    ui_ToleranciaCampoOpciones = NULL;
    ui_RangoTempNormalImg = NULL;
    ui_RangoTempNormalOpciones = NULL;
    ui_RangoTempCritImg = NULL;
    ui_RangoTempCritOpciones = NULL;

}
