// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: UiFinalParte1

#ifndef UI_CONFIGURACIONESSCREEN_H
#define UI_CONFIGURACIONESSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ConfiguracionesScreen
extern void ui_ConfiguracionesScreen_screen_init(void);
extern void ui_ConfiguracionesScreen_screen_destroy(void);
extern lv_obj_t * ui_ConfiguracionesScreen;
extern lv_obj_t * ui_ConfiguracionesHeader;
extern lv_obj_t * ui_ConfiguracionesTitle;
extern lv_obj_t * ui_ConfiguracionesMain;
extern lv_obj_t * ui_ConfiguracionModo;
extern lv_obj_t * ui_ConfiguracionModoTitle;
extern lv_obj_t * ui_ConfiguracionModoOpciones;
extern lv_obj_t * ui_ConfiguracionIntensidadCampo;
extern lv_obj_t * ui_ConfiguracionIntensidadCampoTitle;
extern lv_obj_t * ui_ConfiguracionIntensidadCampoOpciones;
extern lv_obj_t * ui_ConfiguracionFrecuencia;
extern lv_obj_t * ui_ConfiguracionFrecuenciaTitle;
extern lv_obj_t * ui_ConfiguracionFrecuenciaOpciones;
extern lv_obj_t * ui_ConfiguracionDuracion;
extern lv_obj_t * ui_ConfiguracionDuracionTitle;
extern lv_obj_t * ui_ConfiguracionDuracionOpciones;
extern lv_obj_t * ui_ConfiguracionTempNormal;
extern lv_obj_t * ui_ConfiguracionTempNormalTitle;
extern lv_obj_t * ui_ConfiguracionTempNormalOpciones;
extern lv_obj_t * ui_ConfiguracionTempCritica;
extern lv_obj_t * ui_ConfiguracionTempCriticaTitle;
extern lv_obj_t * ui_ConfiguracionTempCriticaOpciones;
extern lv_obj_t * ui_ConfiguracionTolIntensidad;
extern lv_obj_t * ui_ConfiguracionTolIntensidadTitle;
extern lv_obj_t * ui_ConfiguracionTolIntensidadOpciones;
extern lv_obj_t * ui_ConfiguracionesOptionsButtons;
extern lv_obj_t * ui_ButtonConfiguracionVolver;
extern lv_obj_t * ui_ButtonConfiguracionVolverTexto;
extern lv_obj_t * ui_ButtonConfiguracionGuardar;
extern lv_obj_t * ui_ButtonConfiguracionGuardarTexto;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

