// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Configuracion

#ifndef UI_CONFIGURACION_H
#define UI_CONFIGURACION_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Configuracion
extern void ui_Configuracion_screen_init(void);
extern void ui_Configuracion_screen_destroy(void);
extern lv_obj_t * ui_Configuracion;
extern lv_obj_t * ui_ContiguracionHead;
extern lv_obj_t * ui_ConfiguracionHeadImg;
extern lv_obj_t * ui_ContiguracionHeadTitulo;
extern lv_obj_t * ui_ConfiguracionButtons;
extern lv_obj_t * ui_ConfiguracionGuardarBtn;
extern lv_obj_t * ui_ConfiguracionGuardarBtnImg;
extern lv_obj_t * ui_ConfiguracionVolverBtn;
extern lv_obj_t * ui_ConfiguracionVolverBtnImg;
extern lv_obj_t * ui_ConfiguracionMain;
extern lv_obj_t * ui_DuracionImg;
extern lv_obj_t * ui_DuracionOpciones;
extern lv_obj_t * ui_CampoImg;
extern lv_obj_t * ui_CampoOpciones;
extern lv_obj_t * ui_FrecuenciaImg;
extern lv_obj_t * ui_FrecuenciaOpciones;
extern lv_obj_t * ui_ToleranciaCampoImg;
extern lv_obj_t * ui_ToleranciaCampoOpciones;
extern lv_obj_t * ui_RangoTempNormalImg;
extern lv_obj_t * ui_RangoTempNormalOpciones;
extern lv_obj_t * ui_RangoTempCritImg;
extern lv_obj_t * ui_RangoTempCritOpciones;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

