// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: UiFinalParte1

#include "ui.h"

lv_obj_t * ui_ConfiguracionesScreen = NULL;
lv_obj_t * ui_ConfiguracionesHeader = NULL;
lv_obj_t * ui_ConfiguracionesTitle = NULL;
lv_obj_t * ui_ConfiguracionesMain = NULL;
lv_obj_t * ui_ConfiguracionModo = NULL;
lv_obj_t * ui_ConfiguracionModoTitle = NULL;
lv_obj_t * ui_ConfiguracionModoOpciones = NULL;
lv_obj_t * ui_ConfiguracionIntensidadCampo = NULL;
lv_obj_t * ui_ConfiguracionIntensidadCampoTitle = NULL;
lv_obj_t * ui_ConfiguracionIntensidadCampoOpciones = NULL;
lv_obj_t * ui_ConfiguracionFrecuencia = NULL;
lv_obj_t * ui_ConfiguracionFrecuenciaTitle = NULL;
lv_obj_t * ui_ConfiguracionFrecuenciaOpciones = NULL;
lv_obj_t * ui_ConfiguracionDuracion = NULL;
lv_obj_t * ui_ConfiguracionDuracionTitle = NULL;
lv_obj_t * ui_ConfiguracionDuracionOpciones = NULL;
lv_obj_t * ui_ConfiguracionTempNormal = NULL;
lv_obj_t * ui_ConfiguracionTempNormalTitle = NULL;
lv_obj_t * ui_ConfiguracionTempNormalOpciones = NULL;
lv_obj_t * ui_ConfiguracionTempCritica = NULL;
lv_obj_t * ui_ConfiguracionTempCriticaTitle = NULL;
lv_obj_t * ui_ConfiguracionTempCriticaOpciones = NULL;
lv_obj_t * ui_ConfiguracionTolIntensidad = NULL;
lv_obj_t * ui_ConfiguracionTolIntensidadTitle = NULL;
lv_obj_t * ui_ConfiguracionTolIntensidadOpciones = NULL;
lv_obj_t * ui_ConfiguracionesOptionsButtons = NULL;
lv_obj_t * ui_ButtonConfiguracionVolver = NULL;
lv_obj_t * ui_ButtonConfiguracionVolverTexto = NULL;
lv_obj_t * ui_ButtonConfiguracionGuardar = NULL;
lv_obj_t * ui_ButtonConfiguracionGuardarTexto = NULL;
// event funtions

// build funtions

void ui_ConfiguracionesScreen_screen_init(void)
{
    ui_ConfiguracionesScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_ConfiguracionesScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_ConfiguracionesScreen, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_ConfiguracionesScreen, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_style_bg_color(ui_ConfiguracionesScreen, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ConfiguracionesScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ConfiguracionesScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ConfiguracionesScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ConfiguracionesScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ConfiguracionesScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_ConfiguracionesScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ConfiguracionesScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConfiguracionesHeader = lv_obj_create(ui_ConfiguracionesScreen);
    lv_obj_set_height(ui_ConfiguracionesHeader, 40);
    lv_obj_set_width(ui_ConfiguracionesHeader, lv_pct(100));
    lv_obj_set_align(ui_ConfiguracionesHeader, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ConfiguracionesHeader, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ConfiguracionesHeader, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ConfiguracionesHeader, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ConfiguracionesHeader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ConfiguracionesHeader, lv_color_hex(0x0A3358), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ConfiguracionesHeader, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ConfiguracionesHeader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ConfiguracionesHeader, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ConfiguracionesHeader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ConfiguracionesHeader, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ConfiguracionesHeader, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_ConfiguracionesHeader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ConfiguracionesHeader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConfiguracionesTitle = lv_label_create(ui_ConfiguracionesHeader);
    lv_obj_set_width(ui_ConfiguracionesTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ConfiguracionesTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ConfiguracionesTitle, 0);
    lv_obj_set_y(ui_ConfiguracionesTitle, 1);
    lv_obj_set_align(ui_ConfiguracionesTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ConfiguracionesTitle, "CONFIGURACION");
    lv_obj_set_style_text_color(ui_ConfiguracionesTitle, lv_color_hex(0x7FC0FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ConfiguracionesTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ConfiguracionesTitle, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConfiguracionesMain = lv_obj_create(ui_ConfiguracionesScreen);
    lv_obj_set_height(ui_ConfiguracionesMain, 160);
    lv_obj_set_width(ui_ConfiguracionesMain, lv_pct(100));
    lv_obj_set_x(ui_ConfiguracionesMain, 1);
    lv_obj_set_y(ui_ConfiguracionesMain, 0);
    lv_obj_set_align(ui_ConfiguracionesMain, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ConfiguracionesMain, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_ConfiguracionesMain, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_ConfiguracionesMain, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ConfiguracionesMain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ConfiguracionesMain, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ConfiguracionesMain, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ConfiguracionesMain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ConfiguracionesMain, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ConfiguracionesMain, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ConfiguracionesMain, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ConfiguracionesMain, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ConfiguracionesMain, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_ConfiguracionesMain, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ConfiguracionesMain, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConfiguracionModo = lv_obj_create(ui_ConfiguracionesMain);
    lv_obj_set_width(ui_ConfiguracionModo, lv_pct(100));
    lv_obj_set_height(ui_ConfiguracionModo, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_ConfiguracionModo, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ConfiguracionModo, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ConfiguracionModo, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_END);
    lv_obj_remove_flag(ui_ConfiguracionModo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ConfiguracionModo, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ConfiguracionModo, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ConfiguracionModo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ConfiguracionModo, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ConfiguracionModo, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ConfiguracionModo, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ConfiguracionModo, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ConfiguracionModo, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ConfiguracionModo, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_ConfiguracionModo, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ConfiguracionModo, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConfiguracionModoTitle = lv_label_create(ui_ConfiguracionModo);
    lv_obj_set_width(ui_ConfiguracionModoTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ConfiguracionModoTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ConfiguracionModoTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ConfiguracionModoTitle, "MODO");
    lv_obj_set_style_text_color(ui_ConfiguracionModoTitle, lv_color_hex(0x2E628F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ConfiguracionModoTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ConfiguracionModoTitle, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConfiguracionModoOpciones = lv_dropdown_create(ui_ConfiguracionModo);
    lv_dropdown_set_options(ui_ConfiguracionModoOpciones, "        CAMPO X\nCAMPO NULO\n");
    lv_obj_set_width(ui_ConfiguracionModoOpciones, lv_pct(46));
    lv_obj_set_height(ui_ConfiguracionModoOpciones, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ConfiguracionModoOpciones, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_ConfiguracionModoOpciones, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_ConfiguracionModoOpciones, lv_color_hex(0x2E628F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ConfiguracionModoOpciones, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ConfiguracionModoOpciones, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ConfiguracionModoOpciones, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ConfiguracionModoOpciones, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ConfiguracionModoOpciones, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ConfiguracionModoOpciones, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ConfiguracionModoOpciones, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ConfiguracionModoOpciones, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ConfiguracionModoOpciones, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ConfiguracionModoOpciones, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ConfiguracionModoOpciones, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_ConfiguracionModoOpciones, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ConfiguracionModoOpciones, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_align(lv_dropdown_get_list(ui_ConfiguracionModoOpciones), LV_TEXT_ALIGN_RIGHT,
                                LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_align(lv_dropdown_get_list(ui_ConfiguracionModoOpciones), LV_TEXT_ALIGN_RIGHT,
                                LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_ConfiguracionIntensidadCampo = lv_obj_create(ui_ConfiguracionesMain);
    lv_obj_set_width(ui_ConfiguracionIntensidadCampo, 101);
    lv_obj_set_height(ui_ConfiguracionIntensidadCampo, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_ConfiguracionIntensidadCampo, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ConfiguracionIntensidadCampo, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_ConfiguracionIntensidadCampo, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_ConfiguracionIntensidadCampo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ConfiguracionIntensidadCampo, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ConfiguracionIntensidadCampo, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ConfiguracionIntensidadCampo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ConfiguracionIntensidadCampo, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ConfiguracionIntensidadCampo, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ConfiguracionIntensidadCampo, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ConfiguracionIntensidadCampo, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ConfiguracionIntensidadCampo, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ConfiguracionIntensidadCampo, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_ConfiguracionIntensidadCampo, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ConfiguracionIntensidadCampo, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConfiguracionIntensidadCampoTitle = lv_label_create(ui_ConfiguracionIntensidadCampo);
    lv_obj_set_width(ui_ConfiguracionIntensidadCampoTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ConfiguracionIntensidadCampoTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ConfiguracionIntensidadCampoTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ConfiguracionIntensidadCampoTitle, "INTENSIDAD");
    lv_obj_set_style_text_color(ui_ConfiguracionIntensidadCampoTitle, lv_color_hex(0x2E628F),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ConfiguracionIntensidadCampoTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ConfiguracionIntensidadCampoTitle, &lv_font_montserrat_10,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConfiguracionIntensidadCampoOpciones = lv_dropdown_create(ui_ConfiguracionIntensidadCampo);
    lv_obj_set_width(ui_ConfiguracionIntensidadCampoOpciones, 90);
    lv_obj_set_height(ui_ConfiguracionIntensidadCampoOpciones, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ConfiguracionIntensidadCampoOpciones, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ConfiguracionIntensidadCampoOpciones, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_ConfiguracionIntensidadCampoOpciones, lv_color_hex(0x2E628F),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ConfiguracionIntensidadCampoOpciones, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ConfiguracionIntensidadCampoOpciones, LV_TEXT_ALIGN_AUTO,
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ConfiguracionIntensidadCampoOpciones, &lv_font_montserrat_16,
                               LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ConfiguracionIntensidadCampoOpciones, lv_color_hex(0x2E628F),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ConfiguracionIntensidadCampoOpciones, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ConfiguracionIntensidadCampoOpciones, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ConfiguracionIntensidadCampoOpciones, LV_BORDER_SIDE_BOTTOM,
                                 LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ConfiguracionIntensidadCampoOpciones, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ConfiguracionIntensidadCampoOpciones, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ConfiguracionIntensidadCampoOpciones, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ConfiguracionIntensidadCampoOpciones, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_ConfiguracionIntensidadCampoOpciones, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ConfiguracionIntensidadCampoOpciones, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConfiguracionFrecuencia = lv_obj_create(ui_ConfiguracionesMain);
    lv_obj_set_width(ui_ConfiguracionFrecuencia, 102);
    lv_obj_set_height(ui_ConfiguracionFrecuencia, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_ConfiguracionFrecuencia, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ConfiguracionFrecuencia, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_ConfiguracionFrecuencia, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_ConfiguracionFrecuencia, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ConfiguracionFrecuencia, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ConfiguracionFrecuencia, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ConfiguracionFrecuencia, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ConfiguracionFrecuencia, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ConfiguracionFrecuencia, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ConfiguracionFrecuencia, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ConfiguracionFrecuencia, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ConfiguracionFrecuencia, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ConfiguracionFrecuencia, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_ConfiguracionFrecuencia, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ConfiguracionFrecuencia, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConfiguracionFrecuenciaTitle = lv_label_create(ui_ConfiguracionFrecuencia);
    lv_obj_set_width(ui_ConfiguracionFrecuenciaTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ConfiguracionFrecuenciaTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ConfiguracionFrecuenciaTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ConfiguracionFrecuenciaTitle, "FRECUENCIA");
    lv_obj_set_style_text_color(ui_ConfiguracionFrecuenciaTitle, lv_color_hex(0x2E628F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ConfiguracionFrecuenciaTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ConfiguracionFrecuenciaTitle, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConfiguracionFrecuenciaOpciones = lv_dropdown_create(ui_ConfiguracionFrecuencia);
    lv_obj_set_width(ui_ConfiguracionFrecuenciaOpciones, lv_pct(100));
    lv_obj_set_height(ui_ConfiguracionFrecuenciaOpciones, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ConfiguracionFrecuenciaOpciones, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ConfiguracionFrecuenciaOpciones, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_ConfiguracionFrecuenciaOpciones, lv_color_hex(0x2E628F),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ConfiguracionFrecuenciaOpciones, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ConfiguracionFrecuenciaOpciones, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ConfiguracionFrecuenciaOpciones, lv_color_hex(0x2E628F),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ConfiguracionFrecuenciaOpciones, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ConfiguracionFrecuenciaOpciones, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ConfiguracionFrecuenciaOpciones, LV_BORDER_SIDE_BOTTOM,
                                 LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ConfiguracionFrecuenciaOpciones, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ConfiguracionFrecuenciaOpciones, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ConfiguracionFrecuenciaOpciones, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ConfiguracionFrecuenciaOpciones, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_ConfiguracionFrecuenciaOpciones, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ConfiguracionFrecuenciaOpciones, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConfiguracionDuracion = lv_obj_create(ui_ConfiguracionesMain);
    lv_obj_set_width(ui_ConfiguracionDuracion, 101);
    lv_obj_set_height(ui_ConfiguracionDuracion, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_ConfiguracionDuracion, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ConfiguracionDuracion, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_ConfiguracionDuracion, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_ConfiguracionDuracion, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ConfiguracionDuracion, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ConfiguracionDuracion, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ConfiguracionDuracion, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ConfiguracionDuracion, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ConfiguracionDuracion, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ConfiguracionDuracion, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ConfiguracionDuracion, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ConfiguracionDuracion, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ConfiguracionDuracion, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_ConfiguracionDuracion, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ConfiguracionDuracion, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConfiguracionDuracionTitle = lv_label_create(ui_ConfiguracionDuracion);
    lv_obj_set_width(ui_ConfiguracionDuracionTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ConfiguracionDuracionTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ConfiguracionDuracionTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ConfiguracionDuracionTitle, "DURACION");
    lv_obj_set_style_text_color(ui_ConfiguracionDuracionTitle, lv_color_hex(0x2E628F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ConfiguracionDuracionTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ConfiguracionDuracionTitle, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConfiguracionDuracionOpciones = lv_dropdown_create(ui_ConfiguracionDuracion);
    lv_obj_set_width(ui_ConfiguracionDuracionOpciones, lv_pct(100));
    lv_obj_set_height(ui_ConfiguracionDuracionOpciones, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ConfiguracionDuracionOpciones, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ConfiguracionDuracionOpciones, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_ConfiguracionDuracionOpciones, lv_color_hex(0x2E628F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ConfiguracionDuracionOpciones, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ConfiguracionDuracionOpciones, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ConfiguracionDuracionOpciones, lv_color_hex(0x2E628F),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ConfiguracionDuracionOpciones, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ConfiguracionDuracionOpciones, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ConfiguracionDuracionOpciones, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ConfiguracionDuracionOpciones, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ConfiguracionDuracionOpciones, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ConfiguracionDuracionOpciones, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ConfiguracionDuracionOpciones, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_ConfiguracionDuracionOpciones, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ConfiguracionDuracionOpciones, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConfiguracionTempNormal = lv_obj_create(ui_ConfiguracionesMain);
    lv_obj_set_width(ui_ConfiguracionTempNormal, 101);
    lv_obj_set_height(ui_ConfiguracionTempNormal, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_ConfiguracionTempNormal, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ConfiguracionTempNormal, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_ConfiguracionTempNormal, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_ConfiguracionTempNormal, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ConfiguracionTempNormal, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ConfiguracionTempNormal, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ConfiguracionTempNormal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ConfiguracionTempNormal, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ConfiguracionTempNormal, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ConfiguracionTempNormal, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ConfiguracionTempNormal, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ConfiguracionTempNormal, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ConfiguracionTempNormal, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_ConfiguracionTempNormal, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ConfiguracionTempNormal, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConfiguracionTempNormalTitle = lv_label_create(ui_ConfiguracionTempNormal);
    lv_obj_set_width(ui_ConfiguracionTempNormalTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ConfiguracionTempNormalTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ConfiguracionTempNormalTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ConfiguracionTempNormalTitle, "TEMP. NORMAL");
    lv_obj_set_style_text_color(ui_ConfiguracionTempNormalTitle, lv_color_hex(0x2E628F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ConfiguracionTempNormalTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ConfiguracionTempNormalTitle, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConfiguracionTempNormalOpciones = lv_dropdown_create(ui_ConfiguracionTempNormal);
    lv_obj_set_width(ui_ConfiguracionTempNormalOpciones, lv_pct(100));
    lv_obj_set_height(ui_ConfiguracionTempNormalOpciones, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ConfiguracionTempNormalOpciones, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ConfiguracionTempNormalOpciones, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_ConfiguracionTempNormalOpciones, lv_color_hex(0x2E628F),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ConfiguracionTempNormalOpciones, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ConfiguracionTempNormalOpciones, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ConfiguracionTempNormalOpciones, lv_color_hex(0x2E628F),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ConfiguracionTempNormalOpciones, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ConfiguracionTempNormalOpciones, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ConfiguracionTempNormalOpciones, LV_BORDER_SIDE_BOTTOM,
                                 LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ConfiguracionTempNormalOpciones, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ConfiguracionTempNormalOpciones, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ConfiguracionTempNormalOpciones, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ConfiguracionTempNormalOpciones, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_ConfiguracionTempNormalOpciones, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ConfiguracionTempNormalOpciones, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConfiguracionTempCritica = lv_obj_create(ui_ConfiguracionesMain);
    lv_obj_set_width(ui_ConfiguracionTempCritica, 102);
    lv_obj_set_height(ui_ConfiguracionTempCritica, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_ConfiguracionTempCritica, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ConfiguracionTempCritica, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_ConfiguracionTempCritica, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_ConfiguracionTempCritica, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ConfiguracionTempCritica, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ConfiguracionTempCritica, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ConfiguracionTempCritica, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ConfiguracionTempCritica, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ConfiguracionTempCritica, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ConfiguracionTempCritica, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ConfiguracionTempCritica, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ConfiguracionTempCritica, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ConfiguracionTempCritica, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_ConfiguracionTempCritica, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ConfiguracionTempCritica, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConfiguracionTempCriticaTitle = lv_label_create(ui_ConfiguracionTempCritica);
    lv_obj_set_width(ui_ConfiguracionTempCriticaTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ConfiguracionTempCriticaTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ConfiguracionTempCriticaTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ConfiguracionTempCriticaTitle, "TEMP. CRITICA");
    lv_obj_set_style_text_color(ui_ConfiguracionTempCriticaTitle, lv_color_hex(0x2E628F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ConfiguracionTempCriticaTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ConfiguracionTempCriticaTitle, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConfiguracionTempCriticaOpciones = lv_dropdown_create(ui_ConfiguracionTempCritica);
    lv_obj_set_width(ui_ConfiguracionTempCriticaOpciones, lv_pct(100));
    lv_obj_set_height(ui_ConfiguracionTempCriticaOpciones, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ConfiguracionTempCriticaOpciones, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ConfiguracionTempCriticaOpciones, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_ConfiguracionTempCriticaOpciones, lv_color_hex(0x2E628F),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ConfiguracionTempCriticaOpciones, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ConfiguracionTempCriticaOpciones, &lv_font_montserrat_16,
                               LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ConfiguracionTempCriticaOpciones, lv_color_hex(0x2E628F),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ConfiguracionTempCriticaOpciones, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ConfiguracionTempCriticaOpciones, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ConfiguracionTempCriticaOpciones, LV_BORDER_SIDE_BOTTOM,
                                 LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ConfiguracionTempCriticaOpciones, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ConfiguracionTempCriticaOpciones, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ConfiguracionTempCriticaOpciones, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ConfiguracionTempCriticaOpciones, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_ConfiguracionTempCriticaOpciones, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ConfiguracionTempCriticaOpciones, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConfiguracionTolIntensidad = lv_obj_create(ui_ConfiguracionesMain);
    lv_obj_set_width(ui_ConfiguracionTolIntensidad, 101);
    lv_obj_set_height(ui_ConfiguracionTolIntensidad, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_ConfiguracionTolIntensidad, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ConfiguracionTolIntensidad, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_ConfiguracionTolIntensidad, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_ConfiguracionTolIntensidad, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ConfiguracionTolIntensidad, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ConfiguracionTolIntensidad, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ConfiguracionTolIntensidad, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ConfiguracionTolIntensidad, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ConfiguracionTolIntensidad, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ConfiguracionTolIntensidad, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ConfiguracionTolIntensidad, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ConfiguracionTolIntensidad, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ConfiguracionTolIntensidad, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_ConfiguracionTolIntensidad, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ConfiguracionTolIntensidad, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConfiguracionTolIntensidadTitle = lv_label_create(ui_ConfiguracionTolIntensidad);
    lv_obj_set_width(ui_ConfiguracionTolIntensidadTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ConfiguracionTolIntensidadTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ConfiguracionTolIntensidadTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ConfiguracionTolIntensidadTitle, "TOL. INTENSIDAD");
    lv_obj_set_style_text_color(ui_ConfiguracionTolIntensidadTitle, lv_color_hex(0x2E628F),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ConfiguracionTolIntensidadTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ConfiguracionTolIntensidadTitle, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConfiguracionTolIntensidadOpciones = lv_dropdown_create(ui_ConfiguracionTolIntensidad);
    lv_obj_set_width(ui_ConfiguracionTolIntensidadOpciones, lv_pct(100));
    lv_obj_set_height(ui_ConfiguracionTolIntensidadOpciones, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ConfiguracionTolIntensidadOpciones, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ConfiguracionTolIntensidadOpciones, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_ConfiguracionTolIntensidadOpciones, lv_color_hex(0x2E628F),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ConfiguracionTolIntensidadOpciones, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ConfiguracionTolIntensidadOpciones, &lv_font_montserrat_16,
                               LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ConfiguracionTolIntensidadOpciones, lv_color_hex(0x2E628F),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ConfiguracionTolIntensidadOpciones, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ConfiguracionTolIntensidadOpciones, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ConfiguracionTolIntensidadOpciones, LV_BORDER_SIDE_BOTTOM,
                                 LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ConfiguracionTolIntensidadOpciones, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ConfiguracionTolIntensidadOpciones, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ConfiguracionTolIntensidadOpciones, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ConfiguracionTolIntensidadOpciones, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_ConfiguracionTolIntensidadOpciones, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ConfiguracionTolIntensidadOpciones, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConfiguracionesOptionsButtons = lv_obj_create(ui_ConfiguracionesScreen);
    lv_obj_set_height(ui_ConfiguracionesOptionsButtons, 40);
    lv_obj_set_width(ui_ConfiguracionesOptionsButtons, lv_pct(100));
    lv_obj_set_align(ui_ConfiguracionesOptionsButtons, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ConfiguracionesOptionsButtons, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ConfiguracionesOptionsButtons, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_ConfiguracionesOptionsButtons, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ConfiguracionesOptionsButtons, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ConfiguracionesOptionsButtons, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ConfiguracionesOptionsButtons, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ConfiguracionesOptionsButtons, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ConfiguracionesOptionsButtons, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ConfiguracionesOptionsButtons, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ConfiguracionesOptionsButtons, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ConfiguracionesOptionsButtons, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ConfiguracionesOptionsButtons, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_ConfiguracionesOptionsButtons, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ConfiguracionesOptionsButtons, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonConfiguracionVolver = lv_button_create(ui_ConfiguracionesOptionsButtons);
    lv_obj_set_width(ui_ButtonConfiguracionVolver, lv_pct(50));
    lv_obj_set_height(ui_ButtonConfiguracionVolver, lv_pct(100));
    lv_obj_set_align(ui_ButtonConfiguracionVolver, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonConfiguracionVolver, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonConfiguracionVolver, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonConfiguracionVolver, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonConfiguracionVolver, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonConfiguracionVolver, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ButtonConfiguracionVolver, lv_color_hex(0xB0B3B8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ButtonConfiguracionVolver, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ButtonConfiguracionVolver, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonConfiguracionVolverTexto = lv_label_create(ui_ButtonConfiguracionVolver);
    lv_obj_set_width(ui_ButtonConfiguracionVolverTexto, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ButtonConfiguracionVolverTexto, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ButtonConfiguracionVolverTexto, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ButtonConfiguracionVolverTexto, "VOLVER");
    lv_obj_set_style_text_color(ui_ButtonConfiguracionVolverTexto, lv_color_hex(0x1D1F20), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ButtonConfiguracionVolverTexto, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ButtonConfiguracionVolverTexto, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonConfiguracionGuardar = lv_button_create(ui_ConfiguracionesOptionsButtons);
    lv_obj_set_width(ui_ButtonConfiguracionGuardar, lv_pct(50));
    lv_obj_set_height(ui_ButtonConfiguracionGuardar, lv_pct(100));
    lv_obj_set_align(ui_ButtonConfiguracionGuardar, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonConfiguracionGuardar, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonConfiguracionGuardar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonConfiguracionGuardar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonConfiguracionGuardar, lv_color_hex(0x16639E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonConfiguracionGuardar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ButtonConfiguracionGuardar, lv_color_hex(0x2E628F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ButtonConfiguracionGuardar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ButtonConfiguracionGuardar, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonConfiguracionGuardarTexto = lv_label_create(ui_ButtonConfiguracionGuardar);
    lv_obj_set_width(ui_ButtonConfiguracionGuardarTexto, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ButtonConfiguracionGuardarTexto, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ButtonConfiguracionGuardarTexto, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ButtonConfiguracionGuardarTexto, "GUARDAR");
    lv_obj_set_style_text_font(ui_ButtonConfiguracionGuardarTexto, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_ConfiguracionesScreen_screen_destroy(void)
{
    if(ui_ConfiguracionesScreen) lv_obj_del(ui_ConfiguracionesScreen);

    // NULL screen variables
    ui_ConfiguracionesScreen = NULL;
    ui_ConfiguracionesHeader = NULL;
    ui_ConfiguracionesTitle = NULL;
    ui_ConfiguracionesMain = NULL;
    ui_ConfiguracionModo = NULL;
    ui_ConfiguracionModoTitle = NULL;
    ui_ConfiguracionModoOpciones = NULL;
    ui_ConfiguracionIntensidadCampo = NULL;
    ui_ConfiguracionIntensidadCampoTitle = NULL;
    ui_ConfiguracionIntensidadCampoOpciones = NULL;
    ui_ConfiguracionFrecuencia = NULL;
    ui_ConfiguracionFrecuenciaTitle = NULL;
    ui_ConfiguracionFrecuenciaOpciones = NULL;
    ui_ConfiguracionDuracion = NULL;
    ui_ConfiguracionDuracionTitle = NULL;
    ui_ConfiguracionDuracionOpciones = NULL;
    ui_ConfiguracionTempNormal = NULL;
    ui_ConfiguracionTempNormalTitle = NULL;
    ui_ConfiguracionTempNormalOpciones = NULL;
    ui_ConfiguracionTempCritica = NULL;
    ui_ConfiguracionTempCriticaTitle = NULL;
    ui_ConfiguracionTempCriticaOpciones = NULL;
    ui_ConfiguracionTolIntensidad = NULL;
    ui_ConfiguracionTolIntensidadTitle = NULL;
    ui_ConfiguracionTolIntensidadOpciones = NULL;
    ui_ConfiguracionesOptionsButtons = NULL;
    ui_ButtonConfiguracionVolver = NULL;
    ui_ButtonConfiguracionVolverTexto = NULL;
    ui_ButtonConfiguracionGuardar = NULL;
    ui_ButtonConfiguracionGuardarTexto = NULL;

}
