// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: UiFinalParte1

#ifndef UI_ESPERANDOSCREEN_H
#define UI_ESPERANDOSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_EsperandoScreen
extern void ui_EsperandoScreen_screen_init(void);
extern void ui_EsperandoScreen_screen_destroy(void);
extern lv_obj_t * ui_EsperandoScreen;
extern lv_obj_t * ui_EsperandoContenedor;
extern lv_obj_t * ui_EsperandoSpinner;
extern lv_obj_t * ui_EsperandoMensaje;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

