// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: UiFinalParte1

#include "ui.h"

lv_obj_t * ui_EsperandoScreen = NULL;
lv_obj_t * ui_EsperandoContenedor = NULL;
lv_obj_t * ui_EsperandoSpinner = NULL;
lv_obj_t * ui_EsperandoMensaje = NULL;
// event funtions

// build funtions

void ui_EsperandoScreen_screen_init(void)
{
    ui_EsperandoScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_EsperandoScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_EsperandoScreen, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_EsperandoScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_EsperandoContenedor = lv_obj_create(ui_EsperandoScreen);
    lv_obj_remove_style_all(ui_EsperandoContenedor);
    lv_obj_set_width(ui_EsperandoContenedor, lv_pct(100));
    lv_obj_set_height(ui_EsperandoContenedor, lv_pct(100));
    lv_obj_set_align(ui_EsperandoContenedor, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_EsperandoContenedor, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_EsperandoContenedor, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_EsperandoContenedor, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_EsperandoContenedor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_EsperandoContenedor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_EsperandoContenedor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_EsperandoContenedor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_EsperandoContenedor, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_EsperandoContenedor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_EsperandoSpinner = lv_spinner_create(ui_EsperandoContenedor);
    //lv_spinner_set_anim_params(ui_EsperandoSpinner, 1000, 90);
    lv_obj_set_width(ui_EsperandoSpinner, 50);
    lv_obj_set_height(ui_EsperandoSpinner, 50);
    lv_obj_set_align(ui_EsperandoSpinner, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_EsperandoSpinner, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_arc_width(ui_EsperandoSpinner, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_EsperandoSpinner, lv_color_hex(0x2E628F), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_EsperandoSpinner, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_EsperandoSpinner, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_EsperandoMensaje = lv_label_create(ui_EsperandoContenedor);
    lv_obj_set_width(ui_EsperandoMensaje, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_EsperandoMensaje, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_EsperandoMensaje, LV_ALIGN_CENTER);
    lv_label_set_text(ui_EsperandoMensaje, "Procesando...");
    lv_obj_set_style_text_font(ui_EsperandoMensaje, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_EsperandoScreen_screen_destroy(void)
{
    if(ui_EsperandoScreen) lv_obj_del(ui_EsperandoScreen);

    // NULL screen variables
    ui_EsperandoScreen = NULL;
    ui_EsperandoContenedor = NULL;
    ui_EsperandoSpinner = NULL;
    ui_EsperandoMensaje = NULL;

}
