// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: UiFInalParte2

#ifndef UI_ENCURSOSCREEN_H
#define UI_ENCURSOSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_EnCursoScreen
extern void ui_EnCursoScreen_screen_init(void);
extern void ui_EnCursoScreen_screen_destroy(void);
extern lv_obj_t * ui_EnCursoScreen;
extern lv_obj_t * ui_EnCursoHeader;
extern lv_obj_t * ui_EnCursoHeaderTitle;
extern lv_obj_t * ui_EnCursoHeaderEstado;
extern lv_obj_t * ui_EnCursoHeaderEstadoNormal;
extern lv_obj_t * ui_EnCursoHeaderEstadoAdvertencia;
extern lv_obj_t * ui_EnCursoHeaderEstadoCritico;
extern lv_obj_t * ui_EnCursoMain;
extern lv_obj_t * ui_TabView2;
extern lv_obj_t * ui_TabPageObjetivos;
extern lv_obj_t * ui_EnCursoObjetivosModo;
extern lv_obj_t * ui_EnCursoObjetivosModoTitle;
extern lv_obj_t * ui_EnCursoObjetivosModoValor;
extern lv_obj_t * ui_EnCursoObjetivosIntensidad;
extern lv_obj_t * ui_EnCursoObjetivosIntensidadTitle;
extern lv_obj_t * ui_EnCursoObjetivosIntensidadData;
extern lv_obj_t * ui_EnCursoObjetivosIntensidadValor;
extern lv_obj_t * ui_EnCursoObjetivosIntensidadUnidad;
extern lv_obj_t * ui_EnCursoObjetivosFrecuencia;
extern lv_obj_t * ui_EnCursoObjetivosFrecuenciaTitle;
extern lv_obj_t * ui_EnCursoObjetivosFrecuenciaData;
extern lv_obj_t * ui_EnCursoObjetivosFrecuenciaValor;
extern lv_obj_t * ui_EnCursoObjetivosFrecuenciaUnidad;
extern lv_obj_t * ui_EnCursoObjetivosDuracion;
extern lv_obj_t * ui_EnCursoObjetivosDuracionTitle;
extern lv_obj_t * ui_EnCursoObjetivosDuracionData;
extern lv_obj_t * ui_EnCursoObjetivosDuracionHoras;
extern lv_obj_t * ui_EnCursoObjetivosDuracionHorasValor;
extern lv_obj_t * ui_EnCursoObjetivosDuracionHorasUnidad;
extern lv_obj_t * ui_EnCursoObjetivosDuracionMinutos;
extern lv_obj_t * ui_EnCursoObjetivosDuracionMinutosValor;
extern lv_obj_t * ui_EnCursoObjetivosDuracionMinutosUnidad;
extern lv_obj_t * ui_EnCursoObjetivosTolIntensidad;
extern lv_obj_t * ui_EnCursoObjetivosTolIntensidadTitle;
extern lv_obj_t * ui_EnCursoObjetivosTolIntensidadData;
extern lv_obj_t * ui_EnCursoObjetivosTolIntensidadValor;
extern lv_obj_t * ui_EnCursoObjetivosTolIntensidadUnidad;
extern lv_obj_t * ui_EnCursoObjetivosTempNormal;
extern lv_obj_t * ui_EnCursoObjetivosTempNormalTitle;
extern lv_obj_t * ui_EnCursoObjetivosTempNormalData;
extern lv_obj_t * ui_EnCursoObjetivosTempNormalValor;
extern lv_obj_t * ui_EnCursoObjetivosTempNormalUnidad;
extern lv_obj_t * ui_EnCursoObjetivosTempCritica;
extern lv_obj_t * ui_EnCursoObjetivosTempCriticaTitle;
extern lv_obj_t * ui_EnCursoObjetivosTempCriticaData;
extern lv_obj_t * ui_EnCursoObjetivosTempCriticaValor;
extern lv_obj_t * ui_EnCursoObjetivosTempCriticaUnidad;
extern lv_obj_t * ui_TabPageMediciones;
extern lv_obj_t * ui_EnCursoMedicionesIntensidad;
extern lv_obj_t * ui_EnCursoMedicionesIntensidadTitle;
extern lv_obj_t * ui_EnCursoMedicionesIntensidadAlertas;
extern lv_obj_t * ui_EnCursoMedicionesIntensidadAlertas1;
extern lv_obj_t * ui_EnCursoMedicionesIntensidadAlertas2;
extern lv_obj_t * ui_EnCursoMedicionesIntensidadAlertas3;
extern lv_obj_t * ui_EnCursoMedicionesIntensidadAlertas4;
extern lv_obj_t * ui_EnCursoMedicionesIntensidadData;
extern lv_obj_t * ui_EnCursoMedicionesIntensidadValor;
extern lv_obj_t * ui_EnCursoMedicionesIntensidadUnidad;
extern lv_obj_t * ui_EnCursoMedicionesTemp;
extern lv_obj_t * ui_EnCursoMedicionesTempTitle;
extern lv_obj_t * ui_EnCursoMedicionesTempAlertas;
extern lv_obj_t * ui_EnCursoMedicionesTempAlertas1;
extern lv_obj_t * ui_EnCursoMedicionesTempAlertas2;
extern lv_obj_t * ui_EnCursoMedicionesTempAlertas3;
extern lv_obj_t * ui_EnCursoMedicionesTempAlertas4;
extern lv_obj_t * ui_EnCursoMedicionesTempData;
extern lv_obj_t * ui_EnCursoMedicionesTempValor;
extern lv_obj_t * ui_EnCursoMedicionesTempUnidad;
extern lv_obj_t * ui_EnCursoMedicionesBobinas;
extern lv_obj_t * ui_EnCursoMedicionesBobinasHeader;
extern lv_obj_t * ui_EnCursoMedicionesBobinasHeaderNombre;
extern lv_obj_t * ui_EnCursoMedicionesBobinasHeaderControlIntensidad;
extern lv_obj_t * ui_EnCursoMedicionesBobinasHeaderCorriente;
extern lv_obj_t * ui_EnCursoMedicionesBobina1;
extern lv_obj_t * ui_EnCursoMedicionesBobina1Nombre;
extern lv_obj_t * ui_EnCursoMedicionesBobina1Control;
extern lv_obj_t * ui_EnCursoMedicionesBobina1ControlBar;
extern lv_obj_t * ui_EnCursoMedicionesBobina1ControlValor;
extern lv_obj_t * ui_EnCursoMedicionesBobina1Corriente;
extern lv_obj_t * ui_EnCursoMedicionesBobina2;
extern lv_obj_t * ui_EnCursoMedicionesBobina2Nombre;
extern lv_obj_t * ui_EnCursoMedicionesBobina2Control;
extern lv_obj_t * ui_EnCursoMedicionesBobina2ControlBar;
extern lv_obj_t * ui_EnCursoMedicionesBobina2ControlValor;
extern lv_obj_t * ui_EnCursoMedicionesBobina2Corriente;
extern lv_obj_t * ui_EnCursoMedicionesBobina3;
extern lv_obj_t * ui_EnCursoMedicionesBobina3Nombre;
extern lv_obj_t * ui_EnCursoMedicionesBobina3Control;
extern lv_obj_t * ui_EnCursoMedicionesBobina3ControlBar;
extern lv_obj_t * ui_EnCursoMedicionesBobina3ControlValor;
extern lv_obj_t * ui_EnCursoMedicionesBobina3Corriente;
extern lv_obj_t * ui_EnCursoMedicionesBobina4;
extern lv_obj_t * ui_EnCursoMedicionesBobina4Nombre;
extern lv_obj_t * ui_EnCursoMedicionesBobina4Control;
extern lv_obj_t * ui_EnCursoMedicionesBobina4ControlBar;
extern lv_obj_t * ui_EnCursoMedicionesBobina4ControlValor;
extern lv_obj_t * ui_EnCursoMedicionesBobina4Corriente;
extern lv_obj_t * ui_EnCursoOptionsButtons;
extern lv_obj_t * ui_EnCursoProgreso;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_EnCursoTranscurrido;
extern lv_obj_t * ui_EnCursoTranscurridoTitle;
extern lv_obj_t * ui_EnCursoTranscurridoHoras;
extern lv_obj_t * ui_EnCursoTranscurridoHorasValor;
extern lv_obj_t * ui_EnCursoTranscurridoHorasUnidad;
extern lv_obj_t * ui_EnCursoTranscurridoMinutos;
extern lv_obj_t * ui_EnCursoTranscurridoMinutosValor;
extern lv_obj_t * ui_EnCursoTranscurridoMinutosUnidad;
extern lv_obj_t * ui_ButtonDetener;
extern lv_obj_t * ui_ButtonDetenerTexto;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

