// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Principal2

#ifndef UI_PRINCIPAL_H
#define UI_PRINCIPAL_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Principal
extern void ui_Principal_screen_init(void);
extern void ui_Principal_screen_destroy(void);
extern lv_obj_t * ui_Principal;
extern lv_obj_t * ui_PrincipalMain;
extern lv_obj_t * ui_PrincipalObjetivo;
extern lv_obj_t * ui_PrincipalObjetivoTitle;
extern lv_obj_t * ui_PrincipalObjetivoCampo;
extern lv_obj_t * ui_PrincipalObjetivoCampoImg;
extern lv_obj_t * ui_PrincipalObjetivoCampoValue;
extern lv_obj_t * ui_PrincipalObjetivoFrecuencia;
extern lv_obj_t * ui_PrincipalObjetivoFrecuenciaImg;
extern lv_obj_t * ui_PrincipalObjetivoFrecuenciaValue;
extern lv_obj_t * ui_PrincipalObjetivoDuracion;
extern lv_obj_t * ui_PrincipalObjetivoDuracionImg;
extern lv_obj_t * ui_PrincipalObjetivoDuracionValue;
extern lv_obj_t * ui_PrincipalRango;
extern lv_obj_t * ui_PrincipalTolCampoTitle;
extern lv_obj_t * ui_PrincipalTolCampo;
extern lv_obj_t * ui_PrincipalTolCampoImg;
extern lv_obj_t * ui_PrincipalTolCampoValue;
extern lv_obj_t * ui_PrincipalRangoTempTitle;
extern lv_obj_t * ui_PrincipalRangoTempNormal;
extern lv_obj_t * ui_PrincipalRangoTempNormalImg;
extern lv_obj_t * ui_PrincipalRangoTempNormalValue;
extern lv_obj_t * ui_PrincipalRangoTempCrit;
extern lv_obj_t * ui_PrincipalRangoTempCritImg;
extern lv_obj_t * ui_PrincipalRangoTempCritValue;
extern lv_obj_t * ui_PrincipalButtons;
extern lv_obj_t * ui_PrincipalBtnConfiguracion;
extern lv_obj_t * ui_PrincipalBtnConfiguracionImg;
extern lv_obj_t * ui_PrincipalBtnIniciar;
extern lv_obj_t * ui_PrincipalBtnIniciarImg;
extern lv_obj_t * ui_PrincipalHead;
extern lv_obj_t * ui_PrincipalHeadImg;
extern lv_obj_t * ui_PrincipalHeadTitle;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

