// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: UiFinalParte1

#ifndef UI_PRINCIPALSCREEN_H
#define UI_PRINCIPALSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_PrincipalScreen
extern void ui_PrincipalScreen_screen_init(void);
extern void ui_PrincipalScreen_screen_destroy(void);
extern lv_obj_t * ui_PrincipalScreen;
extern lv_obj_t * ui_PrincipalHeader;
extern lv_obj_t * ui_PrincipalTitle;
extern lv_obj_t * ui_PrincipalHeaderBarraEstado;
extern lv_obj_t * ui_PrincipalMegaOk;
extern lv_obj_t * ui_PrincipalMegaNo;
extern lv_obj_t * ui_PrincipalSdOk;
extern lv_obj_t * ui_PrincipalSdNo;
extern lv_obj_t * ui_PrincipalWifiOk;
extern lv_obj_t * ui_PrincipalWifiNo;
extern lv_obj_t * ui_PrincipalBrokerOk;
extern lv_obj_t * ui_PrincipalBrokerNo;
extern lv_obj_t * ui_PrincipalMain;
extern lv_obj_t * ui_PrincipalModo;
extern lv_obj_t * ui_PrincipalModoTitle;
extern lv_obj_t * ui_PrincipalModoValor;
extern lv_obj_t * ui_PrincipalIntensidadCampo;
extern lv_obj_t * ui_PrincipalIntensidadCampoTitle;
extern lv_obj_t * ui_PrincipalIntensidadCampoData;
extern lv_obj_t * ui_PrincipalIntensidadCampoValor;
extern lv_obj_t * ui_PrincipalIntensidadCampoUnidad;
extern lv_obj_t * ui_PrincipalFrecuencia;
extern lv_obj_t * ui_PrincipalFrecuenciaTitle;
extern lv_obj_t * ui_PrincipalFrecuenciaData;
extern lv_obj_t * ui_PrincipalFrecuenciaValor;
extern lv_obj_t * ui_PrincipalFrecuenciaUnidad;
extern lv_obj_t * ui_PrincipalDuracion;
extern lv_obj_t * ui_PrincipalDuracionTitle;
extern lv_obj_t * ui_PrincipalDuracionHoras;
extern lv_obj_t * ui_PrincipalDuracionHorasValor;
extern lv_obj_t * ui_PrincipalDuracionHorasTexto;
extern lv_obj_t * ui_PrincipalDuracionMinutos;
extern lv_obj_t * ui_PrincipalDuracionMinutosValor;
extern lv_obj_t * ui_PrincipalDuracionMinutosTexto;
extern lv_obj_t * ui_PrincipalTolIntensidad;
extern lv_obj_t * ui_PrincipalTolIntensidadTitle;
extern lv_obj_t * ui_PrincipalTolIntensidadData;
extern lv_obj_t * ui_PrincipalTolIntensidadValor;
extern lv_obj_t * ui_PrincipalTolIntensidadUnidad;
extern lv_obj_t * ui_PrincipalTempNormal;
extern lv_obj_t * ui_PrincipalTempNormalTitle;
extern lv_obj_t * ui_PrincipalTempNormalData;
extern lv_obj_t * ui_PrincipalTempNormalValor;
extern lv_obj_t * ui_PrincipalTempNormalUnidad;
extern lv_obj_t * ui_PrincipalTempCritica;
extern lv_obj_t * ui_PrincipalTempCriticaTitle;
extern lv_obj_t * ui_PrincipalTempCriticaData;
extern lv_obj_t * ui_PrincipalTempCriticaValor;
extern lv_obj_t * ui_PrincipalTempCriticaUnidad;
extern lv_obj_t * ui_PrincipalOptionsButtons;
extern lv_obj_t * ui_ButtonPrincipalConfigurar;
extern lv_obj_t * ui_ButtonPrincipalConfigurarTexto;
extern lv_obj_t * ui_ButtonPrincipalIniciar;
extern lv_obj_t * ui_ButtonPrincipalIniciarTexto;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

