// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Principal2

#include "ui.h"

lv_obj_t * ui_Principal = NULL;
lv_obj_t * ui_PrincipalMain = NULL;
lv_obj_t * ui_PrincipalObjetivo = NULL;
lv_obj_t * ui_PrincipalObjetivoTitle = NULL;
lv_obj_t * ui_PrincipalObjetivoCampo = NULL;
lv_obj_t * ui_PrincipalObjetivoCampoImg = NULL;
lv_obj_t * ui_PrincipalObjetivoCampoValue = NULL;
lv_obj_t * ui_PrincipalObjetivoFrecuencia = NULL;
lv_obj_t * ui_PrincipalObjetivoFrecuenciaImg = NULL;
lv_obj_t * ui_PrincipalObjetivoFrecuenciaValue = NULL;
lv_obj_t * ui_PrincipalObjetivoDuracion = NULL;
lv_obj_t * ui_PrincipalObjetivoDuracionImg = NULL;
lv_obj_t * ui_PrincipalObjetivoDuracionValue = NULL;
lv_obj_t * ui_PrincipalRango = NULL;
lv_obj_t * ui_PrincipalTolCampoTitle = NULL;
lv_obj_t * ui_PrincipalTolCampo = NULL;
lv_obj_t * ui_PrincipalTolCampoImg = NULL;
lv_obj_t * ui_PrincipalTolCampoValue = NULL;
lv_obj_t * ui_PrincipalRangoTempTitle = NULL;
lv_obj_t * ui_PrincipalRangoTempNormal = NULL;
lv_obj_t * ui_PrincipalRangoTempNormalImg = NULL;
lv_obj_t * ui_PrincipalRangoTempNormalValue = NULL;
lv_obj_t * ui_PrincipalRangoTempCrit = NULL;
lv_obj_t * ui_PrincipalRangoTempCritImg = NULL;
lv_obj_t * ui_PrincipalRangoTempCritValue = NULL;
lv_obj_t * ui_PrincipalButtons = NULL;
lv_obj_t * ui_PrincipalBtnConfiguracion = NULL;
lv_obj_t * ui_PrincipalBtnConfiguracionImg = NULL;
lv_obj_t * ui_PrincipalBtnIniciar = NULL;
lv_obj_t * ui_PrincipalBtnIniciarImg = NULL;
lv_obj_t * ui_PrincipalHead = NULL;
lv_obj_t * ui_PrincipalHeadImg = NULL;
lv_obj_t * ui_PrincipalHeadTitle = NULL;
// event funtions

// build funtions

void ui_Principal_screen_init(void)
{
    ui_Principal = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Principal, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PrincipalMain = lv_obj_create(ui_Principal);
    lv_obj_remove_style_all(ui_PrincipalMain);
    lv_obj_set_width(ui_PrincipalMain, 270);
    lv_obj_set_height(ui_PrincipalMain, 192);
    lv_obj_set_x(ui_PrincipalMain, -25);
    lv_obj_set_y(ui_PrincipalMain, 23);
    lv_obj_set_align(ui_PrincipalMain, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PrincipalMain, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PrincipalMain, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_PrincipalMain, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_PrincipalMain, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PrincipalMain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PrincipalMain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PrincipalMain, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_PrincipalMain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_PrincipalMain, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrincipalObjetivo = lv_obj_create(ui_PrincipalMain);
    lv_obj_set_width(ui_PrincipalObjetivo, 132);
    lv_obj_set_height(ui_PrincipalObjetivo, lv_pct(100));
    lv_obj_set_x(ui_PrincipalObjetivo, -79);
    lv_obj_set_y(ui_PrincipalObjetivo, 20);
    lv_obj_set_align(ui_PrincipalObjetivo, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PrincipalObjetivo, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_PrincipalObjetivo, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_PrincipalObjetivo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PrincipalObjetivoTitle = lv_label_create(ui_PrincipalObjetivo);
    lv_obj_set_width(ui_PrincipalObjetivoTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PrincipalObjetivoTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PrincipalObjetivoTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PrincipalObjetivoTitle, "Objetivos");

    ui_PrincipalObjetivoCampo = lv_obj_create(ui_PrincipalObjetivo);
    lv_obj_remove_style_all(ui_PrincipalObjetivoCampo);
    lv_obj_set_width(ui_PrincipalObjetivoCampo, 100);
    lv_obj_set_height(ui_PrincipalObjetivoCampo, 32);
    lv_obj_set_align(ui_PrincipalObjetivoCampo, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PrincipalObjetivoCampo, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PrincipalObjetivoCampo, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_PrincipalObjetivoCampo, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PrincipalObjetivoCampoImg = lv_image_create(ui_PrincipalObjetivoCampo);
    lv_image_set_src(ui_PrincipalObjetivoCampoImg, &ui_img_campo_png);
    lv_obj_set_width(ui_PrincipalObjetivoCampoImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PrincipalObjetivoCampoImg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PrincipalObjetivoCampoImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PrincipalObjetivoCampoImg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_PrincipalObjetivoCampoImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PrincipalObjetivoCampoValue = lv_label_create(ui_PrincipalObjetivoCampo);
    lv_obj_set_width(ui_PrincipalObjetivoCampoValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PrincipalObjetivoCampoValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PrincipalObjetivoCampoValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PrincipalObjetivoCampoValue, "1.0 mT");

    ui_PrincipalObjetivoFrecuencia = lv_obj_create(ui_PrincipalObjetivo);
    lv_obj_remove_style_all(ui_PrincipalObjetivoFrecuencia);
    lv_obj_set_width(ui_PrincipalObjetivoFrecuencia, 100);
    lv_obj_set_height(ui_PrincipalObjetivoFrecuencia, 32);
    lv_obj_set_align(ui_PrincipalObjetivoFrecuencia, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PrincipalObjetivoFrecuencia, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PrincipalObjetivoFrecuencia, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_PrincipalObjetivoFrecuencia, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PrincipalObjetivoFrecuenciaImg = lv_image_create(ui_PrincipalObjetivoFrecuencia);
    lv_image_set_src(ui_PrincipalObjetivoFrecuenciaImg, &ui_img_frecuencia_png);
    lv_obj_set_width(ui_PrincipalObjetivoFrecuenciaImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PrincipalObjetivoFrecuenciaImg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PrincipalObjetivoFrecuenciaImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PrincipalObjetivoFrecuenciaImg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_PrincipalObjetivoFrecuenciaImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PrincipalObjetivoFrecuenciaValue = lv_label_create(ui_PrincipalObjetivoFrecuencia);
    lv_obj_set_width(ui_PrincipalObjetivoFrecuenciaValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PrincipalObjetivoFrecuenciaValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PrincipalObjetivoFrecuenciaValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PrincipalObjetivoFrecuenciaValue, "50 Hz");

    ui_PrincipalObjetivoDuracion = lv_obj_create(ui_PrincipalObjetivo);
    lv_obj_remove_style_all(ui_PrincipalObjetivoDuracion);
    lv_obj_set_width(ui_PrincipalObjetivoDuracion, 100);
    lv_obj_set_height(ui_PrincipalObjetivoDuracion, 32);
    lv_obj_set_align(ui_PrincipalObjetivoDuracion, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PrincipalObjetivoDuracion, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PrincipalObjetivoDuracion, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_PrincipalObjetivoDuracion, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PrincipalObjetivoDuracionImg = lv_image_create(ui_PrincipalObjetivoDuracion);
    lv_image_set_src(ui_PrincipalObjetivoDuracionImg, &ui_img_2_png);
    lv_obj_set_width(ui_PrincipalObjetivoDuracionImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PrincipalObjetivoDuracionImg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PrincipalObjetivoDuracionImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PrincipalObjetivoDuracionImg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_PrincipalObjetivoDuracionImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PrincipalObjetivoDuracionValue = lv_label_create(ui_PrincipalObjetivoDuracion);
    lv_obj_set_width(ui_PrincipalObjetivoDuracionValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PrincipalObjetivoDuracionValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PrincipalObjetivoDuracionValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PrincipalObjetivoDuracionValue, "01:00:00");

    ui_PrincipalRango = lv_obj_create(ui_PrincipalMain);
    lv_obj_set_width(ui_PrincipalRango, 132);
    lv_obj_set_height(ui_PrincipalRango, lv_pct(100));
    lv_obj_set_x(ui_PrincipalRango, 78);
    lv_obj_set_y(ui_PrincipalRango, 14);
    lv_obj_set_align(ui_PrincipalRango, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PrincipalRango, LV_FLEX_FLOW_COLUMN_WRAP);
    lv_obj_set_flex_align(ui_PrincipalRango, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_PrincipalRango, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_font(ui_PrincipalRango, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrincipalTolCampoTitle = lv_label_create(ui_PrincipalRango);
    lv_obj_set_width(ui_PrincipalTolCampoTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PrincipalTolCampoTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PrincipalTolCampoTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PrincipalTolCampoTitle, "Tol. campo");

    ui_PrincipalTolCampo = lv_obj_create(ui_PrincipalRango);
    lv_obj_remove_style_all(ui_PrincipalTolCampo);
    lv_obj_set_width(ui_PrincipalTolCampo, 100);
    lv_obj_set_height(ui_PrincipalTolCampo, 32);
    lv_obj_set_align(ui_PrincipalTolCampo, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PrincipalTolCampo, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PrincipalTolCampo, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_PrincipalTolCampo, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PrincipalTolCampoImg = lv_image_create(ui_PrincipalTolCampo);
    lv_image_set_src(ui_PrincipalTolCampoImg, &ui_img_tolcampo_png);
    lv_obj_set_width(ui_PrincipalTolCampoImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PrincipalTolCampoImg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PrincipalTolCampoImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PrincipalTolCampoImg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_PrincipalTolCampoImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PrincipalTolCampoValue = lv_label_create(ui_PrincipalTolCampo);
    lv_obj_set_width(ui_PrincipalTolCampoValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PrincipalTolCampoValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PrincipalTolCampoValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PrincipalTolCampoValue, "5%");

    ui_PrincipalRangoTempTitle = lv_label_create(ui_PrincipalRango);
    lv_obj_set_width(ui_PrincipalRangoTempTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PrincipalRangoTempTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PrincipalRangoTempTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PrincipalRangoTempTitle, "Rango temp.");

    ui_PrincipalRangoTempNormal = lv_obj_create(ui_PrincipalRango);
    lv_obj_remove_style_all(ui_PrincipalRangoTempNormal);
    lv_obj_set_width(ui_PrincipalRangoTempNormal, 100);
    lv_obj_set_height(ui_PrincipalRangoTempNormal, 32);
    lv_obj_set_align(ui_PrincipalRangoTempNormal, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PrincipalRangoTempNormal, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PrincipalRangoTempNormal, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_PrincipalRangoTempNormal, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PrincipalRangoTempNormalImg = lv_image_create(ui_PrincipalRangoTempNormal);
    lv_image_set_src(ui_PrincipalRangoTempNormalImg, &ui_img_temp_normal_png);
    lv_obj_set_width(ui_PrincipalRangoTempNormalImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PrincipalRangoTempNormalImg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PrincipalRangoTempNormalImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PrincipalRangoTempNormalImg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_PrincipalRangoTempNormalImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PrincipalRangoTempNormalValue = lv_label_create(ui_PrincipalRangoTempNormal);
    lv_obj_set_width(ui_PrincipalRangoTempNormalValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PrincipalRangoTempNormalValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PrincipalRangoTempNormalValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PrincipalRangoTempNormalValue, "28 - 30 C");

    ui_PrincipalRangoTempCrit = lv_obj_create(ui_PrincipalRango);
    lv_obj_remove_style_all(ui_PrincipalRangoTempCrit);
    lv_obj_set_width(ui_PrincipalRangoTempCrit, 100);
    lv_obj_set_height(ui_PrincipalRangoTempCrit, 32);
    lv_obj_set_align(ui_PrincipalRangoTempCrit, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PrincipalRangoTempCrit, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PrincipalRangoTempCrit, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_PrincipalRangoTempCrit, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PrincipalRangoTempCritImg = lv_image_create(ui_PrincipalRangoTempCrit);
    lv_image_set_src(ui_PrincipalRangoTempCritImg, &ui_img_temp_critica_png);
    lv_obj_set_width(ui_PrincipalRangoTempCritImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PrincipalRangoTempCritImg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PrincipalRangoTempCritImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PrincipalRangoTempCritImg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_PrincipalRangoTempCritImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PrincipalRangoTempCritValue = lv_label_create(ui_PrincipalRangoTempCrit);
    lv_obj_set_width(ui_PrincipalRangoTempCritValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PrincipalRangoTempCritValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PrincipalRangoTempCritValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PrincipalRangoTempCritValue, "24 - 34 C");

    ui_PrincipalButtons = lv_obj_create(ui_Principal);
    lv_obj_remove_style_all(ui_PrincipalButtons);
    lv_obj_set_width(ui_PrincipalButtons, 40);
    lv_obj_set_height(ui_PrincipalButtons, 192);
    lv_obj_set_x(ui_PrincipalButtons, 135);
    lv_obj_set_y(ui_PrincipalButtons, 23);
    lv_obj_set_align(ui_PrincipalButtons, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PrincipalButtons, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_PrincipalButtons, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_PrincipalButtons, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_PrincipalButtons, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PrincipalButtons, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PrincipalButtons, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PrincipalButtons, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_PrincipalButtons, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_PrincipalButtons, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrincipalBtnConfiguracion = lv_button_create(ui_PrincipalButtons);
    lv_obj_set_height(ui_PrincipalBtnConfiguracion, 50);
    lv_obj_set_width(ui_PrincipalBtnConfiguracion, lv_pct(100));
    lv_obj_set_align(ui_PrincipalBtnConfiguracion, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PrincipalBtnConfiguracion, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PrincipalBtnConfiguracion, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_PrincipalBtnConfiguracion, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_PrincipalBtnConfiguracion, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PrincipalBtnConfiguracion, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PrincipalBtnConfiguracion, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrincipalBtnConfiguracionImg = lv_image_create(ui_PrincipalBtnConfiguracion);
    lv_image_set_src(ui_PrincipalBtnConfiguracionImg, &ui_img_configuracion_png);
    lv_obj_set_width(ui_PrincipalBtnConfiguracionImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PrincipalBtnConfiguracionImg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PrincipalBtnConfiguracionImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PrincipalBtnConfiguracionImg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_PrincipalBtnConfiguracionImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PrincipalBtnIniciar = lv_button_create(ui_PrincipalButtons);
    lv_obj_set_height(ui_PrincipalBtnIniciar, 50);
    lv_obj_set_width(ui_PrincipalBtnIniciar, lv_pct(100));
    lv_obj_set_align(ui_PrincipalBtnIniciar, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PrincipalBtnIniciar, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PrincipalBtnIniciar, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_PrincipalBtnIniciar, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_PrincipalBtnIniciar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PrincipalBtnIniciar, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PrincipalBtnIniciar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrincipalBtnIniciarImg = lv_image_create(ui_PrincipalBtnIniciar);
    lv_image_set_src(ui_PrincipalBtnIniciarImg, &ui_img_iniciar_png);
    lv_obj_set_width(ui_PrincipalBtnIniciarImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PrincipalBtnIniciarImg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PrincipalBtnIniciarImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PrincipalBtnIniciarImg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_PrincipalBtnIniciarImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PrincipalHead = lv_obj_create(ui_Principal);
    lv_obj_remove_style_all(ui_PrincipalHead);
    lv_obj_set_height(ui_PrincipalHead, 40);
    lv_obj_set_width(ui_PrincipalHead, lv_pct(100));
    lv_obj_set_x(ui_PrincipalHead, 0);
    lv_obj_set_y(ui_PrincipalHead, -100);
    lv_obj_set_align(ui_PrincipalHead, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PrincipalHead, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PrincipalHead, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_PrincipalHead, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PrincipalHead, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PrincipalHead, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_PrincipalHead, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_PrincipalHead, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PrincipalHead, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrincipalHeadImg = lv_image_create(ui_PrincipalHead);
    lv_image_set_src(ui_PrincipalHeadImg, &ui_img_monitor_png);
    lv_obj_set_width(ui_PrincipalHeadImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PrincipalHeadImg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PrincipalHeadImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PrincipalHeadImg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_PrincipalHeadImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PrincipalHeadTitle = lv_label_create(ui_PrincipalHead);
    lv_obj_set_width(ui_PrincipalHeadTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PrincipalHeadTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PrincipalHeadTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PrincipalHeadTitle, "Principal");

}

void ui_Principal_screen_destroy(void)
{
    if(ui_Principal) lv_obj_del(ui_Principal);

    // NULL screen variables
    ui_Principal = NULL;
    ui_PrincipalMain = NULL;
    ui_PrincipalObjetivo = NULL;
    ui_PrincipalObjetivoTitle = NULL;
    ui_PrincipalObjetivoCampo = NULL;
    ui_PrincipalObjetivoCampoImg = NULL;
    ui_PrincipalObjetivoCampoValue = NULL;
    ui_PrincipalObjetivoFrecuencia = NULL;
    ui_PrincipalObjetivoFrecuenciaImg = NULL;
    ui_PrincipalObjetivoFrecuenciaValue = NULL;
    ui_PrincipalObjetivoDuracion = NULL;
    ui_PrincipalObjetivoDuracionImg = NULL;
    ui_PrincipalObjetivoDuracionValue = NULL;
    ui_PrincipalRango = NULL;
    ui_PrincipalTolCampoTitle = NULL;
    ui_PrincipalTolCampo = NULL;
    ui_PrincipalTolCampoImg = NULL;
    ui_PrincipalTolCampoValue = NULL;
    ui_PrincipalRangoTempTitle = NULL;
    ui_PrincipalRangoTempNormal = NULL;
    ui_PrincipalRangoTempNormalImg = NULL;
    ui_PrincipalRangoTempNormalValue = NULL;
    ui_PrincipalRangoTempCrit = NULL;
    ui_PrincipalRangoTempCritImg = NULL;
    ui_PrincipalRangoTempCritValue = NULL;
    ui_PrincipalButtons = NULL;
    ui_PrincipalBtnConfiguracion = NULL;
    ui_PrincipalBtnConfiguracionImg = NULL;
    ui_PrincipalBtnIniciar = NULL;
    ui_PrincipalBtnIniciarImg = NULL;
    ui_PrincipalHead = NULL;
    ui_PrincipalHeadImg = NULL;
    ui_PrincipalHeadTitle = NULL;

}
