// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: UiFinalParte1

#include "ui.h"

lv_obj_t * ui_PrincipalScreen = NULL;
lv_obj_t * ui_PrincipalHeader = NULL;
lv_obj_t * ui_PrincipalTitle = NULL;
lv_obj_t * ui_PrincipalHeaderBarraEstado = NULL;
lv_obj_t * ui_PrincipalMegaOk = NULL;
lv_obj_t * ui_PrincipalMegaNo = NULL;
lv_obj_t * ui_PrincipalSdOk = NULL;
lv_obj_t * ui_PrincipalSdNo = NULL;
lv_obj_t * ui_PrincipalWifiOk = NULL;
lv_obj_t * ui_PrincipalWifiNo = NULL;
lv_obj_t * ui_PrincipalBrokerOk = NULL;
lv_obj_t * ui_PrincipalBrokerNo = NULL;
lv_obj_t * ui_PrincipalMain = NULL;
lv_obj_t * ui_PrincipalModo = NULL;
lv_obj_t * ui_PrincipalModoTitle = NULL;
lv_obj_t * ui_PrincipalModoValor = NULL;
lv_obj_t * ui_PrincipalIntensidadCampo = NULL;
lv_obj_t * ui_PrincipalIntensidadCampoTitle = NULL;
lv_obj_t * ui_PrincipalIntensidadCampoData = NULL;
lv_obj_t * ui_PrincipalIntensidadCampoValor = NULL;
lv_obj_t * ui_PrincipalIntensidadCampoUnidad = NULL;
lv_obj_t * ui_PrincipalFrecuencia = NULL;
lv_obj_t * ui_PrincipalFrecuenciaTitle = NULL;
lv_obj_t * ui_PrincipalFrecuenciaData = NULL;
lv_obj_t * ui_PrincipalFrecuenciaValor = NULL;
lv_obj_t * ui_PrincipalFrecuenciaUnidad = NULL;
lv_obj_t * ui_PrincipalDuracion = NULL;
lv_obj_t * ui_PrincipalDuracionTitle = NULL;
lv_obj_t * ui_PrincipalDuracionHoras = NULL;
lv_obj_t * ui_PrincipalDuracionHorasValor = NULL;
lv_obj_t * ui_PrincipalDuracionHorasTexto = NULL;
lv_obj_t * ui_PrincipalDuracionMinutos = NULL;
lv_obj_t * ui_PrincipalDuracionMinutosValor = NULL;
lv_obj_t * ui_PrincipalDuracionMinutosTexto = NULL;
lv_obj_t * ui_PrincipalTolIntensidad = NULL;
lv_obj_t * ui_PrincipalTolIntensidadTitle = NULL;
lv_obj_t * ui_PrincipalTolIntensidadData = NULL;
lv_obj_t * ui_PrincipalTolIntensidadValor = NULL;
lv_obj_t * ui_PrincipalTolIntensidadUnidad = NULL;
lv_obj_t * ui_PrincipalTempNormal = NULL;
lv_obj_t * ui_PrincipalTempNormalTitle = NULL;
lv_obj_t * ui_PrincipalTempNormalData = NULL;
lv_obj_t * ui_PrincipalTempNormalValor = NULL;
lv_obj_t * ui_PrincipalTempNormalUnidad = NULL;
lv_obj_t * ui_PrincipalTempCritica = NULL;
lv_obj_t * ui_PrincipalTempCriticaTitle = NULL;
lv_obj_t * ui_PrincipalTempCriticaData = NULL;
lv_obj_t * ui_PrincipalTempCriticaValor = NULL;
lv_obj_t * ui_PrincipalTempCriticaUnidad = NULL;
lv_obj_t * ui_PrincipalOptionsButtons = NULL;
lv_obj_t * ui_ButtonPrincipalConfigurar = NULL;
lv_obj_t * ui_ButtonPrincipalConfigurarTexto = NULL;
lv_obj_t * ui_ButtonPrincipalIniciar = NULL;
lv_obj_t * ui_ButtonPrincipalIniciarTexto = NULL;
// event funtions

// build funtions

void ui_PrincipalScreen_screen_init(void)
{
    ui_PrincipalScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_PrincipalScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_PrincipalScreen, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_PrincipalScreen, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_style_bg_color(ui_PrincipalScreen, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PrincipalScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PrincipalScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PrincipalScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PrincipalScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PrincipalScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_PrincipalScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_PrincipalScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrincipalHeader = lv_obj_create(ui_PrincipalScreen);
    lv_obj_set_height(ui_PrincipalHeader, 40);
    lv_obj_set_width(ui_PrincipalHeader, lv_pct(100));
    lv_obj_set_align(ui_PrincipalHeader, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PrincipalHeader, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PrincipalHeader, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_PrincipalHeader, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PrincipalHeader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PrincipalHeader, lv_color_hex(0x0A3358), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PrincipalHeader, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PrincipalHeader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PrincipalHeader, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PrincipalHeader, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PrincipalHeader, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PrincipalHeader, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_PrincipalHeader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_PrincipalHeader, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrincipalTitle = lv_label_create(ui_PrincipalHeader);
    lv_obj_set_width(ui_PrincipalTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PrincipalTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PrincipalTitle, 0);
    lv_obj_set_y(ui_PrincipalTitle, 1);
    lv_obj_set_align(ui_PrincipalTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PrincipalTitle, "PRINCIPAL");
    lv_obj_set_style_text_color(ui_PrincipalTitle, lv_color_hex(0x7FC0FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PrincipalTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PrincipalTitle, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrincipalHeaderBarraEstado = lv_obj_create(ui_PrincipalHeader);
    lv_obj_remove_style_all(ui_PrincipalHeaderBarraEstado);
    lv_obj_set_width(ui_PrincipalHeaderBarraEstado, 201);
    lv_obj_set_height(ui_PrincipalHeaderBarraEstado, lv_pct(100));
    lv_obj_set_align(ui_PrincipalHeaderBarraEstado, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PrincipalHeaderBarraEstado, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PrincipalHeaderBarraEstado, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_PrincipalHeaderBarraEstado, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_PrincipalHeaderBarraEstado, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PrincipalHeaderBarraEstado, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PrincipalHeaderBarraEstado, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PrincipalHeaderBarraEstado, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_PrincipalHeaderBarraEstado, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_PrincipalHeaderBarraEstado, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrincipalMegaOk = lv_image_create(ui_PrincipalHeaderBarraEstado);
    lv_image_set_src(ui_PrincipalMegaOk, &ui_img_link_activo_png);
    lv_obj_set_width(ui_PrincipalMegaOk, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PrincipalMegaOk, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PrincipalMegaOk, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PrincipalMegaOk, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_PrincipalMegaOk, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PrincipalMegaNo = lv_image_create(ui_PrincipalHeaderBarraEstado);
    lv_image_set_src(ui_PrincipalMegaNo, &ui_img_link_fallo_png);
    lv_obj_set_width(ui_PrincipalMegaNo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PrincipalMegaNo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PrincipalMegaNo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PrincipalMegaNo, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_PrincipalMegaNo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PrincipalSdOk = lv_image_create(ui_PrincipalHeaderBarraEstado);
    lv_image_set_src(ui_PrincipalSdOk, &ui_img_sd_activo_png);
    lv_obj_set_width(ui_PrincipalSdOk, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PrincipalSdOk, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PrincipalSdOk, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PrincipalSdOk, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_PrincipalSdOk, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PrincipalSdNo = lv_image_create(ui_PrincipalHeaderBarraEstado);
    lv_image_set_src(ui_PrincipalSdNo, &ui_img_sd_fallo_png);
    lv_obj_set_width(ui_PrincipalSdNo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PrincipalSdNo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PrincipalSdNo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PrincipalSdNo, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_PrincipalSdNo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PrincipalWifiOk = lv_image_create(ui_PrincipalHeaderBarraEstado);
    lv_image_set_src(ui_PrincipalWifiOk, &ui_img_wifi_activo_png);
    lv_obj_set_width(ui_PrincipalWifiOk, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PrincipalWifiOk, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PrincipalWifiOk, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PrincipalWifiOk, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_PrincipalWifiOk, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PrincipalWifiNo = lv_image_create(ui_PrincipalHeaderBarraEstado);
    lv_image_set_src(ui_PrincipalWifiNo, &ui_img_wifi_fallo_png);
    lv_obj_set_width(ui_PrincipalWifiNo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PrincipalWifiNo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PrincipalWifiNo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PrincipalWifiNo, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_PrincipalWifiNo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PrincipalBrokerOk = lv_image_create(ui_PrincipalHeaderBarraEstado);
    lv_image_set_src(ui_PrincipalBrokerOk, &ui_img_telemetry_activo_png);
    lv_obj_set_width(ui_PrincipalBrokerOk, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PrincipalBrokerOk, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PrincipalBrokerOk, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PrincipalBrokerOk, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_PrincipalBrokerOk, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PrincipalBrokerNo = lv_image_create(ui_PrincipalHeaderBarraEstado);
    lv_image_set_src(ui_PrincipalBrokerNo, &ui_img_telemetry_fallo_png);
    lv_obj_set_width(ui_PrincipalBrokerNo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PrincipalBrokerNo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PrincipalBrokerNo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PrincipalBrokerNo, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_PrincipalBrokerNo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PrincipalMain = lv_obj_create(ui_PrincipalScreen);
    lv_obj_set_height(ui_PrincipalMain, 160);
    lv_obj_set_width(ui_PrincipalMain, lv_pct(100));
    lv_obj_set_x(ui_PrincipalMain, 1);
    lv_obj_set_y(ui_PrincipalMain, 0);
    lv_obj_set_align(ui_PrincipalMain, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PrincipalMain, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_PrincipalMain, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_PrincipalMain, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PrincipalMain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PrincipalMain, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PrincipalMain, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PrincipalMain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_PrincipalMain, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PrincipalMain, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PrincipalMain, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PrincipalMain, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PrincipalMain, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_PrincipalMain, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_PrincipalMain, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrincipalModo = lv_obj_create(ui_PrincipalMain);
    lv_obj_set_width(ui_PrincipalModo, lv_pct(100));
    lv_obj_set_height(ui_PrincipalModo, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_PrincipalModo, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PrincipalModo, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PrincipalModo, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_END);
    lv_obj_remove_flag(ui_PrincipalModo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PrincipalModo, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PrincipalModo, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PrincipalModo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PrincipalModo, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_PrincipalModo, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PrincipalModo, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PrincipalModo, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PrincipalModo, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PrincipalModo, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_PrincipalModo, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_PrincipalModo, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrincipalModoTitle = lv_label_create(ui_PrincipalModo);
    lv_obj_set_width(ui_PrincipalModoTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PrincipalModoTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PrincipalModoTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PrincipalModoTitle, "MODO");
    lv_obj_set_style_text_color(ui_PrincipalModoTitle, lv_color_hex(0x2E628F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PrincipalModoTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PrincipalModoTitle, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrincipalModoValor = lv_label_create(ui_PrincipalModo);
    lv_obj_set_width(ui_PrincipalModoValor, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PrincipalModoValor, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PrincipalModoValor, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PrincipalModoValor, "NORMAL");
    lv_obj_set_style_text_color(ui_PrincipalModoValor, lv_color_hex(0x2E628F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PrincipalModoValor, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PrincipalModoValor, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrincipalIntensidadCampo = lv_obj_create(ui_PrincipalMain);
    lv_obj_set_width(ui_PrincipalIntensidadCampo, 101);
    lv_obj_set_height(ui_PrincipalIntensidadCampo, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_PrincipalIntensidadCampo, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PrincipalIntensidadCampo, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_PrincipalIntensidadCampo, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_PrincipalIntensidadCampo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PrincipalIntensidadCampo, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PrincipalIntensidadCampo, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PrincipalIntensidadCampo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PrincipalIntensidadCampo, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_PrincipalIntensidadCampo, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PrincipalIntensidadCampo, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PrincipalIntensidadCampo, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PrincipalIntensidadCampo, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PrincipalIntensidadCampo, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_PrincipalIntensidadCampo, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_PrincipalIntensidadCampo, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrincipalIntensidadCampoTitle = lv_label_create(ui_PrincipalIntensidadCampo);
    lv_obj_set_width(ui_PrincipalIntensidadCampoTitle, lv_pct(100));
    lv_obj_set_height(ui_PrincipalIntensidadCampoTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PrincipalIntensidadCampoTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PrincipalIntensidadCampoTitle, "INTENSIDAD");
    lv_obj_set_style_text_color(ui_PrincipalIntensidadCampoTitle, lv_color_hex(0x2E628F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PrincipalIntensidadCampoTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PrincipalIntensidadCampoTitle, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrincipalIntensidadCampoData = lv_obj_create(ui_PrincipalIntensidadCampo);
    lv_obj_remove_style_all(ui_PrincipalIntensidadCampoData);
    lv_obj_set_width(ui_PrincipalIntensidadCampoData, 100);
    lv_obj_set_height(ui_PrincipalIntensidadCampoData, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_PrincipalIntensidadCampoData, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PrincipalIntensidadCampoData, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PrincipalIntensidadCampoData, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_PrincipalIntensidadCampoData, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_PrincipalIntensidadCampoData, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PrincipalIntensidadCampoData, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PrincipalIntensidadCampoData, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PrincipalIntensidadCampoData, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_PrincipalIntensidadCampoData, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_PrincipalIntensidadCampoData, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrincipalIntensidadCampoValor = lv_label_create(ui_PrincipalIntensidadCampoData);
    lv_obj_set_width(ui_PrincipalIntensidadCampoValor, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PrincipalIntensidadCampoValor, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PrincipalIntensidadCampoValor, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PrincipalIntensidadCampoValor, "1.0");
    lv_obj_set_style_text_color(ui_PrincipalIntensidadCampoValor, lv_color_hex(0x2E628F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PrincipalIntensidadCampoValor, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PrincipalIntensidadCampoValor, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrincipalIntensidadCampoUnidad = lv_label_create(ui_PrincipalIntensidadCampoData);
    lv_obj_set_width(ui_PrincipalIntensidadCampoUnidad, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PrincipalIntensidadCampoUnidad, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PrincipalIntensidadCampoUnidad, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PrincipalIntensidadCampoUnidad, "mT");
    lv_obj_set_style_text_color(ui_PrincipalIntensidadCampoUnidad, lv_color_hex(0x2E628F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PrincipalIntensidadCampoUnidad, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PrincipalIntensidadCampoUnidad, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrincipalFrecuencia = lv_obj_create(ui_PrincipalMain);
    lv_obj_set_width(ui_PrincipalFrecuencia, 102);
    lv_obj_set_height(ui_PrincipalFrecuencia, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_PrincipalFrecuencia, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PrincipalFrecuencia, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_PrincipalFrecuencia, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_PrincipalFrecuencia, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PrincipalFrecuencia, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PrincipalFrecuencia, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PrincipalFrecuencia, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PrincipalFrecuencia, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_PrincipalFrecuencia, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PrincipalFrecuencia, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PrincipalFrecuencia, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PrincipalFrecuencia, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PrincipalFrecuencia, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_PrincipalFrecuencia, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_PrincipalFrecuencia, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrincipalFrecuenciaTitle = lv_label_create(ui_PrincipalFrecuencia);
    lv_obj_set_width(ui_PrincipalFrecuenciaTitle, lv_pct(100));
    lv_obj_set_height(ui_PrincipalFrecuenciaTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PrincipalFrecuenciaTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PrincipalFrecuenciaTitle, "FRECUENCIA");
    lv_obj_set_style_text_color(ui_PrincipalFrecuenciaTitle, lv_color_hex(0x2E628F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PrincipalFrecuenciaTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PrincipalFrecuenciaTitle, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrincipalFrecuenciaData = lv_obj_create(ui_PrincipalFrecuencia);
    lv_obj_remove_style_all(ui_PrincipalFrecuenciaData);
    lv_obj_set_width(ui_PrincipalFrecuenciaData, 100);
    lv_obj_set_height(ui_PrincipalFrecuenciaData, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_PrincipalFrecuenciaData, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PrincipalFrecuenciaData, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PrincipalFrecuenciaData, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_PrincipalFrecuenciaData, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_PrincipalFrecuenciaData, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PrincipalFrecuenciaData, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PrincipalFrecuenciaData, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PrincipalFrecuenciaData, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_PrincipalFrecuenciaData, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_PrincipalFrecuenciaData, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrincipalFrecuenciaValor = lv_label_create(ui_PrincipalFrecuenciaData);
    lv_obj_set_width(ui_PrincipalFrecuenciaValor, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PrincipalFrecuenciaValor, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PrincipalFrecuenciaValor, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PrincipalFrecuenciaValor, "50");
    lv_obj_set_style_text_color(ui_PrincipalFrecuenciaValor, lv_color_hex(0x2E628F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PrincipalFrecuenciaValor, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PrincipalFrecuenciaValor, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrincipalFrecuenciaUnidad = lv_label_create(ui_PrincipalFrecuenciaData);
    lv_obj_set_width(ui_PrincipalFrecuenciaUnidad, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PrincipalFrecuenciaUnidad, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PrincipalFrecuenciaUnidad, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PrincipalFrecuenciaUnidad, "Hz");
    lv_obj_set_style_text_color(ui_PrincipalFrecuenciaUnidad, lv_color_hex(0x2E628F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PrincipalFrecuenciaUnidad, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PrincipalFrecuenciaUnidad, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrincipalDuracion = lv_obj_create(ui_PrincipalMain);
    lv_obj_set_width(ui_PrincipalDuracion, 101);
    lv_obj_set_height(ui_PrincipalDuracion, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_PrincipalDuracion, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PrincipalDuracion, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_PrincipalDuracion, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_PrincipalDuracion, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PrincipalDuracion, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PrincipalDuracion, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PrincipalDuracion, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PrincipalDuracion, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_PrincipalDuracion, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PrincipalDuracion, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PrincipalDuracion, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PrincipalDuracion, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PrincipalDuracion, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_PrincipalDuracion, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_PrincipalDuracion, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrincipalDuracionTitle = lv_label_create(ui_PrincipalDuracion);
    lv_obj_set_width(ui_PrincipalDuracionTitle, lv_pct(100));
    lv_obj_set_height(ui_PrincipalDuracionTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PrincipalDuracionTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PrincipalDuracionTitle, "DURACION");
    lv_obj_set_style_text_color(ui_PrincipalDuracionTitle, lv_color_hex(0x2E628F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PrincipalDuracionTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PrincipalDuracionTitle, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrincipalDuracionHoras = lv_obj_create(ui_PrincipalDuracion);
    lv_obj_remove_style_all(ui_PrincipalDuracionHoras);
    lv_obj_set_width(ui_PrincipalDuracionHoras, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_PrincipalDuracionHoras, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_PrincipalDuracionHoras, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PrincipalDuracionHoras, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PrincipalDuracionHoras, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_PrincipalDuracionHoras, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_PrincipalDuracionHoras, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PrincipalDuracionHoras, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PrincipalDuracionHoras, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PrincipalDuracionHoras, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_PrincipalDuracionHoras, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_PrincipalDuracionHoras, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrincipalDuracionHorasValor = lv_label_create(ui_PrincipalDuracionHoras);
    lv_obj_set_width(ui_PrincipalDuracionHorasValor, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PrincipalDuracionHorasValor, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PrincipalDuracionHorasValor, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PrincipalDuracionHorasValor, "0");
    lv_obj_set_style_text_color(ui_PrincipalDuracionHorasValor, lv_color_hex(0x2E628F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PrincipalDuracionHorasValor, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PrincipalDuracionHorasValor, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrincipalDuracionHorasTexto = lv_label_create(ui_PrincipalDuracionHoras);
    lv_obj_set_width(ui_PrincipalDuracionHorasTexto, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PrincipalDuracionHorasTexto, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PrincipalDuracionHorasTexto, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PrincipalDuracionHorasTexto, "h");
    lv_obj_set_style_text_color(ui_PrincipalDuracionHorasTexto, lv_color_hex(0x2E628F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PrincipalDuracionHorasTexto, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PrincipalDuracionHorasTexto, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrincipalDuracionMinutos = lv_obj_create(ui_PrincipalDuracion);
    lv_obj_remove_style_all(ui_PrincipalDuracionMinutos);
    lv_obj_set_width(ui_PrincipalDuracionMinutos, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_PrincipalDuracionMinutos, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_PrincipalDuracionMinutos, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PrincipalDuracionMinutos, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PrincipalDuracionMinutos, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_PrincipalDuracionMinutos, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_PrincipalDuracionMinutos, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PrincipalDuracionMinutos, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PrincipalDuracionMinutos, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PrincipalDuracionMinutos, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_PrincipalDuracionMinutos, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_PrincipalDuracionMinutos, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrincipalDuracionMinutosValor = lv_label_create(ui_PrincipalDuracionMinutos);
    lv_obj_set_width(ui_PrincipalDuracionMinutosValor, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PrincipalDuracionMinutosValor, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PrincipalDuracionMinutosValor, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PrincipalDuracionMinutosValor, "00");
    lv_obj_set_style_text_color(ui_PrincipalDuracionMinutosValor, lv_color_hex(0x2E628F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PrincipalDuracionMinutosValor, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PrincipalDuracionMinutosValor, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrincipalDuracionMinutosTexto = lv_label_create(ui_PrincipalDuracionMinutos);
    lv_obj_set_width(ui_PrincipalDuracionMinutosTexto, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PrincipalDuracionMinutosTexto, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PrincipalDuracionMinutosTexto, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PrincipalDuracionMinutosTexto, "m");
    lv_obj_set_style_text_color(ui_PrincipalDuracionMinutosTexto, lv_color_hex(0x2E628F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PrincipalDuracionMinutosTexto, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PrincipalDuracionMinutosTexto, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrincipalTolIntensidad = lv_obj_create(ui_PrincipalMain);
    lv_obj_set_width(ui_PrincipalTolIntensidad, 101);
    lv_obj_set_height(ui_PrincipalTolIntensidad, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_PrincipalTolIntensidad, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PrincipalTolIntensidad, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_PrincipalTolIntensidad, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_PrincipalTolIntensidad, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PrincipalTolIntensidad, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PrincipalTolIntensidad, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PrincipalTolIntensidad, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PrincipalTolIntensidad, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_PrincipalTolIntensidad, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PrincipalTolIntensidad, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PrincipalTolIntensidad, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PrincipalTolIntensidad, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PrincipalTolIntensidad, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_PrincipalTolIntensidad, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_PrincipalTolIntensidad, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrincipalTolIntensidadTitle = lv_label_create(ui_PrincipalTolIntensidad);
    lv_obj_set_width(ui_PrincipalTolIntensidadTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PrincipalTolIntensidadTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PrincipalTolIntensidadTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PrincipalTolIntensidadTitle, "TOL. INTENSIDAD");
    lv_obj_set_style_text_color(ui_PrincipalTolIntensidadTitle, lv_color_hex(0x2E628F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PrincipalTolIntensidadTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PrincipalTolIntensidadTitle, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrincipalTolIntensidadData = lv_obj_create(ui_PrincipalTolIntensidad);
    lv_obj_remove_style_all(ui_PrincipalTolIntensidadData);
    lv_obj_set_width(ui_PrincipalTolIntensidadData, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_PrincipalTolIntensidadData, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_PrincipalTolIntensidadData, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PrincipalTolIntensidadData, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PrincipalTolIntensidadData, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_PrincipalTolIntensidadData, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_PrincipalTolIntensidadData, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PrincipalTolIntensidadData, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PrincipalTolIntensidadData, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PrincipalTolIntensidadData, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_PrincipalTolIntensidadData, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_PrincipalTolIntensidadData, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrincipalTolIntensidadValor = lv_label_create(ui_PrincipalTolIntensidadData);
    lv_obj_set_width(ui_PrincipalTolIntensidadValor, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PrincipalTolIntensidadValor, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PrincipalTolIntensidadValor, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PrincipalTolIntensidadValor, "5");
    lv_obj_set_style_text_color(ui_PrincipalTolIntensidadValor, lv_color_hex(0x2E628F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PrincipalTolIntensidadValor, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PrincipalTolIntensidadValor, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrincipalTolIntensidadUnidad = lv_label_create(ui_PrincipalTolIntensidadData);
    lv_obj_set_width(ui_PrincipalTolIntensidadUnidad, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PrincipalTolIntensidadUnidad, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PrincipalTolIntensidadUnidad, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PrincipalTolIntensidadUnidad, "%");
    lv_obj_set_style_text_color(ui_PrincipalTolIntensidadUnidad, lv_color_hex(0x2E628F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PrincipalTolIntensidadUnidad, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PrincipalTolIntensidadUnidad, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrincipalTempNormal = lv_obj_create(ui_PrincipalMain);
    lv_obj_set_width(ui_PrincipalTempNormal, 101);
    lv_obj_set_height(ui_PrincipalTempNormal, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_PrincipalTempNormal, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PrincipalTempNormal, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_PrincipalTempNormal, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_PrincipalTempNormal, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PrincipalTempNormal, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PrincipalTempNormal, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PrincipalTempNormal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PrincipalTempNormal, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_PrincipalTempNormal, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PrincipalTempNormal, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PrincipalTempNormal, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PrincipalTempNormal, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PrincipalTempNormal, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_PrincipalTempNormal, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_PrincipalTempNormal, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrincipalTempNormalTitle = lv_label_create(ui_PrincipalTempNormal);
    lv_obj_set_width(ui_PrincipalTempNormalTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PrincipalTempNormalTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PrincipalTempNormalTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PrincipalTempNormalTitle, "TEMP. NORMAL");
    lv_obj_set_style_text_color(ui_PrincipalTempNormalTitle, lv_color_hex(0x2E628F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PrincipalTempNormalTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PrincipalTempNormalTitle, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrincipalTempNormalData = lv_obj_create(ui_PrincipalTempNormal);
    lv_obj_remove_style_all(ui_PrincipalTempNormalData);
    lv_obj_set_width(ui_PrincipalTempNormalData, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_PrincipalTempNormalData, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_PrincipalTempNormalData, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PrincipalTempNormalData, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PrincipalTempNormalData, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_PrincipalTempNormalData, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_PrincipalTempNormalData, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PrincipalTempNormalData, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PrincipalTempNormalData, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PrincipalTempNormalData, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_PrincipalTempNormalData, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_PrincipalTempNormalData, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrincipalTempNormalValor = lv_label_create(ui_PrincipalTempNormalData);
    lv_obj_set_width(ui_PrincipalTempNormalValor, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PrincipalTempNormalValor, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PrincipalTempNormalValor, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PrincipalTempNormalValor, "25~35");
    lv_obj_set_style_text_color(ui_PrincipalTempNormalValor, lv_color_hex(0x2E628F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PrincipalTempNormalValor, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PrincipalTempNormalValor, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrincipalTempNormalUnidad = lv_label_create(ui_PrincipalTempNormalData);
    lv_obj_set_width(ui_PrincipalTempNormalUnidad, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PrincipalTempNormalUnidad, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PrincipalTempNormalUnidad, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PrincipalTempNormalUnidad, "C");
    lv_obj_set_style_text_color(ui_PrincipalTempNormalUnidad, lv_color_hex(0x2E628F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PrincipalTempNormalUnidad, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PrincipalTempNormalUnidad, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrincipalTempCritica = lv_obj_create(ui_PrincipalMain);
    lv_obj_set_width(ui_PrincipalTempCritica, 102);
    lv_obj_set_height(ui_PrincipalTempCritica, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_PrincipalTempCritica, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PrincipalTempCritica, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_PrincipalTempCritica, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_PrincipalTempCritica, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PrincipalTempCritica, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PrincipalTempCritica, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PrincipalTempCritica, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PrincipalTempCritica, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_PrincipalTempCritica, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PrincipalTempCritica, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PrincipalTempCritica, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PrincipalTempCritica, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PrincipalTempCritica, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_PrincipalTempCritica, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_PrincipalTempCritica, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrincipalTempCriticaTitle = lv_label_create(ui_PrincipalTempCritica);
    lv_obj_set_width(ui_PrincipalTempCriticaTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PrincipalTempCriticaTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PrincipalTempCriticaTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PrincipalTempCriticaTitle, "TEMP. CRITICA");
    lv_obj_set_style_text_color(ui_PrincipalTempCriticaTitle, lv_color_hex(0x2E628F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PrincipalTempCriticaTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PrincipalTempCriticaTitle, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrincipalTempCriticaData = lv_obj_create(ui_PrincipalTempCritica);
    lv_obj_remove_style_all(ui_PrincipalTempCriticaData);
    lv_obj_set_width(ui_PrincipalTempCriticaData, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_PrincipalTempCriticaData, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_PrincipalTempCriticaData, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PrincipalTempCriticaData, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PrincipalTempCriticaData, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_PrincipalTempCriticaData, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_PrincipalTempCriticaData, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PrincipalTempCriticaData, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PrincipalTempCriticaData, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PrincipalTempCriticaData, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_PrincipalTempCriticaData, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_PrincipalTempCriticaData, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrincipalTempCriticaValor = lv_label_create(ui_PrincipalTempCriticaData);
    lv_obj_set_width(ui_PrincipalTempCriticaValor, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PrincipalTempCriticaValor, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PrincipalTempCriticaValor, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PrincipalTempCriticaValor, "25~35");
    lv_obj_set_style_text_color(ui_PrincipalTempCriticaValor, lv_color_hex(0x2E628F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PrincipalTempCriticaValor, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PrincipalTempCriticaValor, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrincipalTempCriticaUnidad = lv_label_create(ui_PrincipalTempCriticaData);
    lv_obj_set_width(ui_PrincipalTempCriticaUnidad, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PrincipalTempCriticaUnidad, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PrincipalTempCriticaUnidad, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PrincipalTempCriticaUnidad, "C");
    lv_obj_set_style_text_color(ui_PrincipalTempCriticaUnidad, lv_color_hex(0x2E628F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PrincipalTempCriticaUnidad, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PrincipalTempCriticaUnidad, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrincipalOptionsButtons = lv_obj_create(ui_PrincipalScreen);
    lv_obj_set_height(ui_PrincipalOptionsButtons, 40);
    lv_obj_set_width(ui_PrincipalOptionsButtons, lv_pct(100));
    lv_obj_set_align(ui_PrincipalOptionsButtons, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PrincipalOptionsButtons, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PrincipalOptionsButtons, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_PrincipalOptionsButtons, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PrincipalOptionsButtons, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PrincipalOptionsButtons, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PrincipalOptionsButtons, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PrincipalOptionsButtons, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_PrincipalOptionsButtons, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PrincipalOptionsButtons, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PrincipalOptionsButtons, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PrincipalOptionsButtons, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PrincipalOptionsButtons, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_PrincipalOptionsButtons, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_PrincipalOptionsButtons, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonPrincipalConfigurar = lv_button_create(ui_PrincipalOptionsButtons);
    lv_obj_set_width(ui_ButtonPrincipalConfigurar, lv_pct(50));
    lv_obj_set_height(ui_ButtonPrincipalConfigurar, lv_pct(100));
    lv_obj_set_align(ui_ButtonPrincipalConfigurar, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonPrincipalConfigurar, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonPrincipalConfigurar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonPrincipalConfigurar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonPrincipalConfigurar, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonPrincipalConfigurar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ButtonPrincipalConfigurar, lv_color_hex(0xB0B3B8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ButtonPrincipalConfigurar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ButtonPrincipalConfigurar, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonPrincipalConfigurarTexto = lv_label_create(ui_ButtonPrincipalConfigurar);
    lv_obj_set_width(ui_ButtonPrincipalConfigurarTexto, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ButtonPrincipalConfigurarTexto, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ButtonPrincipalConfigurarTexto, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ButtonPrincipalConfigurarTexto, "CONFIGURACION");
    lv_obj_set_style_text_color(ui_ButtonPrincipalConfigurarTexto, lv_color_hex(0x1D1F20), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ButtonPrincipalConfigurarTexto, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ButtonPrincipalConfigurarTexto, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonPrincipalIniciar = lv_button_create(ui_PrincipalOptionsButtons);
    lv_obj_set_width(ui_ButtonPrincipalIniciar, lv_pct(50));
    lv_obj_set_height(ui_ButtonPrincipalIniciar, lv_pct(100));
    lv_obj_set_align(ui_ButtonPrincipalIniciar, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonPrincipalIniciar, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonPrincipalIniciar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonPrincipalIniciar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonPrincipalIniciar, lv_color_hex(0x16639E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonPrincipalIniciar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ButtonPrincipalIniciar, lv_color_hex(0x2E628F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ButtonPrincipalIniciar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ButtonPrincipalIniciar, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonPrincipalIniciarTexto = lv_label_create(ui_ButtonPrincipalIniciar);
    lv_obj_set_width(ui_ButtonPrincipalIniciarTexto, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ButtonPrincipalIniciarTexto, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ButtonPrincipalIniciarTexto, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ButtonPrincipalIniciarTexto, "INICIAR");
    lv_obj_set_style_text_font(ui_ButtonPrincipalIniciarTexto, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_PrincipalScreen_screen_destroy(void)
{
    if(ui_PrincipalScreen) lv_obj_del(ui_PrincipalScreen);

    // NULL screen variables
    ui_PrincipalScreen = NULL;
    ui_PrincipalHeader = NULL;
    ui_PrincipalTitle = NULL;
    ui_PrincipalHeaderBarraEstado = NULL;
    ui_PrincipalMegaOk = NULL;
    ui_PrincipalMegaNo = NULL;
    ui_PrincipalSdOk = NULL;
    ui_PrincipalSdNo = NULL;
    ui_PrincipalWifiOk = NULL;
    ui_PrincipalWifiNo = NULL;
    ui_PrincipalBrokerOk = NULL;
    ui_PrincipalBrokerNo = NULL;
    ui_PrincipalMain = NULL;
    ui_PrincipalModo = NULL;
    ui_PrincipalModoTitle = NULL;
    ui_PrincipalModoValor = NULL;
    ui_PrincipalIntensidadCampo = NULL;
    ui_PrincipalIntensidadCampoTitle = NULL;
    ui_PrincipalIntensidadCampoData = NULL;
    ui_PrincipalIntensidadCampoValor = NULL;
    ui_PrincipalIntensidadCampoUnidad = NULL;
    ui_PrincipalFrecuencia = NULL;
    ui_PrincipalFrecuenciaTitle = NULL;
    ui_PrincipalFrecuenciaData = NULL;
    ui_PrincipalFrecuenciaValor = NULL;
    ui_PrincipalFrecuenciaUnidad = NULL;
    ui_PrincipalDuracion = NULL;
    ui_PrincipalDuracionTitle = NULL;
    ui_PrincipalDuracionHoras = NULL;
    ui_PrincipalDuracionHorasValor = NULL;
    ui_PrincipalDuracionHorasTexto = NULL;
    ui_PrincipalDuracionMinutos = NULL;
    ui_PrincipalDuracionMinutosValor = NULL;
    ui_PrincipalDuracionMinutosTexto = NULL;
    ui_PrincipalTolIntensidad = NULL;
    ui_PrincipalTolIntensidadTitle = NULL;
    ui_PrincipalTolIntensidadData = NULL;
    ui_PrincipalTolIntensidadValor = NULL;
    ui_PrincipalTolIntensidadUnidad = NULL;
    ui_PrincipalTempNormal = NULL;
    ui_PrincipalTempNormalTitle = NULL;
    ui_PrincipalTempNormalData = NULL;
    ui_PrincipalTempNormalValor = NULL;
    ui_PrincipalTempNormalUnidad = NULL;
    ui_PrincipalTempCritica = NULL;
    ui_PrincipalTempCriticaTitle = NULL;
    ui_PrincipalTempCriticaData = NULL;
    ui_PrincipalTempCriticaValor = NULL;
    ui_PrincipalTempCriticaUnidad = NULL;
    ui_PrincipalOptionsButtons = NULL;
    ui_ButtonPrincipalConfigurar = NULL;
    ui_ButtonPrincipalConfigurarTexto = NULL;
    ui_ButtonPrincipalIniciar = NULL;
    ui_ButtonPrincipalIniciarTexto = NULL;

}
