// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Resultado

#include "ui.h"

lv_obj_t * ui_Resultado = NULL;
lv_obj_t * ui_ResultadoHead = NULL;
lv_obj_t * ui_ResultadoHeadImg = NULL;
lv_obj_t * ui_ResultadoTitle = NULL;
lv_obj_t * ui_ResultadoMain = NULL;
lv_obj_t * ui_ResultadoResumen = NULL;
lv_obj_t * ui_ResultadoExitoso = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_ResultadoFalla = NULL;
lv_obj_t * ui_Image2 = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_ResultadoDetenido = NULL;
lv_obj_t * ui_Image3 = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_ResultadoDetalle = NULL;
lv_obj_t * ui_ResultadoDetalleText = NULL;
lv_obj_t * ui_ResultadoButtons = NULL;
lv_obj_t * ui_ResultadoBtnVolver = NULL;
lv_obj_t * ui_ResultadoBtnVolverImg = NULL;
lv_obj_t * ui_ResultadoBtnVolverText = NULL;
// event funtions

// build funtions

void ui_Resultado_screen_init(void)
{
    ui_Resultado = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Resultado, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Resultado, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Resultado, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ResultadoHead = lv_obj_create(ui_Resultado);
    lv_obj_remove_style_all(ui_ResultadoHead);
    lv_obj_set_height(ui_ResultadoHead, 40);
    lv_obj_set_width(ui_ResultadoHead, lv_pct(100));
    lv_obj_set_x(ui_ResultadoHead, 0);
    lv_obj_set_y(ui_ResultadoHead, -100);
    lv_obj_set_align(ui_ResultadoHead, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ResultadoHead, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ResultadoHead, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ResultadoHead, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ResultadoHead, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ResultadoHead, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_ResultadoHead, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ResultadoHead, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ResultadoHead, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ResultadoHeadImg = lv_image_create(ui_ResultadoHead);
    lv_image_set_src(ui_ResultadoHeadImg, &ui_img_monitor_png);
    lv_obj_set_width(ui_ResultadoHeadImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ResultadoHeadImg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ResultadoHeadImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ResultadoHeadImg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_ResultadoHeadImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ResultadoTitle = lv_label_create(ui_ResultadoHead);
    lv_obj_set_width(ui_ResultadoTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ResultadoTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ResultadoTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ResultadoTitle, "Resultado");

    ui_ResultadoMain = lv_obj_create(ui_Resultado);
    lv_obj_remove_style_all(ui_ResultadoMain);
    lv_obj_set_height(ui_ResultadoMain, 92);
    lv_obj_set_width(ui_ResultadoMain, lv_pct(100));
    lv_obj_set_align(ui_ResultadoMain, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ResultadoMain, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_ResultadoMain, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_ResultadoMain, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ResultadoResumen = lv_obj_create(ui_ResultadoMain);
    lv_obj_remove_style_all(ui_ResultadoResumen);
    lv_obj_set_height(ui_ResultadoResumen, 55);
    lv_obj_set_width(ui_ResultadoResumen, lv_pct(100));
    lv_obj_set_x(ui_ResultadoResumen, 29);
    lv_obj_set_y(ui_ResultadoResumen, 45);
    lv_obj_set_align(ui_ResultadoResumen, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ResultadoResumen, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_ResultadoResumen, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ResultadoResumen, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_font(ui_ResultadoResumen, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ResultadoExitoso = lv_obj_create(ui_ResultadoResumen);
    lv_obj_remove_style_all(ui_ResultadoExitoso);
    lv_obj_set_width(ui_ResultadoExitoso, 220);
    lv_obj_set_height(ui_ResultadoExitoso, 32);
    lv_obj_set_x(ui_ResultadoExitoso, -2);
    lv_obj_set_y(ui_ResultadoExitoso, 56);
    lv_obj_set_align(ui_ResultadoExitoso, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ResultadoExitoso, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ResultadoExitoso, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ResultadoExitoso, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_ResultadoExitoso, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ResultadoExitoso, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_image_create(ui_ResultadoExitoso);
    lv_image_set_src(ui_Image1, &ui_img_estadook_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label6 = lv_label_create(ui_ResultadoExitoso);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "Completado exitosamente");

    ui_ResultadoFalla = lv_obj_create(ui_ResultadoResumen);
    lv_obj_remove_style_all(ui_ResultadoFalla);
    lv_obj_set_width(ui_ResultadoFalla, 220);
    lv_obj_set_height(ui_ResultadoFalla, 32);
    lv_obj_set_x(ui_ResultadoFalla, 9);
    lv_obj_set_y(ui_ResultadoFalla, 5);
    lv_obj_set_align(ui_ResultadoFalla, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ResultadoFalla, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ResultadoFalla, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ResultadoFalla, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_ResultadoFalla, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ResultadoFalla, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_image_create(ui_ResultadoFalla);
    lv_image_set_src(ui_Image2, &ui_img_alertacritica_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label7 = lv_label_create(ui_ResultadoFalla);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "Interrumpido por falla");

    ui_ResultadoDetenido = lv_obj_create(ui_ResultadoResumen);
    lv_obj_remove_style_all(ui_ResultadoDetenido);
    lv_obj_set_width(ui_ResultadoDetenido, 220);
    lv_obj_set_height(ui_ResultadoDetenido, 32);
    lv_obj_set_x(ui_ResultadoDetenido, 0);
    lv_obj_set_y(ui_ResultadoDetenido, 28);
    lv_obj_set_align(ui_ResultadoDetenido, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ResultadoDetenido, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ResultadoDetenido, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ResultadoDetenido, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_ResultadoDetenido, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ResultadoDetenido, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image3 = lv_image_create(ui_ResultadoDetenido);
    lv_image_set_src(ui_Image3, &ui_img_7_png);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label5 = lv_label_create(ui_ResultadoDetenido);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "Detenido por el usuario");

    ui_ResultadoDetalle = lv_obj_create(ui_ResultadoMain);
    lv_obj_remove_style_all(ui_ResultadoDetalle);
    lv_obj_set_height(ui_ResultadoDetalle, 50);
    lv_obj_set_width(ui_ResultadoDetalle, lv_pct(100));
    lv_obj_set_align(ui_ResultadoDetalle, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ResultadoDetalle, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ResultadoDetalle, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ResultadoDetalle, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_font(ui_ResultadoDetalle, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ResultadoDetalleText = lv_label_create(ui_ResultadoDetalle);
    lv_obj_set_width(ui_ResultadoDetalleText, 220);
    lv_obj_set_height(ui_ResultadoDetalleText, lv_pct(100));
    lv_obj_set_align(ui_ResultadoDetalleText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ResultadoDetalleText, "Motivo o detalle");

    ui_ResultadoButtons = lv_obj_create(ui_Resultado);
    lv_obj_remove_style_all(ui_ResultadoButtons);
    lv_obj_set_height(ui_ResultadoButtons, 40);
    lv_obj_set_width(ui_ResultadoButtons, lv_pct(100));
    lv_obj_set_x(ui_ResultadoButtons, 0);
    lv_obj_set_y(ui_ResultadoButtons, 100);
    lv_obj_set_align(ui_ResultadoButtons, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ResultadoButtons, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ResultadoButtons, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ResultadoButtons, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ResultadoBtnVolver = lv_button_create(ui_ResultadoButtons);
    lv_obj_set_width(ui_ResultadoBtnVolver, 258);
    lv_obj_set_height(ui_ResultadoBtnVolver, 35);
    lv_obj_set_x(ui_ResultadoBtnVolver, -24);
    lv_obj_set_y(ui_ResultadoBtnVolver, 56);
    lv_obj_set_align(ui_ResultadoBtnVolver, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ResultadoBtnVolver, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ResultadoBtnVolver, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_ResultadoBtnVolver, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ResultadoBtnVolver, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ResultadoBtnVolver, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ResultadoBtnVolver, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ResultadoBtnVolver, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ResultadoBtnVolverImg = lv_image_create(ui_ResultadoBtnVolver);
    lv_image_set_src(ui_ResultadoBtnVolverImg, &ui_img_volver_png);
    lv_obj_set_width(ui_ResultadoBtnVolverImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ResultadoBtnVolverImg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ResultadoBtnVolverImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ResultadoBtnVolverImg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_ResultadoBtnVolverImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ResultadoBtnVolverText = lv_label_create(ui_ResultadoBtnVolver);
    lv_obj_set_width(ui_ResultadoBtnVolverText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ResultadoBtnVolverText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ResultadoBtnVolverText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ResultadoBtnVolverText, "Volver a menu principal");
    lv_obj_set_style_text_color(ui_ResultadoBtnVolverText, lv_color_hex(0x2081EE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ResultadoBtnVolverText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Resultado_screen_destroy(void)
{
    if(ui_Resultado) lv_obj_del(ui_Resultado);

    // NULL screen variables
    ui_Resultado = NULL;
    ui_ResultadoHead = NULL;
    ui_ResultadoHeadImg = NULL;
    ui_ResultadoTitle = NULL;
    ui_ResultadoMain = NULL;
    ui_ResultadoResumen = NULL;
    ui_ResultadoExitoso = NULL;
    ui_Image1 = NULL;
    ui_Label6 = NULL;
    ui_ResultadoFalla = NULL;
    ui_Image2 = NULL;
    ui_Label7 = NULL;
    ui_ResultadoDetenido = NULL;
    ui_Image3 = NULL;
    ui_Label5 = NULL;
    ui_ResultadoDetalle = NULL;
    ui_ResultadoDetalleText = NULL;
    ui_ResultadoButtons = NULL;
    ui_ResultadoBtnVolver = NULL;
    ui_ResultadoBtnVolverImg = NULL;
    ui_ResultadoBtnVolverText = NULL;

}
