// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Resultado

#ifndef UI_RESULTADO_H
#define UI_RESULTADO_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Resultado
extern void ui_Resultado_screen_init(void);
extern void ui_Resultado_screen_destroy(void);
extern lv_obj_t * ui_Resultado;
extern lv_obj_t * ui_ResultadoHead;
extern lv_obj_t * ui_ResultadoHeadImg;
extern lv_obj_t * ui_ResultadoTitle;
extern lv_obj_t * ui_ResultadoMain;
extern lv_obj_t * ui_ResultadoResumen;
extern lv_obj_t * ui_ResultadoExitoso;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_ResultadoFalla;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_ResultadoDetenido;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_ResultadoDetalle;
extern lv_obj_t * ui_ResultadoDetalleText;
extern lv_obj_t * ui_ResultadoButtons;
extern lv_obj_t * ui_ResultadoBtnVolver;
extern lv_obj_t * ui_ResultadoBtnVolverImg;
extern lv_obj_t * ui_ResultadoBtnVolverText;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

