// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Running

#ifndef UI_RUNNING_H
#define UI_RUNNING_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Running
extern void ui_Running_screen_init(void);
extern void ui_Running_screen_destroy(void);
extern lv_obj_t * ui_Running;
extern lv_obj_t * ui_RunningMain;
extern lv_obj_t * ui_RunningMainContenido;
extern lv_obj_t * ui_RunningTabView;
extern lv_obj_t * ui_TabPageProgress;
extern lv_obj_t * ui_ElapsedTime;
extern lv_obj_t * ui_ElapsedTimeTitle;
extern lv_obj_t * ui_ElapsedTimeValue;
extern lv_obj_t * ui_TotalProgress;
extern lv_obj_t * ui_TotalProgressTitle;
extern lv_obj_t * ui_TotalProgressBar;
extern lv_obj_t * ui_TotalProgressValue;
extern lv_obj_t * ui_ProgressHealth;
extern lv_obj_t * ui_ProgressHealthTitle;
extern lv_obj_t * ui_HealthEstado;
extern lv_obj_t * ui_HealthNormalImg;
extern lv_obj_t * ui_HealthWarningImg;
extern lv_obj_t * ui_HealthCriticalImg;
extern lv_obj_t * ui_TabPageProgressBtnDetener;
extern lv_obj_t * ui_TabPageProgressBtnDetenerText;
extern lv_obj_t * ui_TabPageObjetivos;
extern lv_obj_t * ui_RunningObjetivosTitle;
extern lv_obj_t * ui_RunningObjetivos;
extern lv_obj_t * ui_RunningObjetivoIntensidad;
extern lv_obj_t * ui_RunningObjetivoIntensidadImg;
extern lv_obj_t * ui_RunningObjetivoIntensidadValue;
extern lv_obj_t * ui_RunningObjetivoFreq;
extern lv_obj_t * ui_RunningObjetivoFreqImg;
extern lv_obj_t * ui_RunningObjetivoFreqValue;
extern lv_obj_t * ui_RunningObjetivoDuracion;
extern lv_obj_t * ui_RunningObjetivoDuracionImg;
extern lv_obj_t * ui_RunningObjetivoDuracionValue;
extern lv_obj_t * ui_RunningRangosTitle;
extern lv_obj_t * ui_RunningRangos;
extern lv_obj_t * ui_RunningRangoIntensidad;
extern lv_obj_t * ui_RunningRangoIntensidadImg;
extern lv_obj_t * ui_RunningRangoIntensidadValue;
extern lv_obj_t * ui_RunningRangoTempNormal;
extern lv_obj_t * ui_RunningRangoTempNormalImg;
extern lv_obj_t * ui_RunningRangoTempNormalValue;
extern lv_obj_t * ui_RunningRangoTempCritica;
extern lv_obj_t * ui_RunningRangoTempCriticaImg;
extern lv_obj_t * ui_RunningRangoTempCriticaValue;
extern lv_obj_t * ui_TabPageMediciones;
extern lv_obj_t * ui_MedicionTemperatura;
extern lv_obj_t * ui_MedicionTemperaturaArc;
extern lv_obj_t * ui_MedicionTempImg;
extern lv_obj_t * ui_MedicionTempValue;
extern lv_obj_t * ui_MedicionTempLastUpdate;
extern lv_obj_t * ui_MedicionCorriente;
extern lv_obj_t * ui_MedicionCorrienteArc;
extern lv_obj_t * ui_MedicionCorrienteImg;
extern lv_obj_t * ui_MedicionCorrienteValue;
extern lv_obj_t * ui_MedicionCorrienteLastUpdate;
extern lv_obj_t * ui_MedicionCampoMagnetico;
extern lv_obj_t * ui_MedicionCampoMagneticoArc;
extern lv_obj_t * ui_MedicionCampoMagneticoImg;
extern lv_obj_t * ui_MedicionCampoMagneticoValue;
extern lv_obj_t * ui_MedicionCampoMagneticoLastUpdate;
extern lv_obj_t * ui_TabPageAlertas;
extern lv_obj_t * ui_Alert1;
extern lv_obj_t * ui_Alert1CritImg;
extern lv_obj_t * ui_Alert1WarningImg;
extern lv_obj_t * ui_Alert1TypeAlertSource;
extern lv_obj_t * ui_Alert1TypeAlertText;
extern lv_obj_t * ui_Alert1SourceText;
extern lv_obj_t * ui_Alert1StatsLastUpdate;
extern lv_obj_t * ui_Alert1Stats;
extern lv_obj_t * ui_Alert1StatsCountText;
extern lv_obj_t * ui_Alert1StatsSpacerText;
extern lv_obj_t * ui_Alert1StatsMaxText;
extern lv_obj_t * ui_Alert1LastUpdateText;
extern lv_obj_t * ui_Alert2;
extern lv_obj_t * ui_Alert2CritImg;
extern lv_obj_t * ui_Alert2WarningImg;
extern lv_obj_t * ui_Alert2TypeAlertSource;
extern lv_obj_t * ui_Alert2TypeAlertText;
extern lv_obj_t * ui_Alert2SourceText;
extern lv_obj_t * ui_Alert2StatsLastUpdate;
extern lv_obj_t * ui_Alert2Stats;
extern lv_obj_t * ui_Alert2StatsCountText;
extern lv_obj_t * ui_Alert2StatsSpacerText;
extern lv_obj_t * ui_Alert2StatsMaxText;
extern lv_obj_t * ui_Alert2LastUpdateText;
extern lv_obj_t * ui_Alert3;
extern lv_obj_t * ui_Alert3CritImg;
extern lv_obj_t * ui_Alert2WarningImg1;
extern lv_obj_t * ui_Alert3TypeAlertSource;
extern lv_obj_t * ui_Alert3TypeAlertText;
extern lv_obj_t * ui_Alert3SourceText;
extern lv_obj_t * ui_Alert3StatsLastUpdate;
extern lv_obj_t * ui_Alert3Stats;
extern lv_obj_t * ui_Alert3StatsCountText;
extern lv_obj_t * ui_Alert3StatsSpacerText;
extern lv_obj_t * ui_Alert3StatsMaxText;
extern lv_obj_t * ui_Alert3LastUpdateText;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

