// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: UiFinalParte1

#ifndef UI_RESULTADOSCREEN_H
#define UI_RESULTADOSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ResultadoScreen
extern void ui_ResultadoScreen_screen_init(void);
extern void ui_ResultadoScreen_screen_destroy(void);
extern lv_obj_t * ui_ResultadoScreen;
extern lv_obj_t * ui_ResultadoHeader;
extern lv_obj_t * ui_ResultadoTitle;
extern lv_obj_t * ui_ResultadoMain;
extern lv_obj_t * ui_ResultadoCompletado;
extern lv_obj_t * ui_ResultadoMotivoCompletado;
extern lv_obj_t * ui_ResultadoMotivoCompletadoTitle;
extern lv_obj_t * ui_ResultadoMotivoCompletadoTipoCampo;
extern lv_obj_t * ui_ResultadoMotivoCompletadoDetalle;
extern lv_obj_t * ui_ResultadoMotivoCompletadoMotivo;
extern lv_obj_t * ui_ResultadoMotivoCompletadoMotivoDetalle;
extern lv_obj_t * ui_ResultadoDetenido;
extern lv_obj_t * ui_ResultadoMotivoDetenido;
extern lv_obj_t * ui_ResultadoMotivoDetenidoTitle;
extern lv_obj_t * ui_ResultadoMotivoDetenidoTipoCampo;
extern lv_obj_t * ui_ResultadoMotivoDetenidoDetalle;
extern lv_obj_t * ui_ResultadoMotivoDetenidoMotivo;
extern lv_obj_t * ui_ResultadoMotivoDetenidoMotivoDetalle;
extern lv_obj_t * ui_ResultadoFalla;
extern lv_obj_t * ui_ResultadoMotivoFalla;
extern lv_obj_t * ui_ResultadoMotivoFallaTitle;
extern lv_obj_t * ui_ResultadoMotivoFallaTipoCampo;
extern lv_obj_t * ui_ResultadoMotivoFallaDetalle;
extern lv_obj_t * ui_ResultadoMotivoFallaMotivo;
extern lv_obj_t * ui_ResultadoMotivoFallaMotivoDetalle;
extern lv_obj_t * ui_ResultadoResumen;
extern lv_obj_t * ui_ResultadoProgreso;
extern lv_obj_t * ui_ResultadoProgresoTitle;
extern lv_obj_t * ui_ResultadoProgresoData;
extern lv_obj_t * ui_ResultadoProgresoValor;
extern lv_obj_t * ui_ResultadoTranscurrido;
extern lv_obj_t * ui_ResultadoTranscurridoTitle;
extern lv_obj_t * ui_ResultadoTranscurridoData;
extern lv_obj_t * ui_ResultadoTranscurridoDataHoras;
extern lv_obj_t * ui_ResultadoProgresoHorasValor;
extern lv_obj_t * ui_ResultadoProgresoHorasTitle;
extern lv_obj_t * ui_ResultadoTranscurridoDataMinutos;
extern lv_obj_t * ui_ResultadoProgresoMinutosValor;
extern lv_obj_t * ui_ResultadoProgresoMinutosTitle;
extern lv_obj_t * ui_ResultadoCampoMedio;
extern lv_obj_t * ui_ResultadoCampoMedioTitle;
extern lv_obj_t * ui_ResultadoCampoMedioData;
extern lv_obj_t * ui_ResultadoCampoMedioUnidadValor;
extern lv_obj_t * ui_ResultadoCampoMedioUnidadTitle;
extern lv_obj_t * ui_ResultadoOptionsButtons;
extern lv_obj_t * ui_ButtonResultadoPrincipal;
extern lv_obj_t * ui_ButtonResultadoPrincipalTexto;
extern lv_obj_t * ui_ButtonResultadoRepetir;
extern lv_obj_t * ui_ButtonResultadoRepetirTexto;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

