// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Running

#include "ui.h"

lv_obj_t * ui_Running = NULL;
lv_obj_t * ui_RunningMain = NULL;
lv_obj_t * ui_RunningMainContenido = NULL;
lv_obj_t * ui_RunningTabView = NULL;
lv_obj_t * ui_TabPageProgress = NULL;
lv_obj_t * ui_ElapsedTime = NULL;
lv_obj_t * ui_ElapsedTimeTitle = NULL;
lv_obj_t * ui_ElapsedTimeValue = NULL;
lv_obj_t * ui_TotalProgress = NULL;
lv_obj_t * ui_TotalProgressTitle = NULL;
lv_obj_t * ui_TotalProgressBar = NULL;
lv_obj_t * ui_TotalProgressValue = NULL;
lv_obj_t * ui_ProgressHealth = NULL;
lv_obj_t * ui_ProgressHealthTitle = NULL;
lv_obj_t * ui_HealthEstado = NULL;
lv_obj_t * ui_HealthNormalImg = NULL;
lv_obj_t * ui_HealthWarningImg = NULL;
lv_obj_t * ui_HealthCriticalImg = NULL;
lv_obj_t * ui_TabPageProgressBtnDetener = NULL;
lv_obj_t * ui_TabPageProgressBtnDetenerText = NULL;
lv_obj_t * ui_TabPageObjetivos = NULL;
lv_obj_t * ui_RunningObjetivosTitle = NULL;
lv_obj_t * ui_RunningObjetivos = NULL;
lv_obj_t * ui_RunningObjetivoIntensidad = NULL;
lv_obj_t * ui_RunningObjetivoIntensidadImg = NULL;
lv_obj_t * ui_RunningObjetivoIntensidadValue = NULL;
lv_obj_t * ui_RunningObjetivoFreq = NULL;
lv_obj_t * ui_RunningObjetivoFreqImg = NULL;
lv_obj_t * ui_RunningObjetivoFreqValue = NULL;
lv_obj_t * ui_RunningObjetivoDuracion = NULL;
lv_obj_t * ui_RunningObjetivoDuracionImg = NULL;
lv_obj_t * ui_RunningObjetivoDuracionValue = NULL;
lv_obj_t * ui_RunningRangosTitle = NULL;
lv_obj_t * ui_RunningRangos = NULL;
lv_obj_t * ui_RunningRangoIntensidad = NULL;
lv_obj_t * ui_RunningRangoIntensidadImg = NULL;
lv_obj_t * ui_RunningRangoIntensidadValue = NULL;
lv_obj_t * ui_RunningRangoTempNormal = NULL;
lv_obj_t * ui_RunningRangoTempNormalImg = NULL;
lv_obj_t * ui_RunningRangoTempNormalValue = NULL;
lv_obj_t * ui_RunningRangoTempCritica = NULL;
lv_obj_t * ui_RunningRangoTempCriticaImg = NULL;
lv_obj_t * ui_RunningRangoTempCriticaValue = NULL;
lv_obj_t * ui_TabPageMediciones = NULL;
lv_obj_t * ui_MedicionTemperatura = NULL;
lv_obj_t * ui_MedicionTemperaturaArc = NULL;
lv_obj_t * ui_MedicionTempImg = NULL;
lv_obj_t * ui_MedicionTempValue = NULL;
lv_obj_t * ui_MedicionTempLastUpdate = NULL;
lv_obj_t * ui_MedicionCorriente = NULL;
lv_obj_t * ui_MedicionCorrienteArc = NULL;
lv_obj_t * ui_MedicionCorrienteImg = NULL;
lv_obj_t * ui_MedicionCorrienteValue = NULL;
lv_obj_t * ui_MedicionCorrienteLastUpdate = NULL;
lv_obj_t * ui_MedicionCampoMagnetico = NULL;
lv_obj_t * ui_MedicionCampoMagneticoArc = NULL;
lv_obj_t * ui_MedicionCampoMagneticoImg = NULL;
lv_obj_t * ui_MedicionCampoMagneticoValue = NULL;
lv_obj_t * ui_MedicionCampoMagneticoLastUpdate = NULL;
lv_obj_t * ui_TabPageAlertas = NULL;
lv_obj_t * ui_Alert1 = NULL;
lv_obj_t * ui_Alert1CritImg = NULL;
lv_obj_t * ui_Alert1WarningImg = NULL;
lv_obj_t * ui_Alert1TypeAlertSource = NULL;
lv_obj_t * ui_Alert1TypeAlertText = NULL;
lv_obj_t * ui_Alert1SourceText = NULL;
lv_obj_t * ui_Alert1StatsLastUpdate = NULL;
lv_obj_t * ui_Alert1Stats = NULL;
lv_obj_t * ui_Alert1StatsCountText = NULL;
lv_obj_t * ui_Alert1StatsSpacerText = NULL;
lv_obj_t * ui_Alert1StatsMaxText = NULL;
lv_obj_t * ui_Alert1LastUpdateText = NULL;
lv_obj_t * ui_Alert2 = NULL;
lv_obj_t * ui_Alert2CritImg = NULL;
lv_obj_t * ui_Alert2WarningImg = NULL;
lv_obj_t * ui_Alert2TypeAlertSource = NULL;
lv_obj_t * ui_Alert2TypeAlertText = NULL;
lv_obj_t * ui_Alert2SourceText = NULL;
lv_obj_t * ui_Alert2StatsLastUpdate = NULL;
lv_obj_t * ui_Alert2Stats = NULL;
lv_obj_t * ui_Alert2StatsCountText = NULL;
lv_obj_t * ui_Alert2StatsSpacerText = NULL;
lv_obj_t * ui_Alert2StatsMaxText = NULL;
lv_obj_t * ui_Alert2LastUpdateText = NULL;
lv_obj_t * ui_Alert3 = NULL;
lv_obj_t * ui_Alert3CritImg = NULL;
lv_obj_t * ui_Alert2WarningImg1 = NULL;
lv_obj_t * ui_Alert3TypeAlertSource = NULL;
lv_obj_t * ui_Alert3TypeAlertText = NULL;
lv_obj_t * ui_Alert3SourceText = NULL;
lv_obj_t * ui_Alert3StatsLastUpdate = NULL;
lv_obj_t * ui_Alert3Stats = NULL;
lv_obj_t * ui_Alert3StatsCountText = NULL;
lv_obj_t * ui_Alert3StatsSpacerText = NULL;
lv_obj_t * ui_Alert3StatsMaxText = NULL;
lv_obj_t * ui_Alert3LastUpdateText = NULL;
// event funtions

// build funtions

void ui_Running_screen_init(void)
{
    ui_Running = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Running, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_RunningMain = lv_obj_create(ui_Running);
    lv_obj_remove_style_all(ui_RunningMain);
    lv_obj_set_width(ui_RunningMain, 316);
    lv_obj_set_height(ui_RunningMain, 236);
    lv_obj_set_align(ui_RunningMain, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_RunningMain, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_RunningMain, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_RunningMain, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_RunningMainContenido = lv_obj_create(ui_RunningMain);
    lv_obj_set_width(ui_RunningMainContenido, lv_pct(100));
    lv_obj_set_height(ui_RunningMainContenido, lv_pct(100));
    lv_obj_set_x(ui_RunningMainContenido, 0);
    lv_obj_set_y(ui_RunningMainContenido, -40);
    lv_obj_set_align(ui_RunningMainContenido, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_RunningMainContenido, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_RunningMainContenido, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_RunningMainContenido, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_RunningTabView = lv_tabview_create(ui_RunningMainContenido);
    lv_tabview_set_tab_bar_size(ui_RunningTabView, 30);
    lv_obj_set_width(ui_RunningTabView, lv_pct(100));
    lv_obj_set_height(ui_RunningTabView, lv_pct(100));
    lv_obj_set_x(ui_RunningTabView, 158);
    lv_obj_set_y(ui_RunningTabView, 112);
    lv_obj_set_align(ui_RunningTabView, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_RunningTabView, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_set_style_text_font(lv_tabview_get_tab_bar(ui_RunningTabView), &lv_font_montserrat_12,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabPageProgress = lv_tabview_add_tab(ui_RunningTabView, "Progreso");
    lv_obj_set_flex_flow(ui_TabPageProgress, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_TabPageProgress, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_style_bg_color(ui_TabPageProgress, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TabPageProgress, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TabPageProgress, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ElapsedTime = lv_obj_create(ui_TabPageProgress);
    lv_obj_remove_style_all(ui_ElapsedTime);
    lv_obj_set_height(ui_ElapsedTime, 24);
    lv_obj_set_width(ui_ElapsedTime, lv_pct(100));
    lv_obj_set_align(ui_ElapsedTime, LV_ALIGN_LEFT_MID);
    lv_obj_set_flex_flow(ui_ElapsedTime, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ElapsedTime, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ElapsedTime, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_ElapsedTime, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ElapsedTime, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ElapsedTimeTitle = lv_label_create(ui_ElapsedTime);
    lv_obj_set_width(ui_ElapsedTimeTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ElapsedTimeTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ElapsedTimeTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ElapsedTimeTitle, "Transcurrido:");

    ui_ElapsedTimeValue = lv_label_create(ui_ElapsedTime);
    lv_obj_set_width(ui_ElapsedTimeValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ElapsedTimeValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ElapsedTimeValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ElapsedTimeValue, "00h 00m 00s");

    ui_TotalProgress = lv_obj_create(ui_TabPageProgress);
    lv_obj_remove_style_all(ui_TotalProgress);
    lv_obj_set_height(ui_TotalProgress, 24);
    lv_obj_set_width(ui_TotalProgress, lv_pct(100));
    lv_obj_set_align(ui_TotalProgress, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_TotalProgress, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_TotalProgress, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_TotalProgress, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_TotalProgress, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_TotalProgress, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TotalProgressTitle = lv_label_create(ui_TotalProgress);
    lv_obj_set_width(ui_TotalProgressTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TotalProgressTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TotalProgressTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TotalProgressTitle, "Progreso:");

    ui_TotalProgressBar = lv_bar_create(ui_TotalProgress);
    lv_bar_set_value(ui_TotalProgressBar, 22, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_TotalProgressBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_TotalProgressBar, 140);
    lv_obj_set_height(ui_TotalProgressBar, 20);
    lv_obj_set_align(ui_TotalProgressBar, LV_ALIGN_CENTER);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_TotalProgressBar, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_TotalProgressBar,
                                                                                                       lv_obj_get_style_pad_right(ui_TotalProgressBar, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_TotalProgressValue = lv_label_create(ui_TotalProgress);
    lv_obj_set_width(ui_TotalProgressValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TotalProgressValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TotalProgressValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TotalProgressValue, "22.5 %");

    ui_ProgressHealth = lv_obj_create(ui_TabPageProgress);
    lv_obj_remove_style_all(ui_ProgressHealth);
    lv_obj_set_height(ui_ProgressHealth, 32);
    lv_obj_set_width(ui_ProgressHealth, lv_pct(100));
    lv_obj_set_align(ui_ProgressHealth, LV_ALIGN_LEFT_MID);
    lv_obj_set_flex_flow(ui_ProgressHealth, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ProgressHealth, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ProgressHealth, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_ProgressHealth, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ProgressHealth, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ProgressHealthTitle = lv_label_create(ui_ProgressHealth);
    lv_obj_set_width(ui_ProgressHealthTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ProgressHealthTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ProgressHealthTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ProgressHealthTitle, "Estado:");

    ui_HealthEstado = lv_label_create(ui_ProgressHealth);
    lv_obj_set_width(ui_HealthEstado, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HealthEstado, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_HealthEstado, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HealthEstado, "NORMAL");

    ui_HealthNormalImg = lv_image_create(ui_ProgressHealth);
    lv_image_set_src(ui_HealthNormalImg, &ui_img_estadook_png);
    lv_obj_set_width(ui_HealthNormalImg, 40);
    lv_obj_set_height(ui_HealthNormalImg, 40);
    lv_obj_set_align(ui_HealthNormalImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HealthNormalImg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_HealthNormalImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_HealthNormalImg, LV_IMAGE_ALIGN_TILE);

    ui_HealthWarningImg = lv_image_create(ui_ProgressHealth);
    lv_image_set_src(ui_HealthWarningImg, &ui_img_estadowarning_png);
    lv_obj_set_width(ui_HealthWarningImg, 40);
    lv_obj_set_height(ui_HealthWarningImg, 40);
    lv_obj_set_align(ui_HealthWarningImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HealthWarningImg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_HealthWarningImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_HealthWarningImg, LV_IMAGE_ALIGN_TILE);

    ui_HealthCriticalImg = lv_image_create(ui_ProgressHealth);
    lv_image_set_src(ui_HealthCriticalImg, &ui_img_estadocritical_png);
    lv_obj_set_width(ui_HealthCriticalImg, 40);
    lv_obj_set_height(ui_HealthCriticalImg, 40);
    lv_obj_set_align(ui_HealthCriticalImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HealthCriticalImg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_HealthCriticalImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_HealthCriticalImg, LV_IMAGE_ALIGN_TILE);

    ui_TabPageProgressBtnDetener = lv_button_create(ui_TabPageProgress);
    lv_obj_set_height(ui_TabPageProgressBtnDetener, 30);
    lv_obj_set_width(ui_TabPageProgressBtnDetener, lv_pct(100));
    lv_obj_set_align(ui_TabPageProgressBtnDetener, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TabPageProgressBtnDetener, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_TabPageProgressBtnDetener, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TabPageProgressBtnDetener, lv_color_hex(0xFF4F4F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TabPageProgressBtnDetener, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabPageProgressBtnDetenerText = lv_label_create(ui_TabPageProgressBtnDetener);
    lv_obj_set_width(ui_TabPageProgressBtnDetenerText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TabPageProgressBtnDetenerText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TabPageProgressBtnDetenerText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TabPageProgressBtnDetenerText, "DETENER");

    ui_TabPageObjetivos = lv_tabview_add_tab(ui_RunningTabView, "Objetivos");
    lv_obj_set_flex_flow(ui_TabPageObjetivos, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_TabPageObjetivos, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_style_bg_color(ui_TabPageObjetivos, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TabPageObjetivos, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TabPageObjetivos, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RunningObjetivosTitle = lv_label_create(ui_TabPageObjetivos);
    lv_obj_set_width(ui_RunningObjetivosTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RunningObjetivosTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_RunningObjetivosTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RunningObjetivosTitle, "Objetivos");

    ui_RunningObjetivos = lv_obj_create(ui_TabPageObjetivos);
    lv_obj_remove_style_all(ui_RunningObjetivos);
    lv_obj_set_width(ui_RunningObjetivos, lv_pct(100));
    lv_obj_set_height(ui_RunningObjetivos, LV_SIZE_CONTENT);    /// 110
    lv_obj_set_align(ui_RunningObjetivos, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_RunningObjetivos, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_RunningObjetivos, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_RunningObjetivos, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_RunningObjetivos, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_RunningObjetivos, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RunningObjetivoIntensidad = lv_obj_create(ui_RunningObjetivos);
    lv_obj_remove_style_all(ui_RunningObjetivoIntensidad);
    lv_obj_set_height(ui_RunningObjetivoIntensidad, 32);
    lv_obj_set_width(ui_RunningObjetivoIntensidad, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_align(ui_RunningObjetivoIntensidad, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_RunningObjetivoIntensidad, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_RunningObjetivoIntensidad, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_RunningObjetivoIntensidad, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_RunningObjetivoIntensidad, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_RunningObjetivoIntensidad, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RunningObjetivoIntensidadImg = lv_image_create(ui_RunningObjetivoIntensidad);
    lv_image_set_src(ui_RunningObjetivoIntensidadImg, &ui_img_campo_png);
    lv_obj_set_width(ui_RunningObjetivoIntensidadImg, 40);
    lv_obj_set_height(ui_RunningObjetivoIntensidadImg, 40);
    lv_obj_set_align(ui_RunningObjetivoIntensidadImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_RunningObjetivoIntensidadImg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_RunningObjetivoIntensidadImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_RunningObjetivoIntensidadImg, LV_IMAGE_ALIGN_TILE);

    ui_RunningObjetivoIntensidadValue = lv_label_create(ui_RunningObjetivoIntensidad);
    lv_obj_set_width(ui_RunningObjetivoIntensidadValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RunningObjetivoIntensidadValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_RunningObjetivoIntensidadValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RunningObjetivoIntensidadValue, "1.0 mT");

    ui_RunningObjetivoFreq = lv_obj_create(ui_RunningObjetivos);
    lv_obj_remove_style_all(ui_RunningObjetivoFreq);
    lv_obj_set_height(ui_RunningObjetivoFreq, 26);
    lv_obj_set_width(ui_RunningObjetivoFreq, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_align(ui_RunningObjetivoFreq, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_RunningObjetivoFreq, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_RunningObjetivoFreq, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_RunningObjetivoFreq, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_RunningObjetivoFreq, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_RunningObjetivoFreq, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RunningObjetivoFreqImg = lv_image_create(ui_RunningObjetivoFreq);
    lv_image_set_src(ui_RunningObjetivoFreqImg, &ui_img_frecuencia_png);
    lv_obj_set_width(ui_RunningObjetivoFreqImg, 40);
    lv_obj_set_height(ui_RunningObjetivoFreqImg, 40);
    lv_obj_set_align(ui_RunningObjetivoFreqImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_RunningObjetivoFreqImg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_RunningObjetivoFreqImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_RunningObjetivoFreqImg, LV_IMAGE_ALIGN_TILE);

    ui_RunningObjetivoFreqValue = lv_label_create(ui_RunningObjetivoFreq);
    lv_obj_set_width(ui_RunningObjetivoFreqValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RunningObjetivoFreqValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_RunningObjetivoFreqValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RunningObjetivoFreqValue, "50 Hz");

    ui_RunningObjetivoDuracion = lv_obj_create(ui_RunningObjetivos);
    lv_obj_remove_style_all(ui_RunningObjetivoDuracion);
    lv_obj_set_height(ui_RunningObjetivoDuracion, 26);
    lv_obj_set_width(ui_RunningObjetivoDuracion, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_align(ui_RunningObjetivoDuracion, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_RunningObjetivoDuracion, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_RunningObjetivoDuracion, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_RunningObjetivoDuracion, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_RunningObjetivoDuracion, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_RunningObjetivoDuracion, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RunningObjetivoDuracionImg = lv_image_create(ui_RunningObjetivoDuracion);
    lv_image_set_src(ui_RunningObjetivoDuracionImg, &ui_img_2_png);
    lv_obj_set_width(ui_RunningObjetivoDuracionImg, 40);
    lv_obj_set_height(ui_RunningObjetivoDuracionImg, 40);
    lv_obj_set_align(ui_RunningObjetivoDuracionImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_RunningObjetivoDuracionImg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_RunningObjetivoDuracionImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_RunningObjetivoDuracionImg, LV_IMAGE_ALIGN_TILE);

    ui_RunningObjetivoDuracionValue = lv_label_create(ui_RunningObjetivoDuracion);
    lv_obj_set_width(ui_RunningObjetivoDuracionValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RunningObjetivoDuracionValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_RunningObjetivoDuracionValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RunningObjetivoDuracionValue, "01h 20m");

    ui_RunningRangosTitle = lv_label_create(ui_TabPageObjetivos);
    lv_obj_set_width(ui_RunningRangosTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RunningRangosTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_RunningRangosTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RunningRangosTitle, "Rangos normal y critico");

    ui_RunningRangos = lv_obj_create(ui_TabPageObjetivos);
    lv_obj_remove_style_all(ui_RunningRangos);
    lv_obj_set_width(ui_RunningRangos, lv_pct(100));
    lv_obj_set_height(ui_RunningRangos, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_RunningRangos, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_RunningRangos, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_RunningRangos, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_RunningRangos, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_RunningRangoIntensidad = lv_obj_create(ui_RunningRangos);
    lv_obj_remove_style_all(ui_RunningRangoIntensidad);
    lv_obj_set_height(ui_RunningRangoIntensidad, 32);
    lv_obj_set_width(ui_RunningRangoIntensidad, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_align(ui_RunningRangoIntensidad, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_RunningRangoIntensidad, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_RunningRangoIntensidad, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_RunningRangoIntensidad, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_RunningRangoIntensidad, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_RunningRangoIntensidad, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RunningRangoIntensidadImg = lv_image_create(ui_RunningRangoIntensidad);
    lv_image_set_src(ui_RunningRangoIntensidadImg, &ui_img_tolcampo_png);
    lv_obj_set_width(ui_RunningRangoIntensidadImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RunningRangoIntensidadImg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_RunningRangoIntensidadImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_RunningRangoIntensidadImg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_RunningRangoIntensidadImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_RunningRangoIntensidadValue = lv_label_create(ui_RunningRangoIntensidad);
    lv_obj_set_width(ui_RunningRangoIntensidadValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RunningRangoIntensidadValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_RunningRangoIntensidadValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RunningRangoIntensidadValue, "1%");

    ui_RunningRangoTempNormal = lv_obj_create(ui_RunningRangos);
    lv_obj_remove_style_all(ui_RunningRangoTempNormal);
    lv_obj_set_height(ui_RunningRangoTempNormal, 32);
    lv_obj_set_width(ui_RunningRangoTempNormal, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_align(ui_RunningRangoTempNormal, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_RunningRangoTempNormal, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_RunningRangoTempNormal, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_RunningRangoTempNormal, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_RunningRangoTempNormal, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_RunningRangoTempNormal, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RunningRangoTempNormalImg = lv_image_create(ui_RunningRangoTempNormal);
    lv_image_set_src(ui_RunningRangoTempNormalImg, &ui_img_temp_normal_png);
    lv_obj_set_width(ui_RunningRangoTempNormalImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RunningRangoTempNormalImg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_RunningRangoTempNormalImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_RunningRangoTempNormalImg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_RunningRangoTempNormalImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_RunningRangoTempNormalValue = lv_label_create(ui_RunningRangoTempNormal);
    lv_obj_set_width(ui_RunningRangoTempNormalValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RunningRangoTempNormalValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_RunningRangoTempNormalValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RunningRangoTempNormalValue, "20-28 C");

    ui_RunningRangoTempCritica = lv_obj_create(ui_RunningRangos);
    lv_obj_remove_style_all(ui_RunningRangoTempCritica);
    lv_obj_set_height(ui_RunningRangoTempCritica, 32);
    lv_obj_set_width(ui_RunningRangoTempCritica, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_align(ui_RunningRangoTempCritica, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_RunningRangoTempCritica, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_RunningRangoTempCritica, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_RunningRangoTempCritica, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_RunningRangoTempCritica, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_RunningRangoTempCritica, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RunningRangoTempCriticaImg = lv_image_create(ui_RunningRangoTempCritica);
    lv_image_set_src(ui_RunningRangoTempCriticaImg, &ui_img_temp_critica_png);
    lv_obj_set_width(ui_RunningRangoTempCriticaImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RunningRangoTempCriticaImg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_RunningRangoTempCriticaImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_RunningRangoTempCriticaImg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_RunningRangoTempCriticaImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_RunningRangoTempCriticaValue = lv_label_create(ui_RunningRangoTempCritica);
    lv_obj_set_width(ui_RunningRangoTempCriticaValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RunningRangoTempCriticaValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_RunningRangoTempCriticaValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RunningRangoTempCriticaValue, "20-28 C");

    ui_TabPageMediciones = lv_tabview_add_tab(ui_RunningTabView, "Mediciones");
    lv_obj_set_flex_flow(ui_TabPageMediciones, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_TabPageMediciones, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_style_bg_color(ui_TabPageMediciones, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TabPageMediciones, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TabPageMediciones, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MedicionTemperatura = lv_obj_create(ui_TabPageMediciones);
    lv_obj_remove_style_all(ui_MedicionTemperatura);
    lv_obj_set_width(ui_MedicionTemperatura, lv_pct(30));
    lv_obj_set_height(ui_MedicionTemperatura, lv_pct(100));
    lv_obj_set_align(ui_MedicionTemperatura, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_MedicionTemperatura, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_MedicionTemperatura, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_MedicionTemperatura, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_MedicionTemperatura, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_MedicionTemperatura, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MedicionTemperaturaArc = lv_arc_create(ui_MedicionTemperatura);
    lv_obj_set_width(ui_MedicionTemperaturaArc, 74);
    lv_obj_set_height(ui_MedicionTemperaturaArc, 74);
    lv_obj_set_align(ui_MedicionTemperaturaArc, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_MedicionTemperaturaArc, 0, 60);
    lv_arc_set_value(ui_MedicionTemperaturaArc, 0);
    lv_obj_set_style_arc_width(ui_MedicionTemperaturaArc, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_width(ui_MedicionTemperaturaArc, 8, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_MedicionTemperaturaArc, true, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_opa(ui_MedicionTemperaturaArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_MedicionTempImg = lv_image_create(ui_MedicionTemperaturaArc);
    lv_image_set_src(ui_MedicionTempImg, &ui_img_temp_normal_png);
    lv_obj_set_width(ui_MedicionTempImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MedicionTempImg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MedicionTempImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MedicionTempImg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_MedicionTempImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MedicionTempValue = lv_label_create(ui_MedicionTemperatura);
    lv_obj_set_width(ui_MedicionTempValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MedicionTempValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MedicionTempValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MedicionTempValue, "0.0 C");
    lv_obj_set_style_text_font(ui_MedicionTempValue, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MedicionTempLastUpdate = lv_label_create(ui_MedicionTemperatura);
    lv_obj_set_width(ui_MedicionTempLastUpdate, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MedicionTempLastUpdate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MedicionTempLastUpdate, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MedicionTempLastUpdate, "Sin datos");
    lv_obj_set_style_text_font(ui_MedicionTempLastUpdate, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MedicionCorriente = lv_obj_create(ui_TabPageMediciones);
    lv_obj_remove_style_all(ui_MedicionCorriente);
    lv_obj_set_width(ui_MedicionCorriente, lv_pct(30));
    lv_obj_set_height(ui_MedicionCorriente, lv_pct(100));
    lv_obj_set_align(ui_MedicionCorriente, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_MedicionCorriente, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_MedicionCorriente, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_MedicionCorriente, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_MedicionCorriente, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_MedicionCorriente, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MedicionCorrienteArc = lv_arc_create(ui_MedicionCorriente);
    lv_obj_set_width(ui_MedicionCorrienteArc, 74);
    lv_obj_set_height(ui_MedicionCorrienteArc, 74);
    lv_obj_set_align(ui_MedicionCorrienteArc, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_MedicionCorrienteArc, 0, 80);
    lv_arc_set_value(ui_MedicionCorrienteArc, 0);
    lv_obj_set_style_arc_width(ui_MedicionCorrienteArc, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_MedicionCorrienteArc, lv_color_hex(0xFFCE28), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_MedicionCorrienteArc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_MedicionCorrienteArc, 8, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_opa(ui_MedicionCorrienteArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_MedicionCorrienteImg = lv_image_create(ui_MedicionCorrienteArc);
    lv_image_set_src(ui_MedicionCorrienteImg, &ui_img_bobina_png);
    lv_obj_set_width(ui_MedicionCorrienteImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MedicionCorrienteImg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MedicionCorrienteImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MedicionCorrienteImg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_MedicionCorrienteImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MedicionCorrienteValue = lv_label_create(ui_MedicionCorriente);
    lv_obj_set_width(ui_MedicionCorrienteValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MedicionCorrienteValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MedicionCorrienteValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MedicionCorrienteValue, "0.0 A");
    lv_obj_set_style_text_font(ui_MedicionCorrienteValue, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MedicionCorrienteLastUpdate = lv_label_create(ui_MedicionCorriente);
    lv_obj_set_width(ui_MedicionCorrienteLastUpdate, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MedicionCorrienteLastUpdate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MedicionCorrienteLastUpdate, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MedicionCorrienteLastUpdate, "Sin datos");
    lv_obj_set_style_text_font(ui_MedicionCorrienteLastUpdate, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MedicionCampoMagnetico = lv_obj_create(ui_TabPageMediciones);
    lv_obj_remove_style_all(ui_MedicionCampoMagnetico);
    lv_obj_set_width(ui_MedicionCampoMagnetico, lv_pct(30));
    lv_obj_set_height(ui_MedicionCampoMagnetico, lv_pct(100));
    lv_obj_set_align(ui_MedicionCampoMagnetico, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_MedicionCampoMagnetico, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_MedicionCampoMagnetico, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_MedicionCampoMagnetico, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_MedicionCampoMagnetico, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_MedicionCampoMagnetico, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MedicionCampoMagneticoArc = lv_arc_create(ui_MedicionCampoMagnetico);
    lv_obj_set_width(ui_MedicionCampoMagneticoArc, 74);
    lv_obj_set_height(ui_MedicionCampoMagneticoArc, 74);
    lv_obj_set_align(ui_MedicionCampoMagneticoArc, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_MedicionCampoMagneticoArc, 0, 40);
    lv_arc_set_value(ui_MedicionCampoMagneticoArc, 0);
    lv_obj_set_style_arc_width(ui_MedicionCampoMagneticoArc, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_MedicionCampoMagneticoArc, lv_color_hex(0xFF4B30), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_MedicionCampoMagneticoArc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_MedicionCampoMagneticoArc, 8, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_opa(ui_MedicionCampoMagneticoArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_MedicionCampoMagneticoImg = lv_image_create(ui_MedicionCampoMagneticoArc);
    lv_image_set_src(ui_MedicionCampoMagneticoImg, &ui_img_campo_png);
    lv_obj_set_width(ui_MedicionCampoMagneticoImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MedicionCampoMagneticoImg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MedicionCampoMagneticoImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MedicionCampoMagneticoImg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_MedicionCampoMagneticoImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MedicionCampoMagneticoValue = lv_label_create(ui_MedicionCampoMagnetico);
    lv_obj_set_width(ui_MedicionCampoMagneticoValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MedicionCampoMagneticoValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MedicionCampoMagneticoValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MedicionCampoMagneticoValue, "0.0 mT");
    lv_obj_set_style_text_font(ui_MedicionCampoMagneticoValue, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MedicionCampoMagneticoLastUpdate = lv_label_create(ui_MedicionCampoMagnetico);
    lv_obj_set_width(ui_MedicionCampoMagneticoLastUpdate, lv_pct(100));
    lv_obj_set_height(ui_MedicionCampoMagneticoLastUpdate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MedicionCampoMagneticoLastUpdate, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MedicionCampoMagneticoLastUpdate, "Sin datos");
    lv_obj_set_style_text_align(ui_MedicionCampoMagneticoLastUpdate, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MedicionCampoMagneticoLastUpdate, &lv_font_montserrat_10,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabPageAlertas = lv_tabview_add_tab(ui_RunningTabView, "Alertas");
    lv_obj_set_flex_flow(ui_TabPageAlertas, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_TabPageAlertas, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_style_bg_color(ui_TabPageAlertas, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TabPageAlertas, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Alert1 = lv_obj_create(ui_TabPageAlertas);
    lv_obj_set_width(ui_Alert1, 250);
    lv_obj_set_height(ui_Alert1, 50);
    lv_obj_set_align(ui_Alert1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Alert1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Alert1, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Alert1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Alert1CritImg = lv_image_create(ui_Alert1);
    lv_image_set_src(ui_Alert1CritImg, &ui_img_alertacritica_png);
    lv_obj_set_width(ui_Alert1CritImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Alert1CritImg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Alert1CritImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Alert1CritImg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Alert1CritImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Alert1WarningImg = lv_image_create(ui_Alert1);
    lv_image_set_src(ui_Alert1WarningImg, &ui_img_estadowarning_png);
    lv_obj_set_width(ui_Alert1WarningImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Alert1WarningImg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Alert1WarningImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Alert1WarningImg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Alert1WarningImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Alert1TypeAlertSource = lv_obj_create(ui_Alert1);
    lv_obj_remove_style_all(ui_Alert1TypeAlertSource);
    lv_obj_set_width(ui_Alert1TypeAlertSource, 110);
    lv_obj_set_height(ui_Alert1TypeAlertSource, 40);
    lv_obj_set_align(ui_Alert1TypeAlertSource, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Alert1TypeAlertSource, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Alert1TypeAlertSource, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Alert1TypeAlertSource, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Alert1TypeAlertText = lv_label_create(ui_Alert1TypeAlertSource);
    lv_obj_set_width(ui_Alert1TypeAlertText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Alert1TypeAlertText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Alert1TypeAlertText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Alert1TypeAlertText, "TYPE ALERT");
    lv_obj_set_style_text_font(ui_Alert1TypeAlertText, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Alert1SourceText = lv_label_create(ui_Alert1TypeAlertSource);
    lv_obj_set_width(ui_Alert1SourceText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Alert1SourceText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Alert1SourceText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Alert1SourceText, "SOURCE");
    lv_obj_set_style_text_font(ui_Alert1SourceText, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Alert1StatsLastUpdate = lv_obj_create(ui_Alert1);
    lv_obj_remove_style_all(ui_Alert1StatsLastUpdate);
    lv_obj_set_width(ui_Alert1StatsLastUpdate, 66);
    lv_obj_set_height(ui_Alert1StatsLastUpdate, 40);
    lv_obj_set_align(ui_Alert1StatsLastUpdate, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Alert1StatsLastUpdate, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Alert1StatsLastUpdate, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_END);
    lv_obj_remove_flag(ui_Alert1StatsLastUpdate, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Alert1Stats = lv_obj_create(ui_Alert1StatsLastUpdate);
    lv_obj_remove_style_all(ui_Alert1Stats);
    lv_obj_set_width(ui_Alert1Stats, 59);
    lv_obj_set_height(ui_Alert1Stats, 19);
    lv_obj_set_align(ui_Alert1Stats, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Alert1Stats, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Alert1Stats, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_END);
    lv_obj_remove_flag(ui_Alert1Stats, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Alert1StatsCountText = lv_label_create(ui_Alert1Stats);
    lv_obj_set_width(ui_Alert1StatsCountText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Alert1StatsCountText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Alert1StatsCountText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Alert1StatsCountText, "0");
    lv_obj_set_style_text_font(ui_Alert1StatsCountText, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Alert1StatsSpacerText = lv_label_create(ui_Alert1Stats);
    lv_obj_set_width(ui_Alert1StatsSpacerText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Alert1StatsSpacerText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Alert1StatsSpacerText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Alert1StatsSpacerText, "/ ");
    lv_obj_set_style_text_font(ui_Alert1StatsSpacerText, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Alert1StatsMaxText = lv_label_create(ui_Alert1Stats);
    lv_obj_set_width(ui_Alert1StatsMaxText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Alert1StatsMaxText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Alert1StatsMaxText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Alert1StatsMaxText, "max");
    lv_obj_set_style_text_font(ui_Alert1StatsMaxText, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Alert1LastUpdateText = lv_label_create(ui_Alert1StatsLastUpdate);
    lv_obj_set_width(ui_Alert1LastUpdateText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Alert1LastUpdateText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Alert1LastUpdateText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Alert1LastUpdateText, "SIN DATOS");
    lv_obj_set_style_text_font(ui_Alert1LastUpdateText, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Alert2 = lv_obj_create(ui_TabPageAlertas);
    lv_obj_set_width(ui_Alert2, 250);
    lv_obj_set_height(ui_Alert2, 50);
    lv_obj_set_align(ui_Alert2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Alert2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Alert2, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Alert2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Alert2CritImg = lv_image_create(ui_Alert2);
    lv_image_set_src(ui_Alert2CritImg, &ui_img_alertacritica_png);
    lv_obj_set_width(ui_Alert2CritImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Alert2CritImg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Alert2CritImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Alert2CritImg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Alert2CritImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Alert2WarningImg = lv_image_create(ui_Alert2);
    lv_image_set_src(ui_Alert2WarningImg, &ui_img_estadowarning_png);
    lv_obj_set_width(ui_Alert2WarningImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Alert2WarningImg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Alert2WarningImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Alert2WarningImg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Alert2WarningImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Alert2TypeAlertSource = lv_obj_create(ui_Alert2);
    lv_obj_remove_style_all(ui_Alert2TypeAlertSource);
    lv_obj_set_width(ui_Alert2TypeAlertSource, 110);
    lv_obj_set_height(ui_Alert2TypeAlertSource, 40);
    lv_obj_set_align(ui_Alert2TypeAlertSource, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Alert2TypeAlertSource, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Alert2TypeAlertSource, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Alert2TypeAlertSource, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Alert2TypeAlertText = lv_label_create(ui_Alert2TypeAlertSource);
    lv_obj_set_width(ui_Alert2TypeAlertText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Alert2TypeAlertText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Alert2TypeAlertText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Alert2TypeAlertText, "TYPE ALERT");
    lv_obj_set_style_text_font(ui_Alert2TypeAlertText, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Alert2SourceText = lv_label_create(ui_Alert2TypeAlertSource);
    lv_obj_set_width(ui_Alert2SourceText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Alert2SourceText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Alert2SourceText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Alert2SourceText, "SOURCE");
    lv_obj_set_style_text_font(ui_Alert2SourceText, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Alert2StatsLastUpdate = lv_obj_create(ui_Alert2);
    lv_obj_remove_style_all(ui_Alert2StatsLastUpdate);
    lv_obj_set_width(ui_Alert2StatsLastUpdate, 66);
    lv_obj_set_height(ui_Alert2StatsLastUpdate, 40);
    lv_obj_set_align(ui_Alert2StatsLastUpdate, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Alert2StatsLastUpdate, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Alert2StatsLastUpdate, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_END);
    lv_obj_remove_flag(ui_Alert2StatsLastUpdate, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Alert2Stats = lv_obj_create(ui_Alert2StatsLastUpdate);
    lv_obj_remove_style_all(ui_Alert2Stats);
    lv_obj_set_width(ui_Alert2Stats, 59);
    lv_obj_set_height(ui_Alert2Stats, 19);
    lv_obj_set_align(ui_Alert2Stats, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Alert2Stats, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Alert2Stats, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_END);
    lv_obj_remove_flag(ui_Alert2Stats, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Alert2StatsCountText = lv_label_create(ui_Alert2Stats);
    lv_obj_set_width(ui_Alert2StatsCountText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Alert2StatsCountText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Alert2StatsCountText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Alert2StatsCountText, "0");
    lv_obj_set_style_text_font(ui_Alert2StatsCountText, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Alert2StatsSpacerText = lv_label_create(ui_Alert2Stats);
    lv_obj_set_width(ui_Alert2StatsSpacerText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Alert2StatsSpacerText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Alert2StatsSpacerText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Alert2StatsSpacerText, "/ ");
    lv_obj_set_style_text_font(ui_Alert2StatsSpacerText, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Alert2StatsMaxText = lv_label_create(ui_Alert2Stats);
    lv_obj_set_width(ui_Alert2StatsMaxText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Alert2StatsMaxText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Alert2StatsMaxText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Alert2StatsMaxText, "max");
    lv_obj_set_style_text_font(ui_Alert2StatsMaxText, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Alert2LastUpdateText = lv_label_create(ui_Alert2StatsLastUpdate);
    lv_obj_set_width(ui_Alert2LastUpdateText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Alert2LastUpdateText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Alert2LastUpdateText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Alert2LastUpdateText, "SIN DATOS");
    lv_obj_set_style_text_font(ui_Alert2LastUpdateText, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Alert3 = lv_obj_create(ui_TabPageAlertas);
    lv_obj_set_width(ui_Alert3, 250);
    lv_obj_set_height(ui_Alert3, 50);
    lv_obj_set_align(ui_Alert3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Alert3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Alert3, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Alert3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Alert3CritImg = lv_image_create(ui_Alert3);
    lv_image_set_src(ui_Alert3CritImg, &ui_img_alertacritica_png);
    lv_obj_set_width(ui_Alert3CritImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Alert3CritImg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Alert3CritImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Alert3CritImg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Alert3CritImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Alert2WarningImg1 = lv_image_create(ui_Alert3);
    lv_image_set_src(ui_Alert2WarningImg1, &ui_img_estadowarning_png);
    lv_obj_set_width(ui_Alert2WarningImg1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Alert2WarningImg1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Alert2WarningImg1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Alert2WarningImg1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Alert2WarningImg1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Alert3TypeAlertSource = lv_obj_create(ui_Alert3);
    lv_obj_remove_style_all(ui_Alert3TypeAlertSource);
    lv_obj_set_width(ui_Alert3TypeAlertSource, 110);
    lv_obj_set_height(ui_Alert3TypeAlertSource, 40);
    lv_obj_set_align(ui_Alert3TypeAlertSource, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Alert3TypeAlertSource, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Alert3TypeAlertSource, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Alert3TypeAlertSource, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Alert3TypeAlertText = lv_label_create(ui_Alert3TypeAlertSource);
    lv_obj_set_width(ui_Alert3TypeAlertText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Alert3TypeAlertText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Alert3TypeAlertText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Alert3TypeAlertText, "TYPE ALERT");
    lv_obj_set_style_text_font(ui_Alert3TypeAlertText, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Alert3SourceText = lv_label_create(ui_Alert3TypeAlertSource);
    lv_obj_set_width(ui_Alert3SourceText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Alert3SourceText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Alert3SourceText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Alert3SourceText, "SOURCE");
    lv_obj_set_style_text_font(ui_Alert3SourceText, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Alert3StatsLastUpdate = lv_obj_create(ui_Alert3);
    lv_obj_remove_style_all(ui_Alert3StatsLastUpdate);
    lv_obj_set_width(ui_Alert3StatsLastUpdate, 66);
    lv_obj_set_height(ui_Alert3StatsLastUpdate, 40);
    lv_obj_set_align(ui_Alert3StatsLastUpdate, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Alert3StatsLastUpdate, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Alert3StatsLastUpdate, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_END);
    lv_obj_remove_flag(ui_Alert3StatsLastUpdate, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Alert3Stats = lv_obj_create(ui_Alert3StatsLastUpdate);
    lv_obj_remove_style_all(ui_Alert3Stats);
    lv_obj_set_width(ui_Alert3Stats, 59);
    lv_obj_set_height(ui_Alert3Stats, 19);
    lv_obj_set_align(ui_Alert3Stats, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Alert3Stats, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Alert3Stats, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_END);
    lv_obj_remove_flag(ui_Alert3Stats, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Alert3StatsCountText = lv_label_create(ui_Alert3Stats);
    lv_obj_set_width(ui_Alert3StatsCountText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Alert3StatsCountText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Alert3StatsCountText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Alert3StatsCountText, "0");
    lv_obj_set_style_text_font(ui_Alert3StatsCountText, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Alert3StatsSpacerText = lv_label_create(ui_Alert3Stats);
    lv_obj_set_width(ui_Alert3StatsSpacerText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Alert3StatsSpacerText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Alert3StatsSpacerText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Alert3StatsSpacerText, "/ ");
    lv_obj_set_style_text_font(ui_Alert3StatsSpacerText, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Alert3StatsMaxText = lv_label_create(ui_Alert3Stats);
    lv_obj_set_width(ui_Alert3StatsMaxText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Alert3StatsMaxText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Alert3StatsMaxText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Alert3StatsMaxText, "max");
    lv_obj_set_style_text_font(ui_Alert3StatsMaxText, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Alert3LastUpdateText = lv_label_create(ui_Alert3StatsLastUpdate);
    lv_obj_set_width(ui_Alert3LastUpdateText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Alert3LastUpdateText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Alert3LastUpdateText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Alert3LastUpdateText, "SIN DATOS");
    lv_obj_set_style_text_font(ui_Alert3LastUpdateText, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Running_screen_destroy(void)
{
    if(ui_Running) lv_obj_del(ui_Running);

    // NULL screen variables
    ui_Running = NULL;
    ui_RunningMain = NULL;
    ui_RunningMainContenido = NULL;
    ui_RunningTabView = NULL;
    ui_TabPageProgress = NULL;
    ui_ElapsedTime = NULL;
    ui_ElapsedTimeTitle = NULL;
    ui_ElapsedTimeValue = NULL;
    ui_TotalProgress = NULL;
    ui_TotalProgressTitle = NULL;
    ui_TotalProgressBar = NULL;
    ui_TotalProgressValue = NULL;
    ui_ProgressHealth = NULL;
    ui_ProgressHealthTitle = NULL;
    ui_HealthEstado = NULL;
    ui_HealthNormalImg = NULL;
    ui_HealthWarningImg = NULL;
    ui_HealthCriticalImg = NULL;
    ui_TabPageProgressBtnDetener = NULL;
    ui_TabPageProgressBtnDetenerText = NULL;
    ui_TabPageObjetivos = NULL;
    ui_RunningObjetivosTitle = NULL;
    ui_RunningObjetivos = NULL;
    ui_RunningObjetivoIntensidad = NULL;
    ui_RunningObjetivoIntensidadImg = NULL;
    ui_RunningObjetivoIntensidadValue = NULL;
    ui_RunningObjetivoFreq = NULL;
    ui_RunningObjetivoFreqImg = NULL;
    ui_RunningObjetivoFreqValue = NULL;
    ui_RunningObjetivoDuracion = NULL;
    ui_RunningObjetivoDuracionImg = NULL;
    ui_RunningObjetivoDuracionValue = NULL;
    ui_RunningRangosTitle = NULL;
    ui_RunningRangos = NULL;
    ui_RunningRangoIntensidad = NULL;
    ui_RunningRangoIntensidadImg = NULL;
    ui_RunningRangoIntensidadValue = NULL;
    ui_RunningRangoTempNormal = NULL;
    ui_RunningRangoTempNormalImg = NULL;
    ui_RunningRangoTempNormalValue = NULL;
    ui_RunningRangoTempCritica = NULL;
    ui_RunningRangoTempCriticaImg = NULL;
    ui_RunningRangoTempCriticaValue = NULL;
    ui_TabPageMediciones = NULL;
    ui_MedicionTemperatura = NULL;
    ui_MedicionTemperaturaArc = NULL;
    ui_MedicionTempImg = NULL;
    ui_MedicionTempValue = NULL;
    ui_MedicionTempLastUpdate = NULL;
    ui_MedicionCorriente = NULL;
    ui_MedicionCorrienteArc = NULL;
    ui_MedicionCorrienteImg = NULL;
    ui_MedicionCorrienteValue = NULL;
    ui_MedicionCorrienteLastUpdate = NULL;
    ui_MedicionCampoMagnetico = NULL;
    ui_MedicionCampoMagneticoArc = NULL;
    ui_MedicionCampoMagneticoImg = NULL;
    ui_MedicionCampoMagneticoValue = NULL;
    ui_MedicionCampoMagneticoLastUpdate = NULL;
    ui_TabPageAlertas = NULL;
    ui_Alert1 = NULL;
    ui_Alert1CritImg = NULL;
    ui_Alert1WarningImg = NULL;
    ui_Alert1TypeAlertSource = NULL;
    ui_Alert1TypeAlertText = NULL;
    ui_Alert1SourceText = NULL;
    ui_Alert1StatsLastUpdate = NULL;
    ui_Alert1Stats = NULL;
    ui_Alert1StatsCountText = NULL;
    ui_Alert1StatsSpacerText = NULL;
    ui_Alert1StatsMaxText = NULL;
    ui_Alert1LastUpdateText = NULL;
    ui_Alert2 = NULL;
    ui_Alert2CritImg = NULL;
    ui_Alert2WarningImg = NULL;
    ui_Alert2TypeAlertSource = NULL;
    ui_Alert2TypeAlertText = NULL;
    ui_Alert2SourceText = NULL;
    ui_Alert2StatsLastUpdate = NULL;
    ui_Alert2Stats = NULL;
    ui_Alert2StatsCountText = NULL;
    ui_Alert2StatsSpacerText = NULL;
    ui_Alert2StatsMaxText = NULL;
    ui_Alert2LastUpdateText = NULL;
    ui_Alert3 = NULL;
    ui_Alert3CritImg = NULL;
    ui_Alert2WarningImg1 = NULL;
    ui_Alert3TypeAlertSource = NULL;
    ui_Alert3TypeAlertText = NULL;
    ui_Alert3SourceText = NULL;
    ui_Alert3StatsLastUpdate = NULL;
    ui_Alert3Stats = NULL;
    ui_Alert3StatsCountText = NULL;
    ui_Alert3StatsSpacerText = NULL;
    ui_Alert3StatsMaxText = NULL;
    ui_Alert3LastUpdateText = NULL;

}
