// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: UiFinalParte1

#include "ui.h"

lv_obj_t * ui_ResultadoScreen = NULL;
lv_obj_t * ui_ResultadoHeader = NULL;
lv_obj_t * ui_ResultadoTitle = NULL;
lv_obj_t * ui_ResultadoMain = NULL;
lv_obj_t * ui_ResultadoCompletado = NULL;
lv_obj_t * ui_ResultadoMotivoCompletado = NULL;
lv_obj_t * ui_ResultadoMotivoCompletadoTitle = NULL;
lv_obj_t * ui_ResultadoMotivoCompletadoTipoCampo = NULL;
lv_obj_t * ui_ResultadoMotivoCompletadoDetalle = NULL;
lv_obj_t * ui_ResultadoMotivoCompletadoMotivo = NULL;
lv_obj_t * ui_ResultadoMotivoCompletadoMotivoDetalle = NULL;
lv_obj_t * ui_ResultadoDetenido = NULL;
lv_obj_t * ui_ResultadoMotivoDetenido = NULL;
lv_obj_t * ui_ResultadoMotivoDetenidoTitle = NULL;
lv_obj_t * ui_ResultadoMotivoDetenidoTipoCampo = NULL;
lv_obj_t * ui_ResultadoMotivoDetenidoDetalle = NULL;
lv_obj_t * ui_ResultadoMotivoDetenidoMotivo = NULL;
lv_obj_t * ui_ResultadoMotivoDetenidoMotivoDetalle = NULL;
lv_obj_t * ui_ResultadoFalla = NULL;
lv_obj_t * ui_ResultadoMotivoFalla = NULL;
lv_obj_t * ui_ResultadoMotivoFallaTitle = NULL;
lv_obj_t * ui_ResultadoMotivoFallaTipoCampo = NULL;
lv_obj_t * ui_ResultadoMotivoFallaDetalle = NULL;
lv_obj_t * ui_ResultadoMotivoFallaMotivo = NULL;
lv_obj_t * ui_ResultadoMotivoFallaMotivoDetalle = NULL;
lv_obj_t * ui_ResultadoResumen = NULL;
lv_obj_t * ui_ResultadoProgreso = NULL;
lv_obj_t * ui_ResultadoProgresoTitle = NULL;
lv_obj_t * ui_ResultadoProgresoData = NULL;
lv_obj_t * ui_ResultadoProgresoValor = NULL;
lv_obj_t * ui_ResultadoTranscurrido = NULL;
lv_obj_t * ui_ResultadoTranscurridoTitle = NULL;
lv_obj_t * ui_ResultadoTranscurridoData = NULL;
lv_obj_t * ui_ResultadoTranscurridoDataHoras = NULL;
lv_obj_t * ui_ResultadoProgresoHorasValor = NULL;
lv_obj_t * ui_ResultadoProgresoHorasTitle = NULL;
lv_obj_t * ui_ResultadoTranscurridoDataMinutos = NULL;
lv_obj_t * ui_ResultadoProgresoMinutosValor = NULL;
lv_obj_t * ui_ResultadoProgresoMinutosTitle = NULL;
lv_obj_t * ui_ResultadoCampoMedio = NULL;
lv_obj_t * ui_ResultadoCampoMedioTitle = NULL;
lv_obj_t * ui_ResultadoCampoMedioData = NULL;
lv_obj_t * ui_ResultadoCampoMedioUnidadValor = NULL;
lv_obj_t * ui_ResultadoCampoMedioUnidadTitle = NULL;
lv_obj_t * ui_ResultadoOptionsButtons = NULL;
lv_obj_t * ui_ButtonResultadoPrincipal = NULL;
lv_obj_t * ui_ButtonResultadoPrincipalTexto = NULL;
lv_obj_t * ui_ButtonResultadoRepetir = NULL;
lv_obj_t * ui_ButtonResultadoRepetirTexto = NULL;
// event funtions

// build funtions

void ui_ResultadoScreen_screen_init(void)
{
    ui_ResultadoScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_ResultadoScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_ResultadoScreen, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_ResultadoScreen, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_style_bg_color(ui_ResultadoScreen, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ResultadoScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ResultadoScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ResultadoScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ResultadoScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ResultadoScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_ResultadoScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ResultadoScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ResultadoHeader = lv_obj_create(ui_ResultadoScreen);
    lv_obj_set_height(ui_ResultadoHeader, 40);
    lv_obj_set_width(ui_ResultadoHeader, lv_pct(100));
    lv_obj_set_align(ui_ResultadoHeader, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ResultadoHeader, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ResultadoHeader, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ResultadoHeader, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ResultadoHeader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ResultadoHeader, lv_color_hex(0x0A3358), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ResultadoHeader, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ResultadoHeader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ResultadoHeader, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ResultadoHeader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ResultadoHeader, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ResultadoHeader, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_ResultadoHeader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ResultadoHeader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ResultadoTitle = lv_label_create(ui_ResultadoHeader);
    lv_obj_set_width(ui_ResultadoTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ResultadoTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ResultadoTitle, 0);
    lv_obj_set_y(ui_ResultadoTitle, 1);
    lv_obj_set_align(ui_ResultadoTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ResultadoTitle, "RESULTADO");
    lv_obj_set_style_text_color(ui_ResultadoTitle, lv_color_hex(0x7FC0FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ResultadoTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ResultadoTitle, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ResultadoMain = lv_obj_create(ui_ResultadoScreen);
    lv_obj_set_height(ui_ResultadoMain, 160);
    lv_obj_set_width(ui_ResultadoMain, lv_pct(100));
    lv_obj_set_align(ui_ResultadoMain, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ResultadoMain, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_ResultadoMain, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_ResultadoMain, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ResultadoMain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ResultadoMain, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ResultadoMain, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ResultadoMain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ResultadoMain, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ResultadoMain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ResultadoMain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ResultadoMain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ResultadoMain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_ResultadoMain, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ResultadoMain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ResultadoCompletado = lv_obj_create(ui_ResultadoMain);
    lv_obj_remove_style_all(ui_ResultadoCompletado);
    lv_obj_set_width(ui_ResultadoCompletado, lv_pct(100));
    lv_obj_set_height(ui_ResultadoCompletado, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_ResultadoCompletado, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ResultadoCompletado, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_ResultadoCompletado, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_ResultadoCompletado, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_ResultadoCompletado, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ResultadoCompletado, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ResultadoCompletado, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ResultadoCompletado, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_ResultadoCompletado, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ResultadoCompletado, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ResultadoMotivoCompletado = lv_obj_create(ui_ResultadoCompletado);
    lv_obj_set_width(ui_ResultadoMotivoCompletado, lv_pct(100));
    lv_obj_set_height(ui_ResultadoMotivoCompletado, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_ResultadoMotivoCompletado, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ResultadoMotivoCompletado, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ResultadoMotivoCompletado, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_END,
                          LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_ResultadoMotivoCompletado, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ResultadoMotivoCompletado, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ResultadoMotivoCompletado, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ResultadoMotivoCompletado, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ResultadoMotivoCompletado, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ResultadoMotivoCompletado, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ResultadoMotivoCompletado, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ResultadoMotivoCompletado, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ResultadoMotivoCompletado, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ResultadoMotivoCompletado, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ResultadoMotivoCompletado, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ResultadoMotivoCompletado, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_ResultadoMotivoCompletado, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ResultadoMotivoCompletado, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ResultadoMotivoCompletadoTitle = lv_label_create(ui_ResultadoMotivoCompletado);
    lv_obj_set_width(ui_ResultadoMotivoCompletadoTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ResultadoMotivoCompletadoTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ResultadoMotivoCompletadoTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ResultadoMotivoCompletadoTitle, "COMPLETADO");
    lv_obj_set_style_text_color(ui_ResultadoMotivoCompletadoTitle, lv_color_hex(0x0F5893), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ResultadoMotivoCompletadoTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ResultadoMotivoCompletadoTitle, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ResultadoMotivoCompletadoTipoCampo = lv_label_create(ui_ResultadoMotivoCompletado);
    lv_obj_set_width(ui_ResultadoMotivoCompletadoTipoCampo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ResultadoMotivoCompletadoTipoCampo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ResultadoMotivoCompletadoTipoCampo, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ResultadoMotivoCompletadoTipoCampo, "CAMPO X");
    lv_obj_set_style_text_color(ui_ResultadoMotivoCompletadoTipoCampo, lv_color_hex(0x000000),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ResultadoMotivoCompletadoTipoCampo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ResultadoMotivoCompletadoTipoCampo, &lv_font_montserrat_12,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ResultadoMotivoCompletadoDetalle = lv_obj_create(ui_ResultadoCompletado);
    lv_obj_set_height(ui_ResultadoMotivoCompletadoDetalle, 50);
    lv_obj_set_width(ui_ResultadoMotivoCompletadoDetalle, lv_pct(100));
    lv_obj_set_align(ui_ResultadoMotivoCompletadoDetalle, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ResultadoMotivoCompletadoDetalle, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_ResultadoMotivoCompletadoDetalle, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START,
                          LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_ResultadoMotivoCompletadoDetalle, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ResultadoMotivoCompletadoDetalle, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ResultadoMotivoCompletadoDetalle, lv_color_hex(0xCFE3FA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ResultadoMotivoCompletadoDetalle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ResultadoMotivoCompletadoDetalle, lv_color_hex(0x16639E),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ResultadoMotivoCompletadoDetalle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ResultadoMotivoCompletadoDetalle, LV_BORDER_SIDE_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ResultadoMotivoCompletadoDetalle, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ResultadoMotivoCompletadoDetalle, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ResultadoMotivoCompletadoDetalle, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ResultadoMotivoCompletadoDetalle, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_ResultadoMotivoCompletadoDetalle, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ResultadoMotivoCompletadoDetalle, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ResultadoMotivoCompletadoMotivo = lv_label_create(ui_ResultadoMotivoCompletadoDetalle);
    lv_obj_set_width(ui_ResultadoMotivoCompletadoMotivo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ResultadoMotivoCompletadoMotivo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ResultadoMotivoCompletadoMotivo, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ResultadoMotivoCompletadoMotivo, "LA EXPOSICION LLEGO A SU FIN");
    lv_obj_set_style_text_color(ui_ResultadoMotivoCompletadoMotivo, lv_color_hex(0x0A3358),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ResultadoMotivoCompletadoMotivo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ResultadoMotivoCompletadoMotivoDetalle = lv_label_create(ui_ResultadoMotivoCompletadoDetalle);
    lv_obj_set_width(ui_ResultadoMotivoCompletadoMotivoDetalle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ResultadoMotivoCompletadoMotivoDetalle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ResultadoMotivoCompletadoMotivoDetalle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ResultadoMotivoCompletadoMotivoDetalle, "2 advertencias registradas - ninguna alcanzo el corte");
    lv_obj_set_style_text_color(ui_ResultadoMotivoCompletadoMotivoDetalle, lv_color_hex(0x16639E),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ResultadoMotivoCompletadoMotivoDetalle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ResultadoMotivoCompletadoMotivoDetalle, &lv_font_montserrat_8,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ResultadoDetenido = lv_obj_create(ui_ResultadoMain);
    lv_obj_remove_style_all(ui_ResultadoDetenido);
    lv_obj_set_width(ui_ResultadoDetenido, lv_pct(100));
    lv_obj_set_height(ui_ResultadoDetenido, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_ResultadoDetenido, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ResultadoDetenido, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_ResultadoDetenido, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_ResultadoDetenido, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_ResultadoDetenido, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_ResultadoDetenido, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ResultadoDetenido, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ResultadoDetenido, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ResultadoDetenido, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_ResultadoDetenido, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ResultadoDetenido, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ResultadoMotivoDetenido = lv_obj_create(ui_ResultadoDetenido);
    lv_obj_set_width(ui_ResultadoMotivoDetenido, lv_pct(100));
    lv_obj_set_height(ui_ResultadoMotivoDetenido, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_ResultadoMotivoDetenido, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ResultadoMotivoDetenido, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ResultadoMotivoDetenido, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_ResultadoMotivoDetenido, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ResultadoMotivoDetenido, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ResultadoMotivoDetenido, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ResultadoMotivoDetenido, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ResultadoMotivoDetenido, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ResultadoMotivoDetenido, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ResultadoMotivoDetenido, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ResultadoMotivoDetenido, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ResultadoMotivoDetenido, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ResultadoMotivoDetenido, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ResultadoMotivoDetenido, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ResultadoMotivoDetenido, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_ResultadoMotivoDetenido, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ResultadoMotivoDetenido, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ResultadoMotivoDetenidoTitle = lv_label_create(ui_ResultadoMotivoDetenido);
    lv_obj_set_width(ui_ResultadoMotivoDetenidoTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ResultadoMotivoDetenidoTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ResultadoMotivoDetenidoTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ResultadoMotivoDetenidoTitle, "DETENIDO");
    lv_obj_set_style_text_font(ui_ResultadoMotivoDetenidoTitle, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ResultadoMotivoDetenidoTipoCampo = lv_label_create(ui_ResultadoMotivoDetenido);
    lv_obj_set_width(ui_ResultadoMotivoDetenidoTipoCampo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ResultadoMotivoDetenidoTipoCampo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ResultadoMotivoDetenidoTipoCampo, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ResultadoMotivoDetenidoTipoCampo, "CAMPO X");
    lv_obj_set_style_text_font(ui_ResultadoMotivoDetenidoTipoCampo, &lv_font_montserrat_12,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ResultadoMotivoDetenidoDetalle = lv_obj_create(ui_ResultadoDetenido);
    lv_obj_set_height(ui_ResultadoMotivoDetenidoDetalle, 50);
    lv_obj_set_width(ui_ResultadoMotivoDetenidoDetalle, lv_pct(100));
    lv_obj_set_align(ui_ResultadoMotivoDetenidoDetalle, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ResultadoMotivoDetenidoDetalle, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_ResultadoMotivoDetenidoDetalle, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_ResultadoMotivoDetenidoDetalle, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ResultadoMotivoDetenidoDetalle, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ResultadoMotivoDetenidoDetalle, lv_color_hex(0xD8D9DD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ResultadoMotivoDetenidoDetalle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ResultadoMotivoDetenidoDetalle, lv_color_hex(0x55585C),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ResultadoMotivoDetenidoDetalle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ResultadoMotivoDetenidoDetalle, LV_BORDER_SIDE_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ResultadoMotivoDetenidoDetalle, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ResultadoMotivoDetenidoDetalle, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ResultadoMotivoDetenidoDetalle, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ResultadoMotivoDetenidoDetalle, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_ResultadoMotivoDetenidoDetalle, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ResultadoMotivoDetenidoDetalle, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ResultadoMotivoDetenidoMotivo = lv_label_create(ui_ResultadoMotivoDetenidoDetalle);
    lv_obj_set_width(ui_ResultadoMotivoDetenidoMotivo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ResultadoMotivoDetenidoMotivo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ResultadoMotivoDetenidoMotivo, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ResultadoMotivoDetenidoMotivo, "EL OPERADOR DETUVO LA EXPOSICION");
    lv_obj_set_style_text_color(ui_ResultadoMotivoDetenidoMotivo, lv_color_hex(0x1D1F20), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ResultadoMotivoDetenidoMotivo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ResultadoMotivoDetenidoMotivoDetalle = lv_label_create(ui_ResultadoMotivoDetenidoDetalle);
    lv_obj_set_width(ui_ResultadoMotivoDetenidoMotivoDetalle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ResultadoMotivoDetenidoMotivoDetalle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ResultadoMotivoDetenidoMotivoDetalle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ResultadoMotivoDetenidoMotivoDetalle, "a los 09m 12s - sin alertas activas al detener");
    lv_obj_set_style_text_color(ui_ResultadoMotivoDetenidoMotivoDetalle, lv_color_hex(0x1D1F20),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ResultadoMotivoDetenidoMotivoDetalle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ResultadoMotivoDetenidoMotivoDetalle, &lv_font_montserrat_8,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ResultadoFalla = lv_obj_create(ui_ResultadoMain);
    lv_obj_remove_style_all(ui_ResultadoFalla);
    lv_obj_set_width(ui_ResultadoFalla, lv_pct(100));
    lv_obj_set_height(ui_ResultadoFalla, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_ResultadoFalla, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ResultadoFalla, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_ResultadoFalla, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_ResultadoFalla, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_ResultadoFalla, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_ResultadoFalla, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ResultadoFalla, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ResultadoFalla, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ResultadoFalla, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_ResultadoFalla, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ResultadoFalla, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ResultadoMotivoFalla = lv_obj_create(ui_ResultadoFalla);
    lv_obj_set_width(ui_ResultadoMotivoFalla, lv_pct(100));
    lv_obj_set_height(ui_ResultadoMotivoFalla, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_ResultadoMotivoFalla, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ResultadoMotivoFalla, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ResultadoMotivoFalla, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_ResultadoMotivoFalla, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ResultadoMotivoFalla, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ResultadoMotivoFalla, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ResultadoMotivoFalla, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ResultadoMotivoFalla, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ResultadoMotivoFalla, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ResultadoMotivoFalla, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ResultadoMotivoFalla, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ResultadoMotivoFalla, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ResultadoMotivoFalla, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ResultadoMotivoFalla, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ResultadoMotivoFalla, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_ResultadoMotivoFalla, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ResultadoMotivoFalla, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ResultadoMotivoFallaTitle = lv_label_create(ui_ResultadoMotivoFalla);
    lv_obj_set_width(ui_ResultadoMotivoFallaTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ResultadoMotivoFallaTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ResultadoMotivoFallaTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ResultadoMotivoFallaTitle, "FALLA");
    lv_obj_set_style_text_color(ui_ResultadoMotivoFallaTitle, lv_color_hex(0xC1121F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ResultadoMotivoFallaTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ResultadoMotivoFallaTitle, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ResultadoMotivoFallaTipoCampo = lv_label_create(ui_ResultadoMotivoFalla);
    lv_obj_set_width(ui_ResultadoMotivoFallaTipoCampo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ResultadoMotivoFallaTipoCampo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ResultadoMotivoFallaTipoCampo, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ResultadoMotivoFallaTipoCampo, "CAMPO X");
    lv_obj_set_style_text_color(ui_ResultadoMotivoFallaTipoCampo, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ResultadoMotivoFallaTipoCampo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ResultadoMotivoFallaTipoCampo, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ResultadoMotivoFallaDetalle = lv_obj_create(ui_ResultadoFalla);
    lv_obj_set_height(ui_ResultadoMotivoFallaDetalle, 50);
    lv_obj_set_width(ui_ResultadoMotivoFallaDetalle, lv_pct(100));
    lv_obj_set_align(ui_ResultadoMotivoFallaDetalle, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ResultadoMotivoFallaDetalle, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_ResultadoMotivoFallaDetalle, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_ResultadoMotivoFallaDetalle, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ResultadoMotivoFallaDetalle, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ResultadoMotivoFallaDetalle, lv_color_hex(0xFBD5D2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ResultadoMotivoFallaDetalle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ResultadoMotivoFallaDetalle, lv_color_hex(0xC1121F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ResultadoMotivoFallaDetalle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ResultadoMotivoFallaDetalle, LV_BORDER_SIDE_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ResultadoMotivoFallaDetalle, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ResultadoMotivoFallaDetalle, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ResultadoMotivoFallaDetalle, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ResultadoMotivoFallaDetalle, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_ResultadoMotivoFallaDetalle, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ResultadoMotivoFallaDetalle, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ResultadoMotivoFallaMotivo = lv_label_create(ui_ResultadoMotivoFallaDetalle);
    lv_obj_set_width(ui_ResultadoMotivoFallaMotivo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ResultadoMotivoFallaMotivo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ResultadoMotivoFallaMotivo, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ResultadoMotivoFallaMotivo, "TEMP1 ALCANZO EL LIMITE CRITICO");
    lv_obj_set_style_text_color(ui_ResultadoMotivoFallaMotivo, lv_color_hex(0x1D1F20), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ResultadoMotivoFallaMotivo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ResultadoMotivoFallaMotivoDetalle = lv_label_create(ui_ResultadoMotivoFallaDetalle);
    lv_obj_set_width(ui_ResultadoMotivoFallaMotivoDetalle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ResultadoMotivoFallaMotivoDetalle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ResultadoMotivoFallaMotivoDetalle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ResultadoMotivoFallaMotivoDetalle, "4/4 ocurrencias - Ultima lectura 35.1 C - crItico 24-34 C");
    lv_obj_set_style_text_color(ui_ResultadoMotivoFallaMotivoDetalle, lv_color_hex(0x1D1F20),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ResultadoMotivoFallaMotivoDetalle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ResultadoMotivoFallaMotivoDetalle, &lv_font_montserrat_8,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ResultadoResumen = lv_obj_create(ui_ResultadoMain);
    lv_obj_set_width(ui_ResultadoResumen, lv_pct(100));
    lv_obj_set_height(ui_ResultadoResumen, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_ResultadoResumen, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ResultadoResumen, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ResultadoResumen, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_ResultadoResumen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ResultadoResumen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ResultadoResumen, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ResultadoResumen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ResultadoResumen, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ResultadoResumen, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ResultadoResumen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ResultadoResumen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ResultadoResumen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ResultadoResumen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_ResultadoResumen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ResultadoResumen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ResultadoProgreso = lv_obj_create(ui_ResultadoResumen);
    lv_obj_set_width(ui_ResultadoProgreso, lv_pct(33));
    lv_obj_set_height(ui_ResultadoProgreso, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_ResultadoProgreso, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ResultadoProgreso, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_ResultadoProgreso, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_ResultadoProgreso, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ResultadoProgreso, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ResultadoProgreso, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ResultadoProgreso, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ResultadoProgreso, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ResultadoProgreso, LV_BORDER_SIDE_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ResultadoProgreso, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ResultadoProgreso, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ResultadoProgreso, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ResultadoProgreso, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_ResultadoProgreso, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ResultadoProgreso, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ResultadoProgresoTitle = lv_label_create(ui_ResultadoProgreso);
    lv_obj_set_width(ui_ResultadoProgresoTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ResultadoProgresoTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ResultadoProgresoTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ResultadoProgresoTitle, "PROGRESO");
    lv_obj_set_style_text_font(ui_ResultadoProgresoTitle, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ResultadoProgresoData = lv_obj_create(ui_ResultadoProgreso);
    lv_obj_remove_style_all(ui_ResultadoProgresoData);
    lv_obj_set_width(ui_ResultadoProgresoData, 100);
    lv_obj_set_height(ui_ResultadoProgresoData, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_ResultadoProgresoData, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ResultadoProgresoData, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ResultadoProgresoData, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_ResultadoProgresoData, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ResultadoProgresoValor = lv_label_create(ui_ResultadoProgresoData);
    lv_obj_set_width(ui_ResultadoProgresoValor, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ResultadoProgresoValor, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ResultadoProgresoValor, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ResultadoProgresoValor, "100%");
    lv_obj_set_style_text_font(ui_ResultadoProgresoValor, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ResultadoTranscurrido = lv_obj_create(ui_ResultadoResumen);
    lv_obj_set_width(ui_ResultadoTranscurrido, lv_pct(33));
    lv_obj_set_height(ui_ResultadoTranscurrido, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_ResultadoTranscurrido, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ResultadoTranscurrido, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_ResultadoTranscurrido, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_ResultadoTranscurrido, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ResultadoTranscurrido, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ResultadoTranscurrido, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ResultadoTranscurrido, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ResultadoTranscurrido, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ResultadoTranscurrido, LV_BORDER_SIDE_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ResultadoTranscurrido, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ResultadoTranscurrido, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ResultadoTranscurrido, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ResultadoTranscurrido, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_ResultadoTranscurrido, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ResultadoTranscurrido, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ResultadoTranscurridoTitle = lv_label_create(ui_ResultadoTranscurrido);
    lv_obj_set_width(ui_ResultadoTranscurridoTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ResultadoTranscurridoTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ResultadoTranscurridoTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ResultadoTranscurridoTitle, "TRANSCURRIDO");
    lv_obj_set_style_text_font(ui_ResultadoTranscurridoTitle, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ResultadoTranscurridoData = lv_obj_create(ui_ResultadoTranscurrido);
    lv_obj_remove_style_all(ui_ResultadoTranscurridoData);
    lv_obj_set_width(ui_ResultadoTranscurridoData, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_ResultadoTranscurridoData, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_ResultadoTranscurridoData, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ResultadoTranscurridoData, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ResultadoTranscurridoData, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_ResultadoTranscurridoData, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_ResultadoTranscurridoData, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ResultadoTranscurridoData, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ResultadoTranscurridoData, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ResultadoTranscurridoData, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_ResultadoTranscurridoData, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ResultadoTranscurridoData, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ResultadoTranscurridoDataHoras = lv_obj_create(ui_ResultadoTranscurridoData);
    lv_obj_remove_style_all(ui_ResultadoTranscurridoDataHoras);
    lv_obj_set_width(ui_ResultadoTranscurridoDataHoras, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_ResultadoTranscurridoDataHoras, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_ResultadoTranscurridoDataHoras, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ResultadoTranscurridoDataHoras, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ResultadoTranscurridoDataHoras, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_ResultadoTranscurridoDataHoras, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_ResultadoTranscurridoDataHoras, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ResultadoTranscurridoDataHoras, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ResultadoTranscurridoDataHoras, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ResultadoTranscurridoDataHoras, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_ResultadoTranscurridoDataHoras, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ResultadoTranscurridoDataHoras, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ResultadoProgresoHorasValor = lv_label_create(ui_ResultadoTranscurridoDataHoras);
    lv_obj_set_width(ui_ResultadoProgresoHorasValor, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ResultadoProgresoHorasValor, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ResultadoProgresoHorasValor, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ResultadoProgresoHorasValor, "1");
    lv_obj_set_style_text_font(ui_ResultadoProgresoHorasValor, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ResultadoProgresoHorasTitle = lv_label_create(ui_ResultadoTranscurridoDataHoras);
    lv_obj_set_width(ui_ResultadoProgresoHorasTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ResultadoProgresoHorasTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ResultadoProgresoHorasTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ResultadoProgresoHorasTitle, "h");
    lv_obj_set_style_text_font(ui_ResultadoProgresoHorasTitle, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ResultadoTranscurridoDataMinutos = lv_obj_create(ui_ResultadoTranscurridoData);
    lv_obj_remove_style_all(ui_ResultadoTranscurridoDataMinutos);
    lv_obj_set_width(ui_ResultadoTranscurridoDataMinutos, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_ResultadoTranscurridoDataMinutos, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_ResultadoTranscurridoDataMinutos, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ResultadoTranscurridoDataMinutos, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ResultadoTranscurridoDataMinutos, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_ResultadoTranscurridoDataMinutos, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ResultadoProgresoMinutosValor = lv_label_create(ui_ResultadoTranscurridoDataMinutos);
    lv_obj_set_width(ui_ResultadoProgresoMinutosValor, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ResultadoProgresoMinutosValor, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ResultadoProgresoMinutosValor, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ResultadoProgresoMinutosValor, "20");
    lv_obj_set_style_text_font(ui_ResultadoProgresoMinutosValor, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ResultadoProgresoMinutosTitle = lv_label_create(ui_ResultadoTranscurridoDataMinutos);
    lv_obj_set_width(ui_ResultadoProgresoMinutosTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ResultadoProgresoMinutosTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ResultadoProgresoMinutosTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ResultadoProgresoMinutosTitle, "m");
    lv_obj_set_style_text_font(ui_ResultadoProgresoMinutosTitle, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ResultadoCampoMedio = lv_obj_create(ui_ResultadoResumen);
    lv_obj_set_width(ui_ResultadoCampoMedio, lv_pct(33));
    lv_obj_set_height(ui_ResultadoCampoMedio, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_ResultadoCampoMedio, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ResultadoCampoMedio, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_ResultadoCampoMedio, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_ResultadoCampoMedio, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ResultadoCampoMedio, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ResultadoCampoMedio, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ResultadoCampoMedio, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ResultadoCampoMedio, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ResultadoCampoMedio, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ResultadoCampoMedio, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ResultadoCampoMedio, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ResultadoCampoMedio, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ResultadoCampoMedio, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_ResultadoCampoMedio, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ResultadoCampoMedio, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ResultadoCampoMedioTitle = lv_label_create(ui_ResultadoCampoMedio);
    lv_obj_set_width(ui_ResultadoCampoMedioTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ResultadoCampoMedioTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ResultadoCampoMedioTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ResultadoCampoMedioTitle, "CAMPO MEDIO");
    lv_obj_set_style_text_font(ui_ResultadoCampoMedioTitle, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ResultadoCampoMedioData = lv_obj_create(ui_ResultadoCampoMedio);
    lv_obj_remove_style_all(ui_ResultadoCampoMedioData);
    lv_obj_set_width(ui_ResultadoCampoMedioData, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_ResultadoCampoMedioData, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_ResultadoCampoMedioData, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ResultadoCampoMedioData, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ResultadoCampoMedioData, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_ResultadoCampoMedioData, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_ResultadoCampoMedioData, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ResultadoCampoMedioData, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ResultadoCampoMedioData, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ResultadoCampoMedioData, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_ResultadoCampoMedioData, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ResultadoCampoMedioData, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ResultadoCampoMedioUnidadValor = lv_label_create(ui_ResultadoCampoMedioData);
    lv_obj_set_width(ui_ResultadoCampoMedioUnidadValor, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ResultadoCampoMedioUnidadValor, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ResultadoCampoMedioUnidadValor, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ResultadoCampoMedioUnidadValor, "1.00");
    lv_obj_set_style_text_font(ui_ResultadoCampoMedioUnidadValor, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ResultadoCampoMedioUnidadTitle = lv_label_create(ui_ResultadoCampoMedioData);
    lv_obj_set_width(ui_ResultadoCampoMedioUnidadTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ResultadoCampoMedioUnidadTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ResultadoCampoMedioUnidadTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ResultadoCampoMedioUnidadTitle, "mT");
    lv_obj_set_style_text_font(ui_ResultadoCampoMedioUnidadTitle, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ResultadoOptionsButtons = lv_obj_create(ui_ResultadoScreen);
    lv_obj_set_height(ui_ResultadoOptionsButtons, 40);
    lv_obj_set_width(ui_ResultadoOptionsButtons, lv_pct(100));
    lv_obj_set_align(ui_ResultadoOptionsButtons, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ResultadoOptionsButtons, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ResultadoOptionsButtons, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_ResultadoOptionsButtons, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ResultadoOptionsButtons, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ResultadoOptionsButtons, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ResultadoOptionsButtons, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ResultadoOptionsButtons, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ResultadoOptionsButtons, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ResultadoOptionsButtons, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ResultadoOptionsButtons, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ResultadoOptionsButtons, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ResultadoOptionsButtons, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_ResultadoOptionsButtons, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ResultadoOptionsButtons, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonResultadoPrincipal = lv_button_create(ui_ResultadoOptionsButtons);
    lv_obj_set_width(ui_ButtonResultadoPrincipal, lv_pct(50));
    lv_obj_set_height(ui_ButtonResultadoPrincipal, lv_pct(100));
    lv_obj_set_align(ui_ButtonResultadoPrincipal, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonResultadoPrincipal, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonResultadoPrincipal, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonResultadoPrincipal, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonResultadoPrincipal, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonResultadoPrincipal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ButtonResultadoPrincipal, lv_color_hex(0xB0B3B8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ButtonResultadoPrincipal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ButtonResultadoPrincipal, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonResultadoPrincipalTexto = lv_label_create(ui_ButtonResultadoPrincipal);
    lv_obj_set_width(ui_ButtonResultadoPrincipalTexto, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ButtonResultadoPrincipalTexto, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ButtonResultadoPrincipalTexto, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ButtonResultadoPrincipalTexto, "PRINCIPAL");
    lv_obj_set_style_text_color(ui_ButtonResultadoPrincipalTexto, lv_color_hex(0x1D1F20), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ButtonResultadoPrincipalTexto, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ButtonResultadoPrincipalTexto, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonResultadoRepetir = lv_button_create(ui_ResultadoOptionsButtons);
    lv_obj_set_width(ui_ButtonResultadoRepetir, lv_pct(50));
    lv_obj_set_height(ui_ButtonResultadoRepetir, lv_pct(100));
    lv_obj_set_align(ui_ButtonResultadoRepetir, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonResultadoRepetir, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonResultadoRepetir, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonResultadoRepetir, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonResultadoRepetir, lv_color_hex(0x16639E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonResultadoRepetir, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ButtonResultadoRepetir, lv_color_hex(0x2E628F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ButtonResultadoRepetir, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ButtonResultadoRepetir, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonResultadoRepetirTexto = lv_label_create(ui_ButtonResultadoRepetir);
    lv_obj_set_width(ui_ButtonResultadoRepetirTexto, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ButtonResultadoRepetirTexto, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ButtonResultadoRepetirTexto, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ButtonResultadoRepetirTexto, "REPETIR");
    lv_obj_set_style_text_font(ui_ButtonResultadoRepetirTexto, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_ResultadoScreen_screen_destroy(void)
{
    if(ui_ResultadoScreen) lv_obj_del(ui_ResultadoScreen);

    // NULL screen variables
    ui_ResultadoScreen = NULL;
    ui_ResultadoHeader = NULL;
    ui_ResultadoTitle = NULL;
    ui_ResultadoMain = NULL;
    ui_ResultadoCompletado = NULL;
    ui_ResultadoMotivoCompletado = NULL;
    ui_ResultadoMotivoCompletadoTitle = NULL;
    ui_ResultadoMotivoCompletadoTipoCampo = NULL;
    ui_ResultadoMotivoCompletadoDetalle = NULL;
    ui_ResultadoMotivoCompletadoMotivo = NULL;
    ui_ResultadoMotivoCompletadoMotivoDetalle = NULL;
    ui_ResultadoDetenido = NULL;
    ui_ResultadoMotivoDetenido = NULL;
    ui_ResultadoMotivoDetenidoTitle = NULL;
    ui_ResultadoMotivoDetenidoTipoCampo = NULL;
    ui_ResultadoMotivoDetenidoDetalle = NULL;
    ui_ResultadoMotivoDetenidoMotivo = NULL;
    ui_ResultadoMotivoDetenidoMotivoDetalle = NULL;
    ui_ResultadoFalla = NULL;
    ui_ResultadoMotivoFalla = NULL;
    ui_ResultadoMotivoFallaTitle = NULL;
    ui_ResultadoMotivoFallaTipoCampo = NULL;
    ui_ResultadoMotivoFallaDetalle = NULL;
    ui_ResultadoMotivoFallaMotivo = NULL;
    ui_ResultadoMotivoFallaMotivoDetalle = NULL;
    ui_ResultadoResumen = NULL;
    ui_ResultadoProgreso = NULL;
    ui_ResultadoProgresoTitle = NULL;
    ui_ResultadoProgresoData = NULL;
    ui_ResultadoProgresoValor = NULL;
    ui_ResultadoTranscurrido = NULL;
    ui_ResultadoTranscurridoTitle = NULL;
    ui_ResultadoTranscurridoData = NULL;
    ui_ResultadoTranscurridoDataHoras = NULL;
    ui_ResultadoProgresoHorasValor = NULL;
    ui_ResultadoProgresoHorasTitle = NULL;
    ui_ResultadoTranscurridoDataMinutos = NULL;
    ui_ResultadoProgresoMinutosValor = NULL;
    ui_ResultadoProgresoMinutosTitle = NULL;
    ui_ResultadoCampoMedio = NULL;
    ui_ResultadoCampoMedioTitle = NULL;
    ui_ResultadoCampoMedioData = NULL;
    ui_ResultadoCampoMedioUnidadValor = NULL;
    ui_ResultadoCampoMedioUnidadTitle = NULL;
    ui_ResultadoOptionsButtons = NULL;
    ui_ButtonResultadoPrincipal = NULL;
    ui_ButtonResultadoPrincipalTexto = NULL;
    ui_ButtonResultadoRepetir = NULL;
    ui_ButtonResultadoRepetirTexto = NULL;

}
