// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Splash

#include "ui.h"

lv_obj_t * ui_Splash = NULL;
lv_obj_t * ui_SplashImg = NULL;
// event funtions

// build funtions

void ui_Splash_screen_init(void)
{
    ui_Splash = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Splash, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SplashImg = lv_image_create(ui_Splash);
    lv_image_set_src(ui_SplashImg, &ui_img_splash_png);
    lv_obj_set_width(ui_SplashImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SplashImg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SplashImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SplashImg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_SplashImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}

void ui_Splash_screen_destroy(void)
{
    if(ui_Splash) lv_obj_del(ui_Splash);

    // NULL screen variables
    ui_Splash = NULL;
    ui_SplashImg = NULL;

}
