// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: UiFinalParte1

#include "ui.h"

lv_obj_t * ui_SplashScreen = NULL;
lv_obj_t * ui_Image1 = NULL;
// event funtions

// build funtions

void ui_SplashScreen_screen_init(void)
{
    ui_SplashScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_SplashScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SplashScreen, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SplashScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_image_create(ui_SplashScreen);
    lv_image_set_src(ui_Image1, &ui_img_fiuner3201_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_Image1, LV_IMAGE_ALIGN_TILE);

}

void ui_SplashScreen_screen_destroy(void)
{
    if(ui_SplashScreen) lv_obj_del(ui_SplashScreen);

    // NULL screen variables
    ui_SplashScreen = NULL;
    ui_Image1 = NULL;

}
